
class Danien: Book {
    
    override init() {
        super.init()
        title = "ÐA-NI-ÊN"
        chapters = allChapters
        allChapters.forEach{ $0.book = self }
    }
    
    var allChapters: [Chapter] = [
        Chapter(1, passages: [
            ["Bốn Thanh Niên I-sơ-ra-ên tại Kinh Ðô Ba-by-lôn": """
                1 Năm thứ ba của triều đại Giê-hô-gia-kim vua Giu-đa, Nê-bu-cát-nê-xa vua Ba-by-lôn đến Giê-ru-sa-lem và bao vây thành ấy.  2 Chúa phó Giê-hô-gia-kim vua Giu-đa và một số vật dụng trong Ðền Thờ Ðức Chúa Trời vào tay ông ấy.  Ông đem các vật dụng ấy về xứ Si-na và để các vật dụng ấy trong kho của đền thờ các thần của ông.
                3 Bấy giờ vua truyền cho Ách-pê-na quan chỉ huy các thái giám chọn trong hoàng tộc và hàng quý tộc của người I-sơ-ra-ên và đem đến một số thanh niên, 4 những người không tật nguyền, khôi ngô tuấn tú, có năng khiếu học mọi ngành, trí tuệ minh mẫn, thông minh sáng suốt, và có khả năng phục vụ nơi triều đình, để dạy họ ngôn ngữ và văn chương của người Canh-đê.
                5 Vua truyền nuôi họ hằng ngày bằng các thức ăn giống như trong thực đơn vua ăn và uống cùng thứ rượu vua uống.  Họ phải được huấn luyện trong ba năm.  Cuối ba năm đó họ sẽ được đứng hầu vua trong triều đình.
                6 Trong số những thanh niên ở Giu-đa có Ða-ni-ên, Ha-na-ni-a, Mi-sa-ên, và A-xa-ri-a.  7 Quan chỉ huy các thái giám đặt cho họ các tên mới.  Ông đặt tên cho Ða-ni-ên là Bên-tê-sác-xa, cho Ha-na-ni-a là Sa-đơ-rắc, cho Mi-sa-ên là Mê-sách, và cho A-xa-ri-a là A-bết-nê-gô.  8 Nhưng Ða-ni-ên quyết định trong lòng rằng chàng sẽ không để cho mình bị ô uế vì các thức ăn vua ban và các loại rượu vua uống; vì thế chàng xin quan chỉ huy các thái giám cho chàng được khỏi làm cho mình bị ô uế qua việc ăn uống các thức đó.  9 Bấy giờ Ðức Chúa Trời cho Ða-ni-ên được ơn và được thương mến trước mặt vị quan chỉ huy các thái giám.  10 Tuy nhiên vị quan chỉ huy các thái giám nói với Ða-ni-ên, “Ta sợ vua, chúa thượng của ta, đã chỉ định ta chăm sóc việc ăn uống của các ngươi.  Lẽ nào vua sẽ thấy mặt mày các ngươi tiều tụy hơn những người trẻ cùng trang lứa với các ngươi sao?  Ta không muốn bị mất đầu vì các ngươi.”
                11 Vậy Ða-ni-ên nói với người giám thị do quan chỉ huy các thái giám chỉ định để trông coi Ða-ni-ên, Ha-na-ni-a, Mi-sa-ên, và A-xa-ri-a, 12 “Xin ngài cho thử các tôi tớ ngài mười ngày.  Xin ngài truyền họ cho phép các tôi tớ ngài chỉ ăn rau và uống nước.  13 Sau đó xin ngài xem mặt mày chúng tôi và mặt mày các bạn trẻ đã ăn uống thực phẩm của vua ban, rồi xin ngài quyết định theo những gì ngài thấy.”
                14 Người ấy đồng ý như thế và cho thử họ trong mười ngày.  15 Cuối mười ngày, mặt mày họ trông hồng hào và đầy đặn hơn tất cả những người trẻ đã ăn uống thực phẩm của vua ban.  16 Vậy người giám thị ấy cất đi phần thức ăn và phần rượu họ sẽ uống và thay thế vào đó bằng rau.  17 Ðức Chúa Trời ban cho bốn thanh niên đó tri thức và thông sáng trong mọi lãnh vực văn chương và khoa học.  Ða-ni-ên được ban cho khả năng thấu hiểu mọi khải tượng và giấc mơ.
                18 Khi đến thời hạn vua đã định đem các thanh niên ấy ra trình diện, quan chỉ huy các thái giám đem họ ra trình diện Nê-bu-cát-nê-xa.  19 Vua nói chuyện với họ, và ông thấy chẳng ai có thể sánh bằng Ða-ni-ên, Ha-na-ni-a, Mi-sa-ên, và A-xa-ri-a; vì thế họ được phục vụ trước mặt vua.  20 Mỗi khi vua cần hỏi họ về bất cứ điều gì liên quan đến khôn ngoan và thông sáng, ông thấy họ giỏi gấp mười lần so với tất cả các pháp sư và các bốc sư trong toàn đế quốc.  21 Vậy Ða-ni-ên cứ ở đó cho đến năm đầu của triều đại Vua Ða-ri-út.

                """]
            ]),
        Chapter(2, passages: [
            ["Ðiềm Chiêm Bao của Vua Nê-bu-cát-nê-xa": """
                1 Trong năm thứ nhì của triều đại Nê-bu-cát-nê-xa, Nê-bu-cát-nê-xa nằm mơ và thấy các điềm chiêm bao.  Các điềm chiêm bao ấy đã làm cho tâm thần vua rối loạn, và vua bị mất ngủ.  2 Vì thế vua truyền triệu tập các pháp sư, các bốc sư, các phù thủy, và các chiêm tinh gia đến để giải nghĩa điềm chiêm bao cho vua.  Vậy những người ấy đến và đứng chầu trước mặt vua.  3 Vua phán với họ, “Ta đã thấy một điềm chiêm bao, và tâm thần ta bối rối vì muốn biết ý nghĩa của điềm chiêm bao ấy.”
                4 Các chiêm tinh gia tâu với vua bằng tiếng A-ram, “Tâu hoàng thượng, kính chúc hoàng thượng sống vạn tuế.  Xin hoàng thượng kể lại cho chúng thần điềm chiêm bao hoàng thượng đã thấy, chúng thần sẽ giải thích ý nghĩa của nó cho hoàng thượng.”
                5 Vua trả lời với các chiêm tinh gia, “Ðây là quyết định của ta: nếu các ngươi không nói cho ta biết trong giấc chiêm bao ta đã thấy gì và giải nghĩa điềm chiêm bao ấy cho ta, ta sẽ phân thây các ngươi ra từng mảnh và nhà các ngươi sẽ thành một đống đổ nát hoang tàn.  6 Còn nếu các ngươi nói cho ta biết ta đã nằm chiêm bao và thấy gì, rồi giải thích ý nghĩa của nó cho ta, thì các ngươi sẽ được ban thưởng các tặng vật, các phần thưởng, và quyền cao chức trọng.  Vậy hãy nói cho ta biết ta đã nằm chiêm bao và thấy gì, rồi giải thích ý nghĩa của nó cho ta.”
                7 Họ tâu lại với vua, “Xin hoàng thượng nói cho các tôi tớ của hoàng thượng biết hoàng thượng đã thấy gì trong điềm chiêm bao ấy, rồi chúng thần sẽ giải thích ý nghĩa của nó cho hoàng thượng.”
                8 Bấy giờ vua nói, “Ta biết các ngươi chỉ muốn kéo dài thời gian thôi, vì các ngươi đã nhận thấy lệnh đã ra khỏi miệng ta rồi.  9 Nếu các ngươi không nói cho ta biết điềm chiêm bao ta đã thấy là gì, thì sẽ chỉ có một lệnh dành cho các ngươi mà thôi.  Lâu nay các ngươi đã âm mưu với nhau và dùng những lời dối trá để gạt ta, với hy vọng rằng thời gian sẽ làm cho tình thế thay đổi.  Vậy bây giờ hãy nói cho ta biết điềm chiêm bao ta đã thấy là gì; bấy giờ ta sẽ biết các ngươi có thể giải thích ý nghĩa của nó hay không.”
                10 Các chiêm tinh gia tâu với vua, “Không người nào trên thế gian này có thể bày tỏ cho hoàng thượng điều hoàng thượng đòi hỏi.  Thật vậy, xưa nay chưa hề có vua, chúa, hay lãnh tụ nào đòi hỏi bất cứ pháp sư, bốc sư, hay chiêm tinh gia nào của họ những điều như thế.  11 Những gì hoàng thượng đòi hỏi thật khó quá.  Không ai có thể bày tỏ cho hoàng thượng được điều đó, ngoại trừ các thần, những đấng không ở giữa người phàm.”
                12 Ðiều đó làm cho vua tức giận và nổi trận lôi đình; vua truyền lịnh xử tử tất cả các nhà thông thái ở Ba-by-lôn.  13 Thế là lịnh được truyền ra, và người ta bắt đầu đi bắt giết các nhà thông thái.  Họ cũng đi tìm Ða-ni-ên và các bạn ông để giết họ.  14 Bấy giờ Ða-ni-ên nói một cách khôn ngoan và sáng suốt với A-ri-ốt quan phụ trách việc hành quyết, người đã ra đi để thi hành lệnh giết các nhà thông thái ở Ba-by-lôn.  15 Ông nói và hỏi A-ri-ốt, vị quan do vua sai đến, “Tại sao lệnh vua ban ra buộc phải thi hành cấp bách như vậy?”  Bấy giờ A-ri-ốt mới kể sự việc cho Ða-ni-ên hay.  16 Vì thế Ða-ni-ên xin vào chầu vua và xin vua gia hạn cho một thời gian để ông giải đoán ý nghĩa điềm chiêm bao cho vua.

                """],
            ["Ðức Chúa Trời Tỏ Cho Ða-ni-ên Biết Ðiềm Chiêm Bao": """
                17 Sau đó Ða-ni-ên về nhà và trình bày sự việc cho các bạn ông là Ha-na-ni-a, Mi-sa-ên, và A-xa-ri-a.  18 Ông giục họ hãy khẩn thiết cầu xin ơn thương xót của Ðức Chúa Trời trên trời về bí mật này, để Ða-ni-ên và các bạn ông không bị giết chung với các nhà thông thái khác của Ba-by-lôn.  19 Vậy bí mật ấy đã được mặc khải cho Ða-ni-ên qua một khải tượng trong ban đêm.  Do đó Ða-ni-ên ca ngợi Ðức Chúa Trời trên trời 20 và nói, “Chúc tụng danh Ðức Chúa Trời đời đời vô cùng, vì sự khôn ngoan và quyền năng đều thuộc về Ngài.  21 Ngài thay đổi thời tiết và mùa; Ngài phế và lập các vua; Ngài ban khôn ngoan cho những người khôn sáng và ban kiến thức cho những người trí thức.  22 Ngài mặc khải những việc sâu nhiệm và bí mật.  Ngài biết rõ những gì ở trong tối tăm, và ánh sáng hằng ở với Ngài.  23 Lạy Ðức Chúa Trời của tổ tiên chúng con, con xin cảm tạ Ngài và tôn ngợi Ngài.  Ngài đã ban cho con khôn ngoan và năng lực, và bây giờ Ngài lại bày tỏ cho con những điều chúng con cầu xin Ngài, vì Ngài quả đã cho chúng con biết những gì nhà vua đòi hỏi.”

                """],
            ["Ða-ni-ên Giải Nghĩa Chiêm Bao": """
                24 Vậy Ða-ni-ên đến gặp A-ri-ốt, vị quan được vua chỉ định thi hành lệnh hành quyết các nhà thông thái của Ba-by-lôn, và nói với ông ấy, “Xin ngài đừng giết các nhà thông thái của Ba-by-lôn.  Xin ngài đưa tôi vào gặp vua.  Tôi sẽ giải nghĩa điềm chiêm bao cho vua.”
                25 A-ri-ốt lập tức đưa Ða-ni-ên vào chầu vua và nói, “Hạ thần đã tìm được một người trong đám người bị lưu đày từ Giu-đa; người ấy có thể giải thích ý nghĩa của điềm chiêm bao cho chúa thượng.”
                26 Vua hỏi Ða-ni-ên cũng có tên là Bên-tê-sác-xa, “Ngươi có thể nói cho ta biết những gì ta đã thấy trong giấc chiêm bao và giải thích ý nghĩa của nó hay sao?”
                27 Ða-ni-ên trả lời với vua, “Không nhà thông thái nào, bốc sư nào, pháp sư nào, hoặc thầy bói nào có thể bày tỏ cho hoàng thượng biết bí mật hoàng thượng đã hỏi, 28 nhưng có một Ðức Chúa Trời trên trời, Ðấng mặc khải các bí mật.  Ngài đã bày tỏ cho Vua Nê-bu-cát-nê-xa biết những gì sẽ xảy đến trong những ngày tới.  Ðiềm chiêm bao của hoàng thượng và các khải tượng hiện ra trong đầu hoàng thượng khi hoàng thượng nằm trên giường là thế này:
                29 Tâu hoàng thượng, khi hoàng thượng nằm trên giường, tâm trí của hoàng thượng suy nghĩ đến những việc sẽ xảy ra sau này.  Ðấng bày tỏ những huyền bí đã bày tỏ cho hoàng thượng biết những gì sẽ xảy đến về sau.  30 Về phần hạ thần, huyền bí này được mặc khải cho hạ thần không phải vì hạ thần thông minh khôn sáng hơn người nào trên đời này, nhưng vì để hạ thần có thể giải nghĩa cho hoàng thượng, hầu hoàng thượng có thể hiểu rõ những suy nghĩ trong lòng mình.
                31 Tâu hoàng thượng, khi hoàng thượng đang nhìn, kìa, một pho tượng to lớn xuất hiện.  Pho tượng rực rỡ và uy nghi ấy đứng trước mặt hoàng thượng.  Hình dáng của pho tượng ấy thật kinh khiếp.  32 Ðầu của pho tượng làm bằng vàng ròng, ngực và hai tay bằng bạc, bụng và hai đùi bằng đồng, 33 và hai chân bằng sắt.  Hai bàn chân làm bằng một phần sắt và một phần đất sét.  34 Trong khi hoàng thượng nhìn nó, một tảng đá không do bàn tay loài người đục ra đã tông vào pho tượng ấy ngay chỗ hai bàn chân làm bằng sắt và đất sét, khiến pho tượng ấy vỡ nát thành những mảnh vụn.  35 Sau đó đất sét, sắt, đồng, bạc, và vàng đều rã vụn ra như bụi trấu nơi sân đập lúa mùa hè.  Gió thổi chúng bay đi tất cả, không chừa lại một vết tích nào.  Còn vầng đá đã tông vào pho tượng thì biến thành một núi lớn tràn đầy khắp mặt đất.  36 Ðó là điềm chiêm bao, và bây giờ chúng thần xin giải thích ý nghĩa của điềm chiêm bao ấy cho hoàng thượng.
                37 Tâu hoàng thượng, hoàng thượng là vua của các vua.  Ðức Chúa Trời trên trời đã ban cho hoàng thượng vương quốc, quyền thế, sức mạnh, và vinh hiển.  38 Ngài đã trao vào tay hoàng thượng loài người, thú đồng, và chim trời, bất kể chúng ở đâu, để lập hoàng thượng trị vì trên tất cả.  Hoàng thượng là cái đầu bằng vàng.  39 Sau hoàng thượng, một vương quốc khác sẽ trỗi lên, thấp kém hơn vương quốc của hoàng thượng.  Kế đó là một vương quốc nữa, vương quốc thứ ba làm bằng đồng; vương quốc ấy sẽ trị vì trên khắp mặt đất.  40 Tiếp theo là vương quốc thứ tư, nó cứng như sắt, vì sắt làm bể vụn và tan nát mọi thứ.  Giống như sắt, vương quốc ấy sẽ đập đổ và nghiền nát mọi vương quốc khác.  41 Tuy nhiên như hoàng thượng đã thấy hai bàn chân và các ngón chân, một phần làm bằng đất sét và một phần làm bằng sắt, vương quốc ấy sẽ gồm hai phần tử không hòa hợp với nhau; một ít sức mạnh của sắt vẫn ở trong đó, giống như hoàng thượng đã thấy sắt lẫn lộn với đất sét.  42 Giống như các ngón chân của hai bàn chân, một phần làm bằng sắt và một phần làm bằng đất sét; vương quốc ấy sẽ gồm một phần cứng mạnh và một phần yếu dòn.  43 Như hoàng thượng đã thấy sắt trộn lẫn với đất sét nung, dân trong vương quốc ấy sẽ là một tập thể hỗn hợp nhưng không đoàn kết với nhau, cũng giống như sắt không hòa hợp với đất sét vậy.
                44 Trong thời các vua đó, Ðức Chúa Trời trên trời sẽ lập nên một vương quốc không bao giờ bị hủy diệt, và không ai sẽ được nắm quyền của vương quốc ấy.  Vương quốc ấy sẽ nghiền nát và diệt trừ tất cả các vương quốc khác; còn nó sẽ cứ đứng vững đời đời.  45 Giống như hoàng thượng đã thấy, vầng đá được đục ra từ hòn núi nhưng không phải do tay loài người đục ra, vầng đá ấy sẽ đập nát sắt, đồng, đất sét, bạc, và vàng thành những mảnh vụn.  Ðức Chúa Trời vĩ đại trên trời đã bày tỏ cho hoàng thượng những gì sẽ xảy đến về sau này.  Ðiềm chiêm bao của hoàng thượng đã thấy là thật, và ý nghĩa của nó là chắc chắn.”

                """],
            ["Ða-ni-ên và Các Bạn Ông Ðược Thăng Thưởng": """
                46 Bấy giờ Vua Nê-bu-cát-nê-xa sấp mình xuống trước mặt Ða-ni-ên và lạy ông.  Vua truyền dâng một của lễ chay và dâng hương cho ông.  47 Vua nói với Ða-ni-ên, “Quả thật, Ðức Chúa Trời của ngươi đúng là Ðức Chúa Trời của các thần, Chúa của các vua, và Ðấng mặc khải những huyền bí, vì ngươi đã có thể bày tỏ huyền bí này.”
                48 Vua thăng chức cho Ða-ni-ên và ban cho ông nhiều món quà lớn.  Vua lập ông làm quan cai trị cả tỉnh Ba-by-lôn và làm lãnh tụ tất cả các nhà thông thái của Ba-by-lôn.  49 Ngoài ra theo lời tiến cử của Ða-ni-ên, vua bổ nhiệm Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô làm các quan điều hành trong tỉnh Ba-by-lôn, trong khi Ða-ni-ên phục vụ trong triều đình.

                """]
            ]),
        Chapter(3, passages: [
            ["Pho Tượng Bằng Vàng": """
                1 Vua Nê-bu-cát-nê-xa cho làm một pho tượng bằng vàng, cao ba mươi mét và rộng ba mét.  Ông dựng pho tượng ấy lên trong đồng bằng Ðu-ra, trong tỉnh Ba-by-lôn.  2 Vua Nê-bu-cát-nê-xa truyền triệu tập các thống đốc, các tỉnh trưởng, các tổng trấn, các mưu sĩ, các tổng giám đốc ngân khố, các thẩm phán, các chánh án, và tất cả các quan chức trong các tỉnh đến để dự lễ khánh thành pho tượng Vua Nê-bu-cát-nê-xa đã dựng lên.
                3 Vậy các thống đốc, các tỉnh trưởng, các tổng trấn, các mưu sĩ, các tổng giám đốc ngân khố, các thẩm phán, các chánh án, và tất cả các quan chức trong các tỉnh đều tề tựu đông đủ để tham dự lễ khánh thành pho tượng Vua Nê-bu-cát-nê-xa đã dựng lên, và họ đều đứng trước pho tượng Nê-bu-cát-nê-xa đã dựng lên.  4 Bấy giờ vị quan điều khiển buổi lễ hô to, “Ðây là lịnh truyền cho các ngươi phải làm, hỡi tất cả các dân, các nước, và các ngữ tộc: 5 Hễ khi nào các ngươi nghe tiếng kèn, tiếng sáo, tiếng hạc cầm, tiếng đàn lia, tiếng trống, và mọi thứ nhạc khí khác cùng trỗi lên, các ngươi phải sấp mình xuống và thờ lạy pho tượng vàng Vua Nê-bu-cát-nê-xa đã dựng lên.  6 Kẻ nào không sấp mình xuống thờ lạy pho tượng vàng sẽ lập tức bị quăng vào giữa lò lửa hừng.”
                7 Vì thế khi mọi người nghe tiếng kèn, tiếng sáo, tiếng hạc cầm, tiếng đàn lia, cùng với mọi thứ nhạc khí khác trỗi lên, mọi dân, mọi nước, và mọi ngữ tộc có mặt lúc đó đều sấp mình xuống và thờ lạy pho tượng vàng Vua Nê-bu-cát-nê-xa đã dựng lên.
                8 Khi ấy có mấy chiêm tinh gia người Canh-đê bước đến tố cáo những người Giu-đa.  9 Họ tâu với Vua Nê-bu-cát-nê-xa, “Tâu hoàng thượng, chúc hoàng thượng sống vạn tuế.  10 Tâu hoàng thượng, hoàng thượng đã ban một sắc lịnh rằng bất cứ người nào khi nghe tiếng kèn, tiếng sáo, tiếng hạc cầm, tiếng đàn lia, tiếng trống, và mọi thứ nhạc khí khác cùng trỗi lên thì phải sấp mình xuống và thờ lạy pho tượng vàng.  11 Còn kẻ nào không sấp mình xuống thờ lạy pho tượng ấy sẽ lập tức bị quăng vào giữa lò lửa hừng.  12 Thế nhưng có mấy người Giu-đa hoàng thượng đã lập lên làm quan điều hành công việc trong tỉnh Ba-by-lôn là Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô, tâu hoàng thượng, mấy người ấy chẳng coi lịnh của hoàng thượng ra gì.  Họ chẳng phục vụ các thần của hoàng thượng hay thờ lạy pho tượng vàng hoàng thượng đã dựng lên.”
                13 Bấy giờ Nê-bu-cát-nê-xa đùng đùng nổi giận.  Ông truyền đem Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô đến ngay.  Vậy họ dẫn những người ấy đến trước mặt vua.  14 Nê-bu-cát-nê-xa hỏi họ, “Hỡi Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô, có thật là các ngươi không phục vụ các thần của ta, hay không thờ lạy pho tượng vàng ta đã dựng lên chăng?  15 Bây giờ các ngươi khá sẵn sàng, hễ khi các ngươi nghe tiếng kèn, tiếng sáo, tiếng hạc cầm, tiếng đàn lia, tiếng trống, và mọi thứ nhạc khí khác cùng trỗi lên, nếu các ngươi sấp mình xuống và thờ lạy pho tượng vàng ta đã làm thì tốt.  Nhưng nếu các ngươi không thờ lạy, các ngươi sẽ lập tức bị quăng vào giữa lò lửa hừng.  Rồi để xem thần nào có thể cứu các ngươi khỏi tay ta chăng?”
                16 Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô trả lời với vua, “Tâu Vua Nê-bu-cát-nê-xa, về việc này chúng thần không cần phải binh vực cho chúng thần trước mặt hoàng thượng đâu.  17 Nếu hoàng thượng nhất định quăng chúng thần vào giữa lò lửa hừng thì Ðức Chúa Trời chúng thần thờ phượng sẽ giải cứu chúng thần khỏi lò lửa ấy, và Ngài sẽ giải cứu chúng thần khỏi tay hoàng thượng, tâu hoàng thượng.  18 Nhưng nếu Ngài không giải cứu chúng thần, thì tâu hoàng thượng, chúng thần xin hoàng thượng biết rằng chúng thần sẽ không phục vụ các thần của hoàng thượng hay thờ lạy pho tượng vàng mà hoàng thượng đã dựng lên đâu.”

                """],
            ["Lò Lửa Hừng": """
                19 Bấy giờ Nê-bu-cát-nê-xa cực kỳ tức giận. Da mặt ông đổi màu nghịch lại Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô.  Ông truyền lịnh đốt lò lửa nóng gấp bảy lần mức bình thường.  20 đoạn ông truyền cho các dũng sĩ lực lưỡng nhất trong quân đội của ông trói Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô lại, rồi ném họ vào lò lửa đang cháy hừng hực.  21 Vậy những người ấy bị trói lại và bị quăng vào giữa lò lửa hực.  Họ vẫn còn mặc áo choàng, quần dài, khăn trùm đầu, và quần áo lót bên trong.  22 Số là lịnh vua truyền quá cấp bách, và lò lửa lại nóng gấp nhiều lần hơn mức bình thường, nên các dũng sĩ có nhiệm vụ quăng Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô vào lò lửa đã bị ngọn lửa quá nóng làm chết.  23 Còn ba người đó, Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô, tay chân bị trói chặt, đã rơi vào giữa lò lửa hực.
                24 Bấy giờ Vua Nê-bu-cát-nê-xa lấy làm cực kỳ kinh ngạc và bật đứng dậy.  Ông hỏi các mưu sĩ của ông, “Chẳng phải chúng ta đã trói ba người và quăng vào lò lửa hay sao?”
                Họ đáp với ông, “Tâu hoàng thượng, đúng vậy.”
                25 Ông nói, “Hãy nhìn kìa! Ta thấy bốn người không bị trói đang đi giữa lò lửa, và họ chẳng bị hại gì; và hình dáng của người thứ tư giống như Con của Ðức Chúa Trời.”
                26 Bấy giờ Nê-bu-cát-nê-xa đến gần miệng lò lửa đang cháy hừng hực và kêu lớn, “Hỡi Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô, các đầy tớ của Ðức Chúa Trời Tối Cao, hãy đi ra, và hãy đến đây.”  Vậy Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô bước ra khỏi lò lửa.  27 Khi ấy các thống đốc, các tỉnh trưởng, các tổng trấn, và các mưu sĩ của vua tụ lại quanh ba người ấy; họ thấy lửa không làm hại gì đến thân thể ba người ấy.  Không sợi tóc nào trên đầu họ bị cháy sém, quần áo họ không bị một chút hư hại gì, và mùi lửa cũng không ngửi thấy trên người họ.
                28 Bấy giờ Nê-bu-cát-nê-xa nói, “Nguyện sự chúc tụng thuộc về Ðức Chúa Trời của Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô, Ðấng đã sai thiên sứ của Ngài đến giải cứu các đầy tớ Ngài, những người tin cậy Ngài.  Họ đã bất tuân lịnh vua, và thà chịu chết hơn là thờ phượng bất cứ thần nào khác ngoại trừ Ðức Chúa Trời của họ.  29 Vì thế ta truyền lịnh rằng bất cứ dân nào, nước nào, hay ngữ tộc nào nói điều gì xúc phạm đến Ðức Chúa Trời của Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô sẽ bị phân thây ra từng mảnh, và nhà của chúng sẽ bị biến thành một đống tro, vì không thần nào khác có thể giải cứu được như thế này.”  30 Sau đó vua thăng chức cho Sa-đơ-rắc, Mê-sách, và A-bết-nê-gô trong tỉnh Ba-by-lôn.

                """]
            ]),
        Chapter(4, passages: [
            ["Ðiềm Chiêm Bao Thứ Hai của Nê-bu-cát-nê-xa": """
                1 “Vua Nê-bu-cát-nê-xa gởi đến tất cả các dân, các nước, các ngữ tộc sống trong khắp đất:  Cầu mong các ngươi được bình an thịnh vượng bội phần.
                2 Ta lấy làm vui công bố cho các ngươi biết rằng Ðức Chúa Trời Tối Cao đã làm những dấu kỳ và phép lạ cho ta.  3 Các dấu kỳ của Ngài thật lớn lao!  Các phép lạ của Ngài thật diệu kỳ!  Vương quốc của Ngài là vương quốc đời đời!  Quyền tể trị của Ngài tồn tại từ đời nọ đến đời kia!
                4 Ta, Nê-bu-cát-nê-xa, đang sống nhàn hạ trong nhà ta và hưởng phúc lộc trong cung điện ta.  5 Ta thấy một điềm chiêm bao, và điềm chiêm bao ấy đã làm cho ta sợ.  Trong khi ta nằm trên giường, những tư tưởng cứ nảy ra trong trí, và những khải tượng cứ hiện ra trong đầu, đã làm ta lo sợ.  6 Vì thế ta truyền đem tất cả các nhà thông thái ở Ba-by-lôn đến để họ giải nghĩa điềm chiêm bao cho ta.  7 Vậy các pháp sư, các bốc sư, các chiêm tinh gia, và các thầy bói vào chầu ta.  Ta thuật lại cho họ điềm chiêm bao ấy, nhưng họ không thể giải thích ý nghĩa của nó được.  8 Sau cùng Ða-ni-ên vào chầu ta.  Người này cũng có tên là Bên-tê-sác-xa, theo danh thần của ta; trong người ấy có Thần của Ðức Chúa Trời Thánh.  Ta thuật lại cho người ấy điềm chiêm bao của ta như sau:
                9 “Hỡi Bên-tê-sác-xa, thủ lãnh của các pháp sư.  Ta biết Thần của Ðức Chúa Trời Thánh ở trong ngươi, nên không có huyền bí nào là khó quá cho ngươi.  Hãy nói cho ta khải tượng trong giấc chiêm bao của ta và hãy giải thích ý nghĩa nó.
                10 Ðây là những hình ảnh hiện ra trong đầu ta khi ta đang nằm trên giường: Ta đang nhìn, và kìa, có một cây ở giữa mặt đất; cây ấy cao lớn lạ thường.  11 Cây ấy cứ tiếp tục lớn mạnh, và ngọn cây cao đến tận trời.  Nó cao to đến nỗi người ta ở những nơi tận cùng trái đất có thể trông thấy nó.  12 Lá nó tươi đẹp, và trái nó rất nhiều.  Nó cung cấp thức ăn cho mọi loài.  Các thú đồng trú ngụ dưới bóng mát nó.  Các chim trời sống giữa các cành nó.  Mọi loài xác thịt nhờ nó mà được no nê.
                13 Ta nằm trên giường và đã thấy các khải tượng đó trong đầu, và kìa, một vị thần canh giữ xuất hiện, tức một đấng thánh từ trời xuống.  14 Vị ấy kêu lớn tiếng và nói, ‘Hãy đốn cây ấy xuống và chặt trụi các cành nó đi.  Hãy tuốt sạch các lá nó và quăng hết các trái nó.  Hãy để các thú đồng chạy trốn khỏi bóng mát nó, và các chim trời lìa xa các cành nó.  15 Tuy nhiên hãy chừa gốc nó và các rễ nó lại trong lòng đất; nhưng hãy dùng xích sắt và niền đồng xiềng nó lại giữa cỏ non trong đồng.  Hãy để nó bị đẫm ướt sương trời, và hãy để nó sống với các thú vật giữa cây cỏ ngoài đồng.  16 Hãy để tâm trí của nó bị biến đổi từ tâm trí của loài người ra tâm trí của một con thú, và hãy để nó phải trải qua bảy kỳ như vậy.  17 Án lệnh đó được các vị thần canh giữ thi hành, theo lệnh mà các đấng thánh đã nhận, để mọi người đang sống nhận biết rằng Ðấng Tối Cao đang trị vì trên thế giới loài người.  Ngài ban quyền cai trị cho ai tùy ý Ngài muốn, ngay cả lập một người hèn mọn nhất lên cầm đầu cũng được.’
                18 Ðó là điềm chiêm bao mà ta, Vua Nê-bu-cát-nê-xa, đã thấy.  Bây giờ, ngươi, hỡi Bên-tê-sác-xa, hãy giải thích ý nghĩa nó cho ta, vì tất cả các nhà thông thái trong vương quốc ta đã không thể giải thích ý nghĩa nó cho ta được, nhưng ngươi thì có thể, vì Thần của Ðức Chúa Trời Thánh ở trong ngươi.”

                """],
            ["Ða-ni-ên Giải Nghĩa Ðiềm Chiêm Bao Thứ Hai": """
                19 Bấy giờ Ða-ni-ên, cũng có tên là Bên-tê-sác-xa, lặng người đi một lúc.  Do đó vua lên tiếng và nói, “Hỡi Bên-tê-sác-xa, chớ để điềm chiêm bao hay ý nghĩa của nó làm cho ngươi bối rối.”
                Bên-tê-sác-xa đáp, “Tâu chúa thượng, nguyện điềm chiêm bao ấy dành cho những kẻ ghét chúa thượng và ý nghĩa nó dành cho những kẻ thù của chúa thượng!
                20 Cái cây mà chúa thượng đã thấy là một cây trở nên lớn và mạnh, ngọn cây đụng đến trời xanh, khắp đất đều có thể trông thấy nó, 21 lá nó xanh tươi tốt đẹp, trái nó sinh ra rất nhiều và được dùng làm thức ăn cho mọi loài, bóng mát nó làm chỗ ở cho thú đồng, và các chim trời làm tổ giữa các cành nó; 22 tâu hoàng thượng, hoàng thượng chính là cây đó.  Hoàng thượng đã trở nên vĩ đại và hùng cường.  Sự vĩ đại của hoàng thượng đã lẫy lừng và cao ngất trời xanh.  Quyền trị vì của hoàng thượng đã lan rộng đến những nơi tận cùng trái đất.
                23 Sau đó hoàng thượng thấy một vị thần canh giữ từ trời xuống và nói, ‘Hãy đốn cây ấy xuống và tiêu diệt nó đi, nhưng hãy chừa gốc nó và các rễ nó lại trong lòng đất, rồi hãy dùng xích sắt và niền đồng xiềng nó lại ở giữa cỏ non trong đồng, hãy để nó bị đẫm ướt sương trời, hãy để nó sống với các thú vật giữa cây cỏ ngoài đồng, và hãy để nó phải trải qua bảy kỳ như vậy.’
                24 Tâu hoàng thượng, đây là ý nghĩa của những điều đó: Ðấng Tối Cao đã ban lịnh phải áp dụng những biện pháp sau đây đối với hoàng thượng, chúa thượng của hạ thần:
                25 Hoàng thượng sẽ bị đuổi ra khỏi xã hội của loài người, và hoàng thượng sẽ sống giữa các thú đồng.  Hoàng thượng sẽ bị bắt phải ăn cỏ như bò, và hoàng thượng sẽ bị đẫm ướt sương trời.  Bảy kỳ sẽ trải qua trên hoàng thượng như vậy cho đến khi hoàng thượng thấu hiểu được rằng Ðấng Tối Cao cầm quyền tể trị trên vương quốc loài người, và Ngài ban cho ai tùy ý Ngài muốn.  26 Còn như lịnh đã truyền phải chừa gốc nó và các rễ nó lại có nghĩa là khi nào hoàng thượng thấu hiểu được rằng Trời đang cầm quyền tể trị, bấy giờ vương quốc của hoàng thượng sẽ được tái lập cho hoàng thượng.
                27 Vì vậy tâu hoàng thượng, nguyện lời khuyên của hạ thần sẽ được hoàng thượng chấp nhận: Xin hoàng thượng sớm chuộc các tội lỗi mình bằng những việc ngay lành đạo đức và chuộc những tội ác của mình bằng lòng thương xót đối với những người bị áp bức oan khiên, may ra thời kỳ bình an thịnh vượng của hoàng thượng sẽ kéo dài ra.”

                """],
            ["Ðiềm Chiêm Bao Ðược Ứng Nghiệm": """
                28 Tất cả các điều ấy đều ứng nghiệm trên Vua Nê-bu-cát-nê-xa.  29 Cuối mười hai tháng sau, khi ông đang đi dạo trên sân thượng của hoàng cung tại Ba-by-lôn, 30 ông vọt miệng nói, “Ðây chẳng phải là Ba-by-lôn huy hoàng tráng lệ mà ta đã dùng quyền lực vô song của ta dựng lên để làm kinh đô và để làm cho ta được uy nghi vinh hiển sao?”
                31 Trong khi những lời ấy còn ở nơi miệng vua, có tiếng từ trời phán xuống rằng, “Hỡi Vua Nê-bu-cát-nê-xa, đây là lịnh phải thi hành đối với ngươi: Vương quyền đã lìa khỏi ngươi.  32 Ngươi sẽ bị đuổi khỏi xã hội loài người; ngươi sẽ sống giữa các thú đồng; ngươi sẽ bị bắt phải ăn cỏ như bò.  Bảy kỳ sẽ trải qua trên ngươi, cho đến khi ngươi thấu hiểu được rằng Ðấng Tối Cao đang cầm quyền tể trị trên vương quốc loài người, và Ngài ban cho ai tùy ý Ngài muốn.”
                33 Ngay lúc đó án lịnh được ứng nghiệm trên Nê-bu-cát-nê-xa.  Ông bị đuổi ra khỏi xã hội loài người.  Ông ăn cỏ như bò.  Thân thể ông bị đẫm ướt sương trời cho đến khi tóc ông mọc dài ra như lông phượng hoàng, và các móng của ông trở thành như các móng chim.

                """],
            ["Nê-bu-cát-nê-xa Ca Ngợi Ðức Chúa Trời": """
                34 “Khi thời kỳ ấy đã mãn, ta, Nê-bu-cát-nê-xa, ngước mắt lên trời, trí tuệ của ta phục hồi trong ta.  Ta chúc tụng Ðấng Tối Cao.  Ta ca ngợi và tôn vinh Ðấng sống đời đời; vì quyền tể trị của Ngài là quyền tể trị đời đời, vương quốc Ngài tồn tại từ đời nọ đến đời kia.  35 Mọi dân trên đất đều chẳng có quyền gì đối với Ngài.  Ngài làm bất cứ điều gì Ngài muốn giữa các cơ binh trên trời và giữa các dân trên đất.  Không ai có thể nắm giữ tay Ngài lại hoặc dám hỏi Ngài, “Ngài đang làm gì vậy?”
                36 Lúc đó trí tuệ ta đã phục hồi trong ta, sự uy nghi và huy hoàng của ta được trả lại cho ta, vì vinh hiển của vương quốc ta.  Các mưu sĩ của ta và các đại thần của ta tìm đến ta.  Ta được tái lập địa vị cầm quyền trên vương quốc ta, và quyền thế ta càng lớn hơn khi trước.  37 Bây giờ ta, Nê-bu-cát-nê-xa, ca ngợi, tán dương, và tôn vinh Vua trên trời, vì mọi công việc của Ngài đều chân thật, các đường lối của Ngài đều công chính, và Ngài có thể hạ bệ những kẻ nào hống hách kiêu căng.”

                """]
            ]),
        Chapter(5, passages: [
            ["Ðại Tiệc của Vua Bên-sác-xa": """
                1 Vua Bên-sác-xa đãi một đại tiệc cho một ngàn đại thần của ông và uống rượu với một ngàn đại thần ấy.  2 Ðang khi Bên-sác-xa uống rượu và cao hứng, ông truyền lịnh lấy các khí dụng bằng vàng và bằng bạc mà tổ phụ ông, Nê-bu-cát-nê-xa, đã lấy trong Ðền Thờ ở Giê-ru-sa-lem đem đến để vua, các đại thần của ông, các vợ của ông, và các cung phi của ông dùng uống rượu.  3 Vậy người ta đem các khí dụng bằng vàng đã lấy trong Ðền Thờ, nhà của Ðức Chúa Trời ở Giê-ru-sa-lem, đến để vua, các đại thần của ông, các vợ của ông, và các cung phi của ông dùng uống rượu.  4 Trong khi uống rượu, họ ca tụng các thần của họ, đó là các thần tượng làm bằng vàng, bạc, đồng, sắt, gỗ, và đá.

                """],
            ["Bàn Tay Viết Trên Tường": """
                5 Ngay chính giờ đó những ngón tay của một bàn tay người xuất hiện, và bàn tay ấy viết chữ trên tường vôi của hoàng cung, đối ngang cột đèn.  Nhà vua trông thấy bàn tay ấy khi bàn tay ấy viết.  6 Bấy giờ mặt vua tái mét, tâm trí ông kinh hoàng, hai chân ông bủn rủn, và hai gối ông run cầm cập.  7 Vua lớn tiếng truyền lịnh đem ngay các bốc sư, các chiêm tinh gia, và các thầy bói đến.
                Vua nói với các nhà thông thái của Ba-by-lôn, “Người nào đọc được những chữ này và giải thích ý nghĩa của chúng cho ta sẽ được mặc áo choàng màu tía, được đeo vòng vàng vào cổ, và sẽ đứng hàng thứ ba trong việc triều chính của vương quốc.”
                8 Tất cả các nhà thông thái đều vào triều kiến, nhưng không ai có thể đọc được những chữ đó và không thể giải thích được ý nghĩa của chúng.  9 Bấy giờ Vua Bên-sác-xa càng thêm sợ hãi; mặt ông tái xanh, và các đại thần của ông đều bối rối.
                10 Khi hoàng hậu nghe những lời của vua và các đại thần, bà đi vào phòng tiệc.  Hoàng hậu cất tiếng nói, “Hoàng thượng vạn tuế!  Xin hoàng thượng đừng để những lo nghĩ làm hoàng thượng bất an, và xin hoàng thượng đừng sợ hãi mà biến sắc.  11 Trong vương quốc của hoàng thượng có một người được Thần của Ðức Chúa Trời Thánh ở cùng.  Trong thời tổ phụ của hoàng thượng, người ấy là một người sáng suốt, thông minh, và khôn ngoan; có thể nói người ấy khôn ngoan như các thần.  Vì thế Vua Nê-bu-cát-nê-xa tổ phụ hoàng thượng đã lập người ấy làm đầu các pháp sư, các bốc sư, các chiêm tinh gia, và các phù thủy.  Quả thật tiên vương của hoàng thượng đã làm điều ấy.  12 Người ta đã tìm thấy nơi người ấy một thần trí phi phàm, trí thức, thông minh, khả năng giải mộng, giải đáp những điều huyền bí, tháo gỡ các vấn đề rắc rối khó khăn; người đó chính là Ða-ni-ên mà tiên vương đã đặt tên là Bên-tê-sác-xa.  Bây giờ xin hoàng thượng cho triệu Ða-ni-ên vào để ông ấy giải nghĩa những chữ ấy cho hoàng thượng.”

                """],
            ["Ý Nghĩa Những Chữ Trên Tường": """
                13 Vậy người ta đem Ða-ni-ên đến ra mắt vua.  Vua phán hỏi Ða-ni-ên, “Ngươi có phải là Ða-ni-ên, một trong những kẻ bị lưu đày từ Giu-đa mà tiên vương ta đã mang từ Giu-đa về không?  14 Ta có nghe rằng ngươi được Thần của Ðức Chúa Trời ở cùng, và ngươi là người sáng suốt, thông minh, và khôn ngoan xuất chúng.  15 Các nhà thông thái và các bốc sư đã được đem đến đây để đọc và giải nghĩa những chữ này cho ta, nhưng họ không giải nghĩa được.  16 Ta nghe nói rằng ngươi có thể giải nghĩa những điều huyền bí và tháo gỡ các vấn đề rắc rối khó khăn.  Bây giờ nếu ngươi có thể đọc được những chữ này và giải thích ý nghĩa những chữ ấy cho ta, ngươi sẽ được mặc áo choàng màu tía, được đeo vòng vàng vào cổ, và sẽ đứng hàng thứ ba trong việc triều chính của vương quốc.”
                17 Bấy giờ Ða-ni-ên trả lời trước mặt vua, “Xin hoàng thượng giữ các món quà ấy lại cho mình, và xin ban các phần thưởng ấy cho người khác.  Dầu vậy hạ thần sẽ đọc những chữ ấy cho hoàng thượng và giải thích ý nghĩa của chúng cho hoàng thượng.  18 Tâu hoàng thượng: Ðức Chúa Trời Tối Cao đã ban cho Nê-bu-cát-nê-xa tổ phụ của hoàng thượng vương quốc, quyền bính, vinh hiển, và tôn trọng.  19 Vì quyền lực lớn lao Ngài đã ban cho người nên mọi dân, các nước, và các ngữ tộc đều run rẩy và sợ hãi trước mặt người.  Người muốn ai chết, kẻ ấy phải chết; người muốn để ai sống, kẻ ấy được sống; người muốn cho ai thăng chức, kẻ ấy được thăng chức; người muốn cất chức ai, kẻ ấy bị cất chức.  20 Nhưng khi lòng người trở nên tự cao tự đại, và trí người trở nên cứng cỏi vì kiêu căng, người đã bị truất khỏi ngôi vua và bị tước hết vinh hiển.  21 Người đã bị đuổi khỏi xã hội loài người; lòng dạ người đã bị biến ra lòng dạ của loài thú; người đã phải sống chung lộn với các lừa hoang.  Người ta đã cho người ăn cỏ như bò; thân thể người phải đẫm ướt sương trời cho đến khi người nhận biết rằng Ðức Chúa Trời Tối Cao cầm quyền tể trị trên các vương quốc loài người, và Ngài lập ai lên cầm quyền tùy ý Ngài muốn.  22 Nhưng hoàng thượng, Bên-sác-xa, con cháu của người, dù rằng hoàng thượng đã biết rõ mọi điều ấy, hoàng thượng vẫn không hạ mình.  23 Ngược lại hoàng thượng đã lên mình kiêu ngạo và dám chống cả Chúa trên trời.  Hoàng thượng đã cho đem các ly chén trong nhà của Ðức Chúa Trời đến trước mặt hoàng thượng để hoàng thượng, các đại thần của hoàng thượng, các vợ của hoàng thượng, và các cung phi của hoàng thượng dùng uống rượu.  Hoàng thượng ca ngợi các thần tượng làm bằng bạc và vàng, đồng và sắt, gỗ và đá, là các thần tượng không thấy, không nghe, và không biết; còn Ðức Chúa Trời, Ðấng nắm trong tay hơi thở của hoàng thượng và mọi đường lối của hoàng thượng, hoàng thượng lại không tôn vinh Ngài.  24 Vì thế Ngài đã sai bàn tay ấy viết ra những chữ này.  25 Ðây là những chữ đã được viết, ‘Mê-nê, Mê-nê, Tê-kên, Pạc-sin.’  26 Ðây là ý nghĩa những chữ ấy: ‘Mê-nê’ nghĩa là ‘bị đếm.’ Ðức Chúa Trời đã đếm các ngày của triều đại hoàng thượng và quyết định nó phải chấm dứt.  27 ‘Tê-kên’ nghĩa là ‘cân.’  Hoàng thượng được đem đặt trên một cái cân để cân và phía bên hoàng thượng bị thiếu.  28 ‘Pạc-sin’ nghĩa là ‘bị chia ra.’  Vương quốc của hoàng thượng sẽ bị chia ra và được ban cho người Mê-đi và người Ba-tư.”
                29 Bấy giờ Bên-sác-xa truyền lịnh cho người ta mặc áo choàng màu tía cho ông, đeo vòng vàng vào cổ ông, và rao báo cho mọi người biết rằng ông đứng hàng thứ ba trong việc triều chính của vương quốc.  30 Chính trong đêm đó, Bên-sác-xa vua Ba-by-lôn bị giết.  31 Ða-ri-út người Mê-đi lên ngôi thế vị lúc sáu mươi hai tuổi.

                """]
            ]),
        Chapter(6, passages: [
            ["Âm Mưu Hại Ða-ni-ên": """
                1 Ða-ri-út lấy làm hài lòng bổ nhiệm một trăm hai mươi thống đốc cai trị trên cả vương quốc của ông.  2 Các thống đốc ấy ở dưới quyền của ba quan đại thần, và Ða-ni-ên là một trong ba vị đó.  Các thống đốc phải chịu trách nhiệm với ba quan đại thần đó để vua không bị thiệt hại gì.  3 Lúc ấy Ða-ni-ên nổi bật hơn hai vị đại thần kia và các vị thống đốc, vì thần trí phi phàm ở trong ông; do đó vua có ý muốn lập ông làm tể tướng để trị vì trên cả vương quốc.  4 Vì thế các đại thần và các thống đốc tìm mọi cớ để bắt lỗi Ða-ni-ên về công việc triều chính, nhưng họ chẳng tìm được một lý cớ nào, vì ông là một người trung thành, không tham nhũng, và không có lỗi lầm gì.  5 Cuối cùng những người ấy nói với nhau, “Chúng ta không thể tìm ra lỗi lầm nào của ông Ða-ni-ên này hầu tố cáo ông ấy cả, trừ phi chúng ta đi tìm những sơ hở của ông ấy trong việc giữ luật Ðức Chúa Trời của ông ấy.”
                6 Vậy các quan đại thần và các thống đốc hẹn nhau cùng đến ra mắt vua, và họ tâu với vua, “Tâu Vua Ða-ri-út!  Kính chúc hoàng thượng sống vạn tuế!  7 Tất cả các đại thần, các triều thần, các thống đốc, các mưu sĩ, và các tổng trấn đã đồng ý xin hoàng thượng ban hành một sắc lịnh và lập nó thành một sắc luật bất di bất dịch rằng: Trong vòng ba mươi ngày, hễ ai cầu nguyện với bất cứ thần nào hoặc người nào khác hơn hoàng thượng, tâu hoàng thượng, kẻ ấy sẽ bị quăng vào hang sư tử.  8 Tâu hoàng thượng, bây giờ xin hoàng thượng lập nó thành một sắc luật và ký tên vào văn bản, để nó không bị thay đổi theo như luật của người Mê-đi và người Ba-tư, và nó không bị thu hồi.”  9 Thế là Vua Ða-ri-út ký tên vào văn bản của sắc luật ấy.

                """],
            ["Ða-ni-ên Bị Quăng Vào Hang Sư Tử": """
                10 Lúc đó sau khi Ða-ni-ên biết văn bản của sắc luật đã được vua ký, ông về nhà, lên phòng trên lầu, nơi có các cửa sổ mở hướng về Giê-ru-sa-lem, mỗi ngày ba lần, ông quỳ xuống, cầu nguyện, và ca ngợi Ðức Chúa Trời của ông, như ông vẫn thường làm từ trước đến giờ.  11 Bấy giờ những người ấy kéo nhau đến nhà ông.  Họ thấy Ða-ni-ên đang cầu nguyện và kêu xin trước mặt Ðức Chúa Trời của ông.  12 Thế là họ vào chầu vua và tâu với vua về sắc luật vua đã ban hành, “Tâu hoàng thượng, chẳng phải hoàng thượng đã ban hành một sắc luật rằng trong vòng ba mươi ngày không ai được cầu nguyện với bất cứ thần nào hoặc người nào khác hơn hoàng thượng, bằng không, kẻ ấy sẽ bị quăng vào hang sư tử sao?”
                Vua đáp, “Sắc luật ấy đã ban hành, và theo luật của người Mê-đi và người Ba-tư, sắc luật ấy không thể bị thu hồi.”
                13 Bấy giờ họ tâu với vua, “Ða-ni-ên, một trong những kẻ bị lưu đày của dân Giu-đa, đã chẳng coi hoàng thượng ra gì, tâu hoàng thượng.  Ông ấy cũng chẳng coi sắc lịnh của hoàng thượng đã ký ra gì, vì ngày nào ông ấy cũng cầu nguyện ba lần.”
                14 Khi vua nghe những lời ấy, ông rất đau buồn, và ông vận dụng tâm trí để tìm cách cứu Ða-ni-ên.  Ông vật vã suy nghĩ mãi cho đến khi mặt trời lặn để tìm cách cứu Ða-ni-ên.  15 Bấy giờ những người đó họp lại với nhau và đến nói với vua, “Tâu hoàng thượng, chắc hẳn hoàng thượng biết rằng theo luật của người Mê-đi và người Ba-tư, mỗi khi sắc lịnh hay sắc luật đã được nhà vua ban hành thì nó không thể thay đổi được.”
                16 Vậy vua ban lịnh.  Họ liền đem Ða-ni-ên và quăng ông vào hang sư tử.  Vua cất tiếng và nói với Ða-ni-ên, “Cầu xin Ðức Chúa Trời, Ðấng ngươi hằng thờ phượng, giải cứu ngươi.”  17 Sau đó người ta mang một tảng đá lớn đến chận miệng hang.  Vua đóng ấn tín của ông trên đó, và các đại thần cũng đóng ấn dấu của họ trên đó, để xác nhận rằng vụ Ða-ni-ên không còn gì thay đổi nữa.  18 Sau đó vua trở về cung điện mình.  Tối hôm đó ông không thiết ăn uống gì cả, ông cũng không muốn đem ban nhạc đến giải khuây, và suốt đêm đó ông không ngủ được.

                """],
            ["Ða-ni-ên Ðược Cứu Khỏi Hang Sư Tử": """
                19 Sáng hôm sau vua thức dậy thật sớm và vội vàng đi đến hang sư tử.  20 Khi đến gần hang, ông cất tiếng gọi Ða-ni-ên với giọng rất bi thương.  Vua cất tiếng và nói với Ða-ni-ên, “Hỡi Ða-ni-ên tôi tớ của Ðức Chúa Trời hằng sống, Ðức Chúa Trời, Ðấng ngươi hằng thờ phượng, có thể giải cứu ngươi khỏi các sư tử chăng?”
                21 Bấy giờ Ða-ni-ên trả lời với vua, “Tâu hoàng thượng, kính chúc hoàng thượng sống vạn tuế!  22 Ðức Chúa Trời của hạ thần đã sai thiên sứ của Ngài bịt mồm các sư tử; vì thế chúng không làm gì hại đến hạ thần, vì Ngài thấy hạ thần vô tội trước mặt Ngài, và hạ thần cũng chẳng làm điều gì sai trước mặt hoàng thượng, tâu hoàng thượng.”
                23 Bấy giờ vua rất đỗi vui mừng và truyền lịnh đem Ða-ni-ên lên khỏi hang.  Vậy Ða-ni-ên được đem lên khỏi hang sư tử.  Người ta thấy ông không bị hại một chút gì, vì ông đã tin cậy Ðức Chúa Trời của ông.  24 Kế đó vua truyền lịnh đem những kẻ đã tố cáo Ða-ni-ên đến.  Người ta quăng chúng cùng với vợ con chúng vào hang sư tử.  Trước khi chúng rơi tới đáy hang, các sư tử đã nhảy lên vồ lấy chúng và xé thây chúng ra từng mảnh.
                25 Sau đó Vua Ða-ri-út viết, “Gởi đến các dân, các nước, và các ngữ tộc sống trên khắp đất.  Cầu mong các ngươi được bình an thịnh vượng bội phần.  26 Ta ban hành chiếu chỉ này để truyền cho mọi người trong vương quốc phải run rẩy và kính sợ trước mặt Ðức Chúa Trời của Ða-ni-ên, vì Ngài là Ðức Chúa Trời hằng sống và tồn tại đời đời.  Vương quốc Ngài sẽ không bao giờ bị diệt mất, và quyền bính Ngài sẽ không bao giờ tận cùng.  27 Ngài giải thoát và giải cứu.  Ngài làm các dấu kỳ và các phép lạ trên trời và dưới đất.  Ngài đã giải thoát Ða-ni-ên khỏi các nanh vuốt của sư tử.”
                28 Vậy Ða-ni-ên được thịnh vượng trong triều đại của Ða-ri-út và trong triều đại của Sy-ru người Ba-tư.

                """]
            ]),
        Chapter(7, passages: [
            ["Khải Tượng về Bốn Sinh Vật": """
                1 Trong năm thứ nhất của triều đại Bên-sác-xa vua Ba-by-lôn, Ða-ni-ên nằm trên giường và thấy chiêm bao.  Ông thấy các khải tượng trong đầu ông.  Ông ghi lại tất cả những gì ông đã thấy trong giấc chiêm bao ấy và nói, 2 “Tôi, Ða-ni-ên, xin thuật lại như sau: Ban đêm, trong một khải tượng, tôi thấy, kìa, bốn hướng gió trên trời đang vần vũ dữ dội trên mặt đại dương.  3 Từ dưới biển có bốn con thú đi lên; mỗi con đều khác với các con khác.
                4 Con thứ nhất giống như sư tử và có cánh như đại bàng.  Khi tôi đang mải mê nhìn tôi thấy đôi cánh nó bị nhổ đi, rồi nó được nhấc lên khỏi mặt đất và bắt phải đứng trên hai chân như người ta, và nó được ban cho tâm trí của một người.
                5 Này, một con thú khác xuất hiện, con thú thứ nhì, giống như một con gấu.  Nó đứng trườn lên một bên; trong miệng nó, giữa hai hàm răng, nhô ra ba xương sườn, và nó được bảo, “Hãy đứng dậy và ăn nuốt nhiều thịt.”
                6 Kế đó tôi nhìn, và kìa, một con thú nữa xuất hiện, giống như con beo.  Trên lưng nó có bốn cánh như cánh chim. Con thú ấy có bốn đầu, và nó được ban cho quyền cai trị.
                7 Sau đó, ban đêm tôi thấy trong khải tượng, và kìa, con thú thứ tư.  Nó trông thật đáng sợ, kinh khủng, và rất mạnh.  Nó có các răng lớn bằng sắt.  Nó cắn xé, nghiền nát, và chà đạp dưới chân những gì còn sót lại.  Nó khác hẳn tất cả con thú trước nó; nó có mười sừng.  8 Ðang khi tôi nhìn các sừng của nó, kìa, một sừng khác, một sừng nhỏ, mọc lên giữa các sừng ấy; và trước nó thì ba sừng có trước nó lại bị nhổ tận gốc; và kìa, sừng ấy có các mắt như mắt của người ta, và có miệng nói những lời cao ngạo trịch thượng.

                """],
            ["Ðấng Thái Cổ Phán Xét": """
                9 Khi tôi đang nhìn tôi thấy các ngai được đặt vào chỗ;
                Ðấng Thái Cổ ngồi vào ngai Ngài.
                Y phục Ngài trắng như tuyết;
                Tóc trên đầu Ngài tựa lông chiên tinh khiết;
                Chiếc ngai Ngài rực cháy với lửa hừng;
                Các bánh xe của ngai thảy đều rực lửa.
                10 Từ thánh nhan Ngài lửa cuồn cuộn phát ra.
                Ngàn ngàn hầu hạ Ngài,
                Vạn vạn túc trực trước mặt Ngài.
                Phiên tòa bắt đầu xử,
                Và các sách được mở ra.
                11 Bấy giờ tôi tiếp tục nhìn vì tiếng của những lời cao ngạo trịch thượng từ cái sừng ấy vang ra.  Tôi cứ nhìn cho đến khi con thú ấy bị giết; thân xác nó bị tiêu hủy và bị thiêu trong lửa.  12 Các con thú còn lại đều bị tước hết quyền cai trị; tuy nhiên chúng được cho sống thêm một mùa và một kỳ.
                13 Ban đêm tôi thấy trong các khải tượng,
                Kìa, một Ðấng giống như Con Người ngự trên mây trời đến.
                Ngài đến trước mặt Ðấng Thái Cổ,
                Và được đưa ra trình diện trước Ðấng ấy.
                14 Ngài được ban cho quyền trị vì, vinh hiển, và vương quyền,
                Ðể mọi dân tộc, mọi quốc gia, và mọi ngữ tộc phải phục vụ Ngài.
                Quyền trị vì của Ngài là quyền trị vì đời đời, không bao giờ dứt;
                Vương quyền của Ngài không bao giờ bị hủy diệt.

                """],
            ["Khải Tượng Ðược Giải Nghĩa": """
                15 Về phần tôi, Ða-ni-ên, tâm trí trong tôi bối rối, và những khải tượng trong đầu làm tôi hoang mang.  16 Tôi tiến gần một trong những vị đang đứng đó và hỏi vị ấy sự thật về mọi điều ấy là gì.  Vị ấy trả lời và giải thích cho tôi biết những điều ấy như sau:
                17 “Bốn con thú to lớn chỉ về bốn vua sẽ trỗi lên trên đất.  18 Nhưng các thánh đồ của Ðấng Tối Cao sẽ nhận lấy vương quốc và chiếm hữu vương quốc đời đời, vô cùng, và vĩnh viễn.”
                19 Bấy giờ tôi muốn biết sự thật về con thú thứ tư, con thú khác hơn tất cả con thú khác, một con thú cực kỳ đáng sợ; các răng nó bằng sắt, và các móng vuốt nó bằng đồng.  Nó cắn xé, nghiền nát, và chà đạp dưới chân những gì còn sót lại.  20 Tôi cũng muốn biết về mười cái sừng trên đầu nó, và về cái sừng kia mọc lên sau, mà trước nó ba sừng khác phải rụng đi.  Cái sừng đó có các mắt và miệng nói những lời cao ngạo trịch thượng.  Ngoài ra nó trông có vẻ lớn hơn các sừng khác.  21 Trong khi tôi đang nhìn, cái sừng ấy giao chiến với các thánh đồ và thắng hơn họ 22 cho đến khi Ðấng Thái Cổ đến, và cuộc phán xét ban sự đắc thắng cho các thánh đồ của Ðấng Tối Cao; và thời điểm đã đến cho các thánh đồ chiếm hữu vương quốc.  23 Vị ấy nói thế này:
                “Về con thú thứ tư,
                Sẽ có một đế quốc thứ tư trên đất;
                Ðế quốc ấy sẽ khác hơn tất cả đế quốc khác;
                Nó sẽ ăn nuốt cả thế giới;
                Nó sẽ giày đạp và nghiền nát thế giới dưới chân nó.
                24 Còn về mười cái sừng,
                Từ đế quốc ấy mười vua sẽ nổi lên;
                Nhưng sẽ có một vua khác nổi lên sau mười vua đó;
                Vua mới nổi lên ấy khác hơn các vua trước;
                Vua mới ấy sẽ đè bẹp ba vua.
                25 Vua ấy sẽ nói những lời chống lại Ðấng Tối Cao;
                Vua ấy sẽ làm hại các thánh đồ của Ðấng Tối Cao;
                Vua ấy sẽ cố thay đổi thì giờ và luật pháp.
                Người ta sẽ trao quyền cho vua ấy một kỳ, các kỳ, và nửa kỳ.
                26 Sau đó tòa phán xét sẽ ngồi lại xét xử;
                Quyền bính của vua ấy bị tước đoạt, giải thể, và tiêu diệt hoàn toàn.
                27 Bấy giờ vương quốc, quyền bính, và sự vĩ đại của các vương quốc dưới trời sẽ được ban cho dân thánh, tức các thánh đồ của Ðấng Tối Cao;
                Vương quốc Ngài sẽ là vương quốc đời đời;
                Và mọi quyền bính sẽ phục vụ Ngài và vâng lời Ngài.”
                28 Những lời giải nghĩa về các khải tượng đến đây là chấm dứt.  Nhưng về phần tôi, Ða-ni-ên, những tư tưởng trong tôi làm tôi quá đỗi sợ hãi, đến nỗi mặt tôi biến sắc, nhưng tôi giữ kín việc ấy trong lòng.

                """]
            ]),
        Chapter(8, passages: [
            ["Khải Tượng về Chiên Ðực và Dê Ðực": """
                1 Trong năm thứ ba của triều đại Vua Bên-sác-xa, một khải tượng đã hiện ra cho tôi, Ða-ni-ên, sau khi khải tượng kia đã hiện ra cho tôi lần trước.  2 Trong khi tôi đang nhìn khải tượng, bổng nhiên tôi thấy tôi đang ở Kinh Thành Su-sa, trong Tỉnh Ê-lam.  Tôi cũng thấy trong khải tượng rằng tôi đang ở bên bờ Sông U-lai.
                3 Tôi ngước mắt lên nhìn và thấy, kìa, một con chiên đực có hai sừng đang đứng cạnh bờ sông.  Cả hai sừng đều dài, nhưng một sừng dài hơn sừng kia, và sừng dài hơn lại mọc lên sau sừng kia.  4 Tôi thấy con chiên đực ấy xông về hướng tây, hướng bắc, và hướng nam.  Không thú vật nào có thể chống cự nó nổi, và cũng không con vật nào có thể thoát khỏi sức mạnh của nó.  Nó muốn làm gì thì làm, và nó trở nên lớn mạnh.
                5 Ðang khi tôi suy nghĩ về việc ấy, kìa, một con dê đực từ hướng tây vụt đến.  Nó phóng nhanh trên khắp mặt đất, nhanh đến nỗi như chân không chấm đất.  Con dê đực ấy có một sừng nổi bật ở giữa hai mắt.  6 Con dê đực ấy nhắm vào con chiên đực có hai sừng đang đứng bên bờ sông mà phóng tới với tất cả cơn giận của nó.  7 Tôi thấy nó hung hăng xông vào con chiên đực.  Nó tấn công con chiên đực và húc gãy cả hai sừng của con chiên đực.  Con chiên đực không đủ sức chống cự nó.  Nó húc con chiên đực ngã nhào xuống đất và giày đạp con chiên đực dưới chân.  Không ai có thể cứu con chiên đực thoát khỏi sức mạnh của nó.  8 Con dê đực trở nên rất mạnh mẽ.  Nhưng đang khi nó ở đỉnh cao của quyền lực, cái sừng to lớn của nó đột nhiên bị gãy.  Nơi cái sừng bị gãy, bốn cái sừng khác mọc lên quay về bốn hướng gió trên trời.  9 Trong bốn cái sừng ấy, một cái sừng nhỏ lớn lên rất nhanh về hướng nam, hướng đông, và hướng của miền Ðất Vinh Hiển.  10 Nó lớn mãi cho đến khi nó đụng đến đạo binh thiên thượng.  Nó quăng một số trong đạo binh thiên thượng và một số trong các tinh tú xuống đất, và nó giày đạp họ.  11 Nó tự tôn tự đại đối với Ðấng Thủ Lãnh của đạo binh thiên thượng, qua việc dẹp bỏ sự dâng tế lễ hằng ngày lên Ngài và lật đổ nơi thánh của Ngài.  12 Sự bội nghịch ấy có vẻ như thành công vì đạo binh thiên thượng bị kiềm hãm, nhờ thế nó có thể dẹp bỏ sự dâng tế lễ hằng ngày, đạp đổ chân lý xuống đất, và làm gì cũng thành đạt.
                13 Bấy giờ tôi nghe một vị thánh lên tiếng, và tôi lại nghe một vị thánh khác nói với vị thánh ấy, “Cho đến bao giờ những gì trông thấy trong khải tượng ấy, tức sự bội nghịch khiến cho sự dâng tế lễ hằng ngày bị bỏ phế và nơi thánh cùng đạo binh thiên thượng bị giày đạp dưới chân, mới chấm dứt?”
                14 Vị ấy nói với tôi, “Nó sẽ kéo dài đến hai ngàn ba trăm buổi chiều và buổi sáng; sau đó nơi thánh sẽ được thanh tẩy.”

                """],
            ["Gáp-ri-ên Giải Thích Khải Tượng": """
                15 Ðang khi tôi, Ða-ni-ên, thấy khải tượng và suy nghĩ để hiểu ý nghĩa của khải tượng ấy, thình lình có ai như một người đàn ông xuất hiện và đứng trước mặt tôi.  16 Tôi nghe tiếng của một người từ giữa hai bờ Sông U-lai kêu lên, “Gáp-ri-ên, hãy nói cho người ấy hiểu ý nghĩa của khải tượng đó.”
                17 Người ấy bèn tiến gần chỗ tôi đang đứng.  Tôi sợ hãi quá đỗi và nằm sấp mặt xuống đất.  Người ấy bảo tôi, “Hỡi con người, ngươi phải hiểu rằng những gì ngươi thấy trong khải tượng đó đều liên quan đến thời kỳ cuối cùng.”  18 Khi người ấy nói với tôi, tôi như người ngất xỉu nằm sấp mặt xuống đất; nhưng người ấy chạm vào tôi và làm cho tôi đứng dậy trên chân tôi.
                19 Người ấy nói, “Này, ta sẽ cho ngươi biết những gì sẽ xảy ra trong thời kỳ của cơn thịnh nộ về sau, vì nó liên quan đến thời kỳ đã định cho sự cuối cùng:  20 Con chiên đực có hai sừng ngươi đã thấy tiêu biểu cho các vua Mê-đi và Ba-tư.  21 Con dê đực có bờm tiêu biểu cho vua Hy-lạp.  Cái sừng to lớn ở giữa hai mắt của nó tiêu biểu cho vua đầu tiên của đế quốc đó.  22 Bốn cái sừng mọc lên ở chỗ nó tiêu biểu cho bốn vương quốc sẽ ra từ đế quốc đó, nhưng không vương quốc nào mạnh bằng đế quốc đó.  23 Ðến gần cuối thời kỳ của các vương quốc đó, khi tội lỗi của họ đã đầy, một vua dữ tợn sẽ dấy lên; đó là một kẻ đầy mưu mô xảo quyệt.  24 Nó sẽ trở nên rất mạnh, nhưng chẳng phải nhờ thực lực của nó.  Nó sẽ tiêu diệt các đối thủ của nó một cách tàn bạo.  Nó sẽ thành công trong mọi việc nó làm.  Nó sẽ tiêu diệt những người dũng mãnh và luôn cả dân thánh.  25 Nhờ xảo quyệt nó làm cho sự dối gạt trở nên thịnh hành dưới quyền của nó.  Trong thâm tâm nó, nó tự cho nó là một kẻ vĩ đại.  Trong khi người ta an hưởng thái bình, nó sẽ bất thần giết hại nhiều người.  Nó cả gan đứng dậy chống lại Chúa của các chúa, nhưng nó sẽ bị đập nát tan tành dù chẳng phải bởi tay của người phàm.  26 Khải tượng về các buổi chiều và các buổi sáng đã báo cho ngươi là thật; nhưng ngươi hãy giữ kín khải tượng đó, vì nó liên quan đến những gì sẽ xảy ra vào những ngày xa lắm trong tương lai.”
                27 Tôi, Ða-ni-ên, bị kiệt lực và bị bịnh luôn mấy ngày.  Sau đó tôi trỗi dậy và lo việc của vua, nhưng tôi cứ bần thần dã dượi mãi sau khi trông thấy khải tượng đó, vì tôi không hiểu thấu được ý nghĩa của nó.

                """]
            ]),
        Chapter(9, passages: [
            ["Ða-ni-ên Cầu Nguyện cho Dân Ông": """
                1 Năm thứ nhất triều đại Ða-ri-út con của A-suê-ru, thuộc chủng tộc Mê-đi, người đã được lập làm vua trị vì cả đế quốc của người Canh-đê, 2 trong năm thứ nhất của triều đại vua ấy, tôi, Ða-ni-ên, nhờ nghiên cứu sách thánh, biết được số năm mà lời CHÚA đã cậy Tiên Tri Giê-rê-mi nói về cảnh đổ nát điêu tàn của Giê-ru-sa-lem là bảy mươi năm sắp mãn.  3 Tôi kiêng ăn, mặc vải thô, và rắc tro trên đầu, rồi hướng mặt về Chúa, Ðức Chúa Trời, mà dâng lời cầu nguyện và nài xin.  4 Tôi đã cầu nguyện và xưng tội với CHÚA, Ðức Chúa Trời của tôi, rằng:
                “Ôi lạy Chúa, Ðức Chúa Trời vĩ đại và đáng kinh, Ðấng giữ giao ước và tỏ lòng thương xót đối với ai yêu kính Ngài và vâng giữ các điều răn Ngài.  5 Chúng con đã phạm tội và có lỗi.  Chúng con đã làm điều gian ác và phản nghịch.  Chúng con đã lìa bỏ những điều răn và luật lệ Ngài.  6 Chúng con đã không nghe lời các vị tiên tri, tức các tôi tớ Ngài, những người đã nhân danh Ngài mà nói với các vua, các quan, các bậc tiền bối, và toàn dân trong nước.
                7 Lạy Chúa, nguyện lẽ công chính thuộc về Ngài, còn sự hổ mặt thuộc về chúng con như đã thấy ngày nay, tức trên người Giu-đa, dân cư Giê-ru-sa-lem, và mọi người I-sơ-ra-ên, và trên mọi người ở gần hoặc ở xa, trong mọi xứ mà Ngài đã đuổi họ đến, vì họ đã phạm tội bất trung và chống nghịch Ngài.
                8 Lạy CHÚA, nguyện sự hổ mặt đổ trên chúng con, trên các vua chúng con, các quan chúng con, và các bậc tiền bối chúng con, vì chúng con đã phạm tội nghịch lại Ngài.
                9 Nguyện ơn thương xót và ơn tha thứ thuộc về Chúa, Ðức Chúa Trời của chúng con, vì chúng con đã phản nghịch Ngài.  10 Chúng con đã không vâng theo tiếng CHÚA, Ðức Chúa Trời của chúng con, để vâng giữ luật pháp Ngài mà Ngài đã dùng các tôi tớ Ngài, tức các vị tiên tri Ngài, giải bày cho chúng con.
                11 Toàn dân I-sơ-ra-ên đã vi phạm luật pháp Ngài và lìa bỏ luật pháp ấy bằng cách từ chối vâng theo tiếng Ngài.  Vì thế những lời nguyền rủa và thề nguyền ghi trong luật pháp của Môi-se tôi tớ Ðức Chúa Trời đã đổ xuống trên chúng con, vì chúng con đã phạm tội nghịch lại Ngài.  12 Ngài đã thực hiện lời Ngài cảnh cáo chúng con và những người lãnh đạo chúng con, bằng cách giáng xuống Giê-ru-sa-lem một cơn đại họa chưa từng thấy dưới trời.  13 Thật đúng y như đã chép trong luật pháp của Môi-se; tất cả các thảm họa ấy đã đến trên chúng con.  Thế mà chúng con vẫn không chịu tìm cầu ơn thương xót của CHÚA, Ðức Chúa Trời của chúng con, mà lìa bỏ tội lỗi, và tỉnh ngộ nhờ chân lý Ngài.  14 Vì thế CHÚA đã để dành thảm họa ấy và đã giáng nó trên chúng con.  Về việc này, CHÚA, Ðức Chúa Trời của chúng con, hoàn toàn đúng trong mọi việc Ngài làm, vì chúng con đã không vâng theo tiếng Ngài.
                15 Giờ đây, lạy Chúa, Ðức Chúa Trời của chúng con, Ðấng đã đem dân Ngài ra khỏi đất Ai-cập bằng cánh tay quyền năng và đã làm cho danh Ngài được lẫy lừng cho đến ngày nay; chúng con đã phạm tội, chúng con đã làm điều ác.  16 Lạy Chúa, dựa theo mọi điều công chính Ngài đã thực hiện, cầu xin Ngài quay cơn giận và cơn thịnh nộ Ngài khỏi Giê-ru-sa-lem, thành của Ngài, núi thánh của Ngài; bởi vì tội lỗi của chúng con và sự gian ác của tổ tiên chúng con mà Giê-ru-sa-lem và dân Ngài đã trở thành cớ sỉ nhục giữa mọi nước láng giềng của chúng con.
                17 Vậy, giờ đây, lạy Ðức Chúa Trời của chúng con, xin lắng nghe lời cầu nguyện và lời van xin của tôi tớ Ngài.  Lạy Chúa, vì cớ danh Ngài, nguyện thánh nhan Ngài tỏa rạng trên nơi thánh Ngài đang đổ nát.  18 Lạy Ðức Chúa Trời của con, xin nghiêng tai và nghe.  Xin đoái xem và nhìn thấy cảnh tan hoang của chúng con và của thành mang danh Ngài.  Chúng con không cậy vào đức công chính của chúng con để cầu xin Ngài, nhưng xin cậy vào ơn thương xót lớn lao của Ngài.  19 Lạy Chúa, xin lắng nghe; lạy Chúa, xin tha thứ; lạy Chúa, xin đoái thương và hành động.  Vì cớ danh Ngài, xin đừng trì hoãn, lạy Ðức Chúa Trời của con, và cũng vì cớ thành của Ngài và dân mang danh Ngài nữa.”

                """],
            ["Bảy Mươi Tuần": """
                20 Trong khi tôi đang nói, cầu nguyện, và xưng tội của tôi và tội của dân I-sơ-ra-ên tôi, và trình dâng những lời khẩn nguyện của tôi lên trước thánh nhan CHÚA, Ðức Chúa Trời của tôi, vì cớ núi thánh của Ðức Chúa Trời tôi, 21 đang khi tôi nói những lời cầu nguyện ấy, người đàn ông Gáp-ri-ên, người tôi đã thấy trong khải tượng trước, được sai bay vụt đến bên tôi vào giờ dâng của lễ chiều tối.  22 Vị ấy giúp cho tôi hiểu, nói chuyện với tôi, và bảo rằng, “Hỡi Ða-ni-ên, bây giờ ta đến để ban cho ngươi sự thông minh và thông sáng.  23 Khi ngươi bắt đầu cầu nguyện thì lệnh đã ban ra, và ta đến để báo cho ngươi lệnh ấy, vì ngươi rất được yêu quý.  Vậy hãy suy nghĩ về sứ điệp và hiểu ý nghĩa của khải tượng:
                24 Bảy mươi tuần đã được định cho dân ngươi và cho thành thánh của ngươi, để kết thúc sự vi phạm, chấm dứt tội lỗi, đền xong tội ác, mang lại sự công chính vĩnh cửu, làm ứng nghiệm khải tượng và lời tiên tri, và xức dầu cho Nơi Chí Thánh.  25 Vậy ngươi khá biết và hiểu rằng từ khi lệnh ban ra để tái lập và tái thiết Giê-ru-sa-lem cho đến khi Ðấng Mê-si-a Vị Thủ Lãnh xuất hiện sẽ có bảy tuần và sáu mươi hai tuần.  Các phố xá và các chiến hào sẽ được xây dựng lại, mặc dù giữa lúc nhiễu nhương.  26 Sau sáu mươi hai tuần, Ðấng Mê-si-a sẽ bị giết, rồi sẽ chẳng còn gì.  Quân lính của tên thủ lãnh sắp đến sẽ phá hủy thành và nơi thánh.  Hậu quả cuối cùng sẽ như bị một trận lụt tàn phá, và đến cuối cùng sẽ có chiến tranh; còn những cảnh tan hoang đã định ắt sẽ xảy ra.  27 Tên thủ lãnh sắp đến ấy sẽ xác định lập trường của nó với nhiều người qua một giao ước có thời hạn một tuần.  Tuy nhiên chỉ mới giữa tuần, nó sẽ bắt người ta phải ngưng dâng các sinh vật hiến tế và các lễ vật.  Nó sẽ làm cho nơi ấy phải chịu cảnh tan hoang bằng cách đem vào cánh của nơi thánh những thứ gớm ghiếc, và chúng sẽ còn đó cho đến hồi kết thúc.  Bấy giờ những gì đã định sẽ trút xuống đầu kẻ gây nên cảnh tan hoang.”

                """]
            ]),
        Chapter(10, passages: [
            ["Sự Xung Ðột giữa Các Nước và Quyền Lực Thiên Thượng": """
                1 Trong năm thứ ba của triều đại Sy-ru vua Ba-tư, một sứ điệp đã được bày tỏ cho Ða-ni-ên, cũng có tên là Bên-tê-sác-xa.  Sứ điệp ấy là thật và liên quan đến chiến tranh khủng khiếp về sau.  Ông hiểu ý nghĩa của sứ điệp ấy và cũng hiểu ý nghĩa của khải tượng.
                2 Trong những ngày ấy, tôi, Ða-ni-ên, đã than khóc trọn ba tuần.  3 Tôi không ăn những thức ăn ngon; thịt và rượu không vào miệng tôi; tôi cũng không xức dầu cho mình trọn ba tuần.
                4 Vào ngày hai mươi bốn, tháng giêng, đang khi đứng bên bờ Sông Cả, Sông Khít-đê-ken, 5 tôi ngước mắt lên nhìn, và này, có một người mặc y phục bằng vải gai, lưng thắt đai bằng vàng ròng U-pha.  6 Thân hình người ấy như lục bích ngọc, mặt người ấy tỏa rạng hào quang như sét chớp, đôi mắt người ấy như hai đuốc đang rực cháy, hai tay và hai chân người ấy như đồng đánh bóng, và tiếng nói của người ấy như tiếng gào của một đám đông.
                7 Tôi, Ða-ni-ên, chỉ một mình tôi thấy khải tượng ấy; những người ở với tôi lúc đó không thấy khải tượng ấy.  Tuy nhiên một cơn run rẩy hãi hùng giáng trên họ, họ bỏ chạy tìm chỗ lẩn trốn.  8 Vì thế chỉ còn lại một mình tôi và tôi đã thấy khải tượng kinh khủng đó.  Tôi không còn chút sức lực nào; mặt tôi có lẽ đã tái ngắt như người chết, và tôi bủn rủn cả người.  9 Bấy giờ tôi nghe tiếng người ấy nói.  Vừa khi tôi nghe những lời người ấy nói, mặt tôi như kẻ mất hồn, và tôi nằm sấp mặt xuống đất.  10 Này, một bàn tay chạm vào tôi, khiến tôi chổm dậy mà hai tay và hai đầu gối tôi cứ run lẩy bẩy.  11 Người ấy nói với tôi, “Hỡi Ða-ni-ên, người rất được yêu thương, hãy hiểu những lời ta sắp nói với ngươi.  Hãy đứng thẳng dậy, vì bây giờ ta được sai đến với ngươi.”  Khi người ấy nói với tôi như thế, tôi đứng thẳng dậy nhưng vẫn còn run lập cập.  12 Người ấy nói tiếp, “Hỡi Ða-ni-ên, đừng sợ, vì từ ngày đầu tiên khi ngươi để lòng tìm hiểu và hạ mình xuống trước mặt Ðức Chúa Trời của ngươi, những lời cầu xin của ngươi đã được nhậm, và ta đến để đáp lời cầu nguyện của ngươi.  13 Nhưng thủ lĩnh của vương quốc Ba-tư đã cản trở ta hai mươi mốt ngày.  Vì thế Mi-chên, một trong những vị thống soái, đã đến giúp ta, vì ta đã bị bỏ lại đó với các vua Ba-tư.  14 Bây giờ ta đến để giúp ngươi hiểu những gì sẽ xảy đến cho dân ngươi trong những ngày cuối cùng, vì khải tượng ấy liên quan đến những ngày còn xa lắm trong tương lai.”
                15 Khi người ấy nói những lời ấy với tôi, tôi cúi đầu xuống đất và im lặng.
                16 Này, một đấng có hình dáng giống con cái loài người chạm vào môi tôi; tôi mở miệng và nói được.  Tôi nói với vị đứng trước mặt tôi, “Thưa ngài, khải tượng tôi thấy đã làm tôi đau đớn đến nỗi chẳng còn sức lực nữa.  17 Làm thể nào tôi tớ ngài có thể nói gì với ngài được?  Vì sức lực, ngay cả hơi thở dường như cũng không còn trong tôi.”
                18 Ðấng có hình dáng loài người chạm vào tôi một lần nữa và ban sức lực cho tôi.  19 Ðấng ấy nói, “Hỡi người rất được yêu quý, đừng sợ, ngươi hãy an tâm.  Hãy mạnh mẽ và hãy can đảm lên!”
                Khi đấng ấy nói với tôi, tôi liền được phục sức và nói, “Thưa ngài, xin ngài nói, vì ngài đã làm cho tôi được mạnh khỏe.”
                20 Bấy giờ người ấy nói, “Ngươi có biết tại sao ta đến với ngươi không?  Nhưng bây giờ ta phải trở lại để giao chiến với thủ lĩnh của vương quốc Ba-tư.  Khi ta đi rồi, này, thủ lĩnh của vương quốc Hy-lạp sẽ đến.  21 Nhưng trước khi đi ta phải nói cho ngươi biết những gì đã ghi trong Sách Chân Lý.  Không ai hiệp với ta để đối phó với các thủ lĩnh ấy cả, ngoại trừ Mi-chên, thủ lĩnh của các ngươi.

                """]
            ]),
        Chapter(11, passages: [
            ["": """
                1 Về phần ta, trong năm thứ nhất của triều đại Ða-ri-út người Mê-đi, ta đã đứng hỗ trợ và thêm sức cho vua ấy.  2 Bây giờ ta sẽ tỏ cho ngươi biết sự thật.  Này, ba vua nữa sẽ trị vì Ba-tư, nhưng vua thứ tư sẽ giàu hơn ba vua kia rất nhiều.  Sau khi vua ấy đã dùng của cải để xây dựng quyền lực thêm mạnh mẽ, vua ấy sẽ vận động mọi người chống lại vương quốc Hy-lạp.
                3 Bấy giờ một vua hùng mạnh sẽ nổi lên.  Vua ấy sẽ trị vì với quyền hành rộng lớn và muốn làm gì thì làm.  4 Nhưng khi quyền lực của vua ấy đang trên đà lớn mạnh, vương quốc của vua ấy bị tan rã và chia ra theo bốn hướng gió trên trời.  Vương quốc ấy sẽ không do con cháu của vua ấy trị vì, và nó sẽ không còn nhiều quyền lực như trước, vì vương quốc ấy sẽ bị nhổ bật gốc và ban cho những người khác.
                5 Vua phương nam sẽ được hùng mạnh, nhưng một trong các tướng của vua trở nên hùng mạnh hơn vua và sẽ thống trị một vương quốc lớn hơn cả vương quốc của vua.
                6 Vài năm sau họ lập một liên minh.  Công chúa của vua phương nam được gả cho vua phương bắc để bảo đảm cho hiệp ước.  Nhưng nàng không giữ được quyền lực của nàng; ngay cả cha nàng và quyền lực của ông cũng không đứng vững.  Lúc bấy giờ nàng bị trao nộp cùng với phái đoàn hộ tống nàng, luôn cả người sinh ra nàng, và người hỗ trợ nàng.  Chẳng bao lâu sau đó, 7 một người trong dòng dõi nàng lên nắm quyền.  Vua ấy đem quân tiến đánh quân phương bắc và chiếm được thành trì vua đó, và đánh bại vua đó.  8 Vua ấy mang các thần của chúng về lưu đày ở Ai-cập, cùng với các hình tượng bằng kim loại, các vật quý bằng bạc và bằng vàng của chúng.  Mấy năm sau đó vua ấy để yên cho vua phương bắc.
                9 Sau khi khôi phục lực lượng vua phương bắc kéo quân đến xâm lấn lãnh thổ của vua phương nam, nhưng rồi vua ấy cũng phải rút quân về nước.  10 Dầu vậy các con trai của vua ấy vẫn nổ lực chuẩn bị chiến tranh.  Họ thành lập được một đạo quân lớn mạnh.  Một trong các người con đó kéo quân đến, tràn ngập như nước lũ, dìm chìm tất cả, rồi rút quân trở về thành mình, và cứ tiếp tục gây chiến.
                11 Bấy giờ vua phương nam cực kỳ tức giận; vua ấy kéo quân đến tấn công vua phương bắc, người đã thành lập được đạo quân lớn mạnh.  Tuy nhiên đạo quân lớn mạnh đó bị trao vào tay vua phương nam.  12 Khi đoàn tù binh đông đúc bị bắt dẫn đi, lòng vua phương nam nổi lên kiêu ngạo, ông ra lịnh xử tử hàng ngàn tù binh; nhưng chiến thắng của ông chẳng kéo dài được bao lâu.
                13 Chỉ trong vài năm, vua phương bắc tập hợp được một đội quân rất lớn, lớn hơn cả đội quân khi trước, rồi dẫn đội quân lớn và được trang bị đầy đủ đó trở lại.  14 Trong thời gian ấy nhiều người sẽ nổi lên chống lại vua phương nam.  Những kẻ gian hùng ở giữa dân ngươi sẽ thừa cơ dấy loạn, vì tưởng sẽ được làm ứng nghiệm được khải tượng, nhưng chúng thảy đều thất bại.
                15 Vua phương bắc sẽ đến phương nam, đắp mô công thành, và chiếm được một thành kiên cố.  Quân của vua phương nam không chống cự nổi vua phương bắc.  Ngay cả các đơn vị thiện chiến nhất cũng không đủ sức đương đầu với quân thù.  16 Vua phương bắc muốn làm gì thì làm, và không ai có thể làm gì để chống cự nổi ông ấy.  Ông đứng trong Ðất Vinh Hiển với quyền hủy diệt nó trong tay.  17 Ông quyết định dùng toàn lực trong vương quốc của ông để chiếm vương quốc phương nam, nên ông gả con gái ông cho vua phương nam với ý đồ sẽ phá hủy vương quốc đó từ bên trong; nhưng ý đồ đó không thành, và ông chẳng được gì.  18 Sau đó ông quay mặt về hướng biển và chiếm lấy nhiều xứ ở miền duyên hải; nhưng một tướng lãnh đã chấm dứt hành động làm nhục người khác của ông và cho chính ông thấm đòn bị làm nhục.  19 Do đó ông phải quay mặt rút về một thành kiên cố trong nước của ông, nhưng ông bị vấp và ngã nhào, và không ai còn thấy ông nữa.
                20 Kẻ lên kế vị ông sai người đi thu thuế để có thể tiếp tục duy trì sự huy hoàng của vương quốc.  Nhưng chỉ trong một thời gian ngắn, kẻ kế vị ấy bị tiêu diệt, dù không phải vì bị ai tức giận hay bị tử trận nơi chiến trường.
                21 Kẻ đứng lên thế vị là một tên bỉ ổi.  Tên đó không được người ta ban cho vương quyền, nhưng hắn chiếm đoạt vương quyền.  Trong lúc mọi người đang sống an lành và không phòng bị, hắn dùng những lời dối nịnh mà đoạt lấy.  22 Sau đó toàn thể đội quân có sức mạnh như nước lũ đều bị dẹp sạch trước mặt hắn và bị tan rã, kể cả người thủ lãnh đã có giao ước với hắn.  23 Sau khi các hiệp ước đã ký kết với các đối phương, người ta mới khám phá ra rằng những gì hắn ký kết chỉ là lừa gạt.  Nhưng bấy giờ từ một nhóm ít người hắn đã trở nên một kẻ đầy quyền lực rồi.  24 Trong lúc mọi người đang sống an lành và không phòng bị, hắn bất thần chiếm đoạt những vùng trù phú nhất trong xứ.  Hắn làm điều mà không ai trong vòng cha ông và tổ tiên hắn đã làm: hắn chia cho những kẻ theo hắn các của cướp, các chiến lợi phẩm, và các tài sản chúng đã cướp đoạt.  Hắn cũng lập mưu đánh chiếm các thành kiên cố, nhưng điều đó chỉ được một thời gian ngắn.  25 Hắn dốc toàn lực và đảm lược dẫn một đội quân lớn kéo xuống đánh vua phương nam.  Vua phương nam cũng dốc toàn lực đem một đội quân lớn và mạnh ra giao chiến với hắn.  Nhưng vua phương nam sẽ không thể chống cự hắn nổi, vì bầy tôi của ông đã âm mưu hãm hại ông.  26 Những kẻ đã hưởng lộc do ông chu cấp hãm hại ông.  Quân đội của ông bị dẹp tan, và nhiều người ngã gục và tử trận.
                27 Cả hai vua đều toan tính những điều gian ác trong lòng.  Dù chúng ngồi cùng một bàn thương thảo với nhau, nhưng chúng chỉ nói với nhau toàn những lời dối trá.  Do đó việc thương thảo ấy chẳng tới đâu vì hồi kết thúc theo thời điểm đã ấn định chưa đến.  28 Vua phương bắc rút quân về nước và mang theo rất nhiều của cải chiếm được.  Trên đường về hắn sinh lòng chống lại dân của giao ước thánh.  Hắn gây nhiều thiệt hại, rồi tiếp tục kéo quân về nước của hắn.
                29 Ðến kỳ đã định, hắn trở lại xâm lấn phương nam, nhưng lần này, kết quả khác xa lần trước.  30 Trong khi ấy các chiến thuyền từ các nước ở miền biển kéo đến tấn công hắn, do đó hắn lo sợ và buộc lòng phải rút quân về.  Dọc đường hắn trút cơn tức giận trên dân của giao ước thánh.  Về sau hắn trở lại và giúp đỡ đặc biệt những kẻ đã bỏ giao ước thánh.  31 Quân đội do hắn sai đi chiếm lấy đồn bảo vệ Ðền Thờ, làm ô uế nơi thánh, chấm dứt việc dâng của tế lễ hằng ngày, và đem vào đặt trong nơi thánh những vật gớm ghiếc làm cho nơi thánh tan hoang.  32 Hắn sẽ dùng những lời dối trá tâng bốc để lôi kéo những kẻ gian ác chống lại giao ước về với hắn, nhưng những người biết Ðức Chúa Trời mình thì vững mạnh và kiên trì chống lại hắn.  33 Những người khôn ngoan trong dân sẽ chỉ bảo cho nhiều người biết.  Tuy nhiên trong nhiều ngày, họ bị gươm ngã chết, bị thiêu sống, bị tù đày, và bị cướp bóc.  34 Khi họ bị hoạn nạn ngã chết như thế, chỉ có một ít người thật sự giúp đỡ họ, vì phần nhiều những kẻ gia nhập với họ đều không thật lòng.  35 Trong số những người khôn ngoan có một số người ngã xuống, hầu họ được tinh luyện, thanh tẩy, và làm cho thánh sạch, cho đến thời kỳ cuối cùng, vì thời kỳ đã ấn định ấy chưa đến.
                36 Vua ấy sẽ tha hồ muốn làm gì thì làm.  Hắn tự tôn hắn lên và tự cho mình là vĩ đại hơn tất cả các thần.  Hắn buông những lời ngạo mạn xúc phạm đến Ðức Chúa Trời của các thần, và hắn được thành công cho đến khi cơn thịnh nộ dành cho hắn được đầy trọn, vì những gì đã định chắc chắn phải được thực hiện.  37 Hắn không coi các thần của tổ tiên hắn thờ phượng ra gì; hắn không coi thần phái nữ ái mộ ra gì, và hắn cũng không coi bất cứ thần nào ra gì, vì hắn tự cho hắn vĩ đại hơn tất cả các thần.  38 Ðể thay vào chỗ các thần ấy, hắn thờ thần các đồn lũy, một thần mà cha ông hắn không hề biết.  Hắn dâng cúng cho thần ấy vàng, bạc, bửu thạch, và các báu vật.  39 Hắn tin cậy vào thần lạ ấy giúp đỡ nên đi tấn công các thành trì kiên cố nhất.  Những ai quy phục hắn, hắn làm cho được tôn trọng.  Hắn bổ nhiệm chúng vào những chức vụ có quyền hành trên nhiều người, và hắn chia đất cho chúng để thưởng công chúng.

                """],
            ["Thời Cuối Cùng": """
                40 Ðến thời kỳ kết thúc, vua phương nam đến tấn công hắn.  Hắn kéo ra chống lại như vũ bão với các xe chiến mã, các kỵ binh, và các tàu chiến.  Hắn tiến vào các nước, tràn ngập chúng, và càn qua chúng như nước lụt.  41 Hắn xâm lăng Ðất Vinh Hiển.  Nhiều nước bị sụp đổ, nhưng các nước sau đây thoát khỏi tay hắn: Ê-đôm, Mô-áp, và những nơi trọng yếu của người Am-môn.  42 Hắn tóm thâu nhiều nước vào tay hắn, ngay cả đất Ai-cập cũng không thoát khỏi.  43 Hắn nắm quyền trên tất cả các kho vàng, các kho bạc, và các kho báu vật của người Ai-cập.  Dân Li-by-a và dân Ê-thi-ô-pi đều phải quy phục hắn.  44 Nhưng các tin tức từ phương đông và phương bắc gởi về làm cho hắn lo sợ.  Hắn nổi giận kéo quân ra đi và quyết tâm sát hại và tiêu diệt nhiều người.  45 Hắn dựng doanh trại của hắn ở khoảng giữa biển và núi thánh vinh hiển; nhưng ngày tàn của hắn đã đến, và không ai giúp đỡ hắn.

                """]
            ]),
        Chapter(12, passages: [
            ["Sự Sống Lại của Người Chết": """
                1 Vào lúc đó, Mi-chên, vị đại thống soái, đấng luôn đứng binh vực cho dân ngươi, sẽ đứng dậy.  Khi ấy sẽ có một thời kỳ hoạn nạn mà từ khi loài người lập quốc cho đến bấy giờ chưa hề có như vậy.  Nhưng khi ấy dân ngươi, tất cả những người có tên được ghi trong sách, sẽ được cứu.  2 Nhiều người đã ngủ trong bụi đất sẽ trỗi dậy.  Một số để hưởng sự sống đời đời, và một số để bị sỉ nhục và ghê tởm đời đời.
                3 Những người khôn ngoan sẽ rạng rỡ như ánh sáng trên bầu trời, và những ai dẫn đưa nhiều người đến sự công chính sẽ rực sáng như các vì sao đời đời mãi mãi.
                4 Nhưng ngươi, Ða-ni-ên, hãy giữ kín sứ điệp này và hãy niêm phong sách này lại cho đến thời kỳ cuối cùng, thời mà nhiều kẻ sẽ chạy tới chạy lui và tri thức sẽ gia tăng.”
                5 Bấy giờ, tôi, Ða-ni-ên, đang nhìn, và này, hai người khác xuất hiện; một người đứng bên này bờ sông, và một người đứng bên kia bờ sông.  6 Một người cất tiếng nói với người mặc y phục bằng vải gai mịn đang đứng trên dòng sông, “Cho đến bao giờ những việc lạ lùng ấy sẽ được ứng nghiệm?”
                7 Tôi nghe người mặc y phục bằng vải gai mịn đứng trên dòng sông đưa tay phải và tay trái mình lên trời, và nhân danh Ðấng sống đời đời mà thề rằng, “Sẽ phải qua một kỳ, các kỳ, và nửa kỳ; khi quyền lực của dân thánh cuối cùng bị gãy đổ hoàn toàn, bấy giờ mọi sự ấy sẽ hoàn tất.”
                8 Tôi nghe nhưng chẳng hiểu gì, vì thế tôi nói, “Thưa ngài, cuối cùng của những sự ấy sẽ ra sao?”
                9 Người ấy đáp, “Hỡi Ða-ni-ên, hãy yên chí, vì sứ điệp này sẽ được giữ kín và niêm phong cho đến thời cuối cùng.  10 Nhiều người sẽ được thanh tẩy, làm cho thánh sạch, và tinh luyện; tuy nhiên những kẻ gian ác sẽ tiếp tục gian ác, và chẳng ai trong bọn chúng sẽ hiểu gì, nhưng những người khôn ngoan sẽ hiểu rõ.
                11 Từ lúc của lễ thiêu hằng ngày bị cất đi và vật gớm ghiếc khiến cho tan hoang được lập lên là một ngàn hai trăm chín mươi ngày.
                12 Phước thay cho những người trông đợi và bền đỗ cho đến một ngàn ba trăm ba mươi lăm ngày.
                13 Còn ngươi, hãy đi con đường của ngươi cho đến cùng, rồi ngươi sẽ được an nghỉ.  Ðến ngày cuối cùng, ngươi sẽ đứng lên nhận lãnh phần đã dành cho ngươi.”

                """]
            ])
    ]
    
}
