
class Exote: Book {
    
    override init() {
        super.init()
        title = "Ê-XƠ-TÊ"
        chapters = allChapters
        allChapters.forEach{ $0.book = self }
    }
    
    var allChapters: [Chapter] = [
        Chapter(1, passages: [
            ["Vua A-ha-suê-ru Ðãi Tiệc": """
                1 Việc này đã xảy ra trong thời của A-ha-suê-ru; A-ha-suê-ru này là người cai trị một trăm hai mươi bảy tỉnh, từ Ấn-độ đến Ê-thi-ô-pi.  2 Thuở ấy Vua A-ha-suê-ru đã ngồi vững trên ngai của ông tại kinh thành Su-sa.  3 Năm thứ ba của triều đại ông, ông mở một đại tiệc thết đãi tất cả quần thần và bầy tôi của ông.  Các tướng lãnh chỉ huy quân đội Ba-tư và Mê-đi, các nhà quyền quý, và các tỉnh trưởng ở các tỉnh đều về hiện diện đông đủ.  4 Nhân cơ hội ấy ông biểu dương sự giàu sang phú quý của vương quốc ông và sự huy hoàng uy nghi rực rỡ của ông nhiều ngày – một trăm tám mươi ngày cả thảy.
                5 Khi những ngày ấy qua rồi, vua lại bày một tiệc khác bảy ngày nữa, trong vườn ngự uyển của hoàng cung, để thết đãi mọi người ở kinh thành Su-sa, cả lớn lẫn nhỏ.  6 Trong vườn ngự uyển người ta treo những bức màn bằng vải trắng và vải xanh dương.  Người ta dùng các dây vải màu tím để máng các màn ấy vào các vòng bằng bạc và cột chúng vào những trụ đá cẩm thạch.  Trong vườn ngự uyển có các băng ghế bằng vàng và bằng bạc, đặt trên những nền đá quý được lát rất mỹ thuật, nào là đá màu đỏ trắng, đá cẩm thạch, đá lam lục, và đá có vân đen.  7 Người ta dùng các ly uống rượu bằng vàng có kiểu rất độc đáo và mỹ thuật để đãi khách.  Các thực khách đều được tiếp rượu dồi dào, xứng hợp với cung cách đãi khách giàu sang phú quý của bậc đế vương.  8 Người ta mang rượu ra hàng hũ để đãi khách.  Ai muốn uống bao nhiêu tùy ý, vì vua đã truyền cho các quan chức phục vụ ở hoàng cung phải chiều ý mọi người.  9 Ngoài ra Hoàng Hậu Vả-thi cũng mở một tiệc riêng để thết đãi các mệnh phụ phu nhân trong cung điện của Vua A-ha-suê-ru.

                """],
            ["Hoàng Hậu Vả-thi Bị Truất Phế": """
                10 Vào ngày thứ bảy khi rượu đã làm cho vua hứng chí, vua truyền lệnh cho Mê-hu-man, Bi-tha, Hạc-bô-na, Bích-tha, A-ba-tha, Xê-tha, và Ca-cách –bảy quan thái giám đang hầu vua– 11 đưa Hoàng Hậu Vả-thi, đội mão triều, đến chầu vua, để dân chúng và triều thần được cơ hội chiêm ngưỡng sắc đẹp của bà, vì bà là một tuyệt sắc giai nhân.  12 Nhưng Hoàng Hậu Vả-thi từ chối vâng theo lệnh vua do các quan thái giám mang đến.  Vì thế vua vô cùng tức giận, và lòng vua nổi giận bừng bừng.
                13 Bấy giờ vua tham khảo ý kiến của các quân sư, những người am hiểu tình hình chính trị, vì đó là cách vua thường làm đối với những vị am tường luật pháp và việc xử đoán, mỗi khi hữu sự.  14 Những người hầu cận bên vua gồm Cạt-sê-na, Sê-tha, Át-ma-tha, Tạt-si, Mê-rê, Mạc-sê-na, và Mê-mu-can, tức bảy quan thượng thư của Ba-tư và Mê-đi, những người thường đứng chầu trước mặt vua và nắm giữ những chức vụ hàng đầu trong đế quốc.  15 “Theo luật thì chúng ta phải làm sao với Hoàng Hậu Vả-thi, vì bà đã không tuân lệnh Vua A-ha-suê-ru do các quan thái giám mang đến?”
                16 Bấy giờ Mê-nu-can tâu với vua trước mặt các quan thượng thư, “Hoàng Hậu Vả-thi không những đã có lỗi với hoàng thượng, nhưng cũng có lỗi với tất cả các quần thần và tất cả các dân sống trong tất cả các tỉnh của Vua A-ha-suê-ru.  17 Vì khi hành động này của hoàng hậu bị đồn ra đến tai toàn thể phụ nữ, họ sẽ nhìn chồng của họ với cặp mắt khinh thường.  Họ sẽ bảo, ‘Vua A-ha-suê-ru đã truyền đem Hoàng Hậu Vả-thi đến chầu vua, nhưng bà ấy không đi thì có sao đâu?’  18 Hôm nay thế nào các mệnh phụ phu nhân của Ba-tư và Mê-đi cũng sẽ về nói cho tất cả các quần thần của hoàng thượng rằng họ đã nghe về thái độ của hoàng hậu.  Như thế rồi đây trong vương quốc sẽ có không biết bao nhiêu vấn đề xảy ra do sự khinh thường của vợ và phản ứng tức giận của chồng.  19 Vậy nếu đẹp ý hoàng thượng, xin hoàng thượng ban một sắc chỉ và cho ghi vào trong sách luật của người Ba-tư và Mê-đi để không thể thay đổi được rằng Vả-thi sẽ không bao giờ được diện kiến Vua A-ha-suê-ru nữa, và kính xin hoàng thượng ban chức vụ đó cho người nào xứng đáng hơn bà.  20 Rồi đây khi sắc chỉ của hoàng thượng được công bố trong toàn thể vương quốc bao la rộng lớn này, bấy giờ tất cả phụ nữ sẽ tôn trọng chồng họ, bất kể giàu sang hay nghèo khó.”
                21 Lời tâu đó đẹp lòng vua và các triều thần.  Vua bèn làm y như lời của Mê-nu-can đã đề nghị.  22 Vua ban sắc chỉ gởi đến tất cả các tỉnh của ông.  Tỉnh nào theo chữ viết của tỉnh ấy, dân nào theo ngôn ngữ của dân ấy, và truyền rằng trong mỗi gia đình người đàn ông là chủ gia đình.

                """]
            ]),
        Chapter(2, passages: [
            ["Ê-xơ-tê Ðược Chọn Làm Hoàng Hậu": """
                1 Sau những việc ấy khi cơn giận của Vua A-ha-suê-ru đã nguôi ngoai, vua nhớ đến Vả-thi và những việc bà đã làm; ông cũng nhớ đến sắc lệnh ông đã ban ra để xử tội bà.  2 Bấy giờ các quan hầu cận của vua nói, “Phải tìm cho hoàng thượng những trinh nữ trẻ đẹp.  3 Xin hoàng thượng bổ nhiệm các quan đặc nhiệm ở tất cả các tỉnh trong vương quốc của hoàng thượng, để họ tìm các thiếu nữ trẻ đẹp, đem về hậu cung ở Kinh Ðô Su-sa, và giao cho Hê-gai quan thái giám của hoàng thượng, người trông coi các phụ nữ trong cung; và xin cung cấp cho họ các mỹ phẩm họ cần.  4 Sau đó hễ cô nào đẹp lòng hoàng thượng, xin hoàng thượng lập người ấy làm hoàng hậu thế cho Vả-thi.”  Ðề nghị ấy đẹp lòng vua, và vua làm như vậy.
                5 Bấy giờ tại Kinh Ðô Su-sa có một người Do-thái tên là Mạc-đô-chê, con cháu của Giai-rơ, con cháu của Si-mê-i, con cháu của Kích, dòng dõi của Bên-gia-min.  6 Người Bên-gia-min ấy bị bắt phải rời khỏi Giê-ru-sa-lem đi lưu đày cùng một lượt với Giê-cô-ni-a vua Giu-đa, tức vị vua đã bị Nê-bu-cát-nê-xa vua Ba-by-lôn bắt đi lưu đày.  7 Mạc-đô-chê đã nuôi Ha-đác-sa, cũng gọi là Ê-xơ-tê, con gái của chú ông, bởi vì nàng đã mồ côi cha mẹ từ thuở nhỏ.  Nàng là một thiếu nữ duyên dáng và xinh đẹp.  Khi cha mẹ nàng qua đời, ông đã nhận nàng làm con gái của ông.  8 Vì thế khi lệnh vua được ban ra và sắc chỉ của vua được công bố, nhiều thiếu nữ trẻ đẹp đã bị tập họp về Kinh Ðô Su-sa, đặt dưới quyền quản lý của Hê-gai.  Ê-xơ-tê cũng bị đem vào hoàng cung và ở dưới quyền quản lý của Hê-gai, người trông coi các phụ nữ trong cung.  9 Người thiếu nữ ấy được cảm tình của ông, nên ông đối xử tốt với nàng.  Ông vội vàng cung cấp các mỹ phẩm và lương thực cho nàng.  Ông cũng chọn bảy cung nữ đang phục vụ trong hoàng cung để hầu hạ nàng và sắp đặt họ vào ở trong một phòng sang trọng nhất ở hậu cung.  10 Ê-xơ-tê không tiết lộ cho ai biết về gốc tích dân tộc hay dòng họ của nàng, vì Mạc-đô-chê đã dặn nàng không được tiết lộ gì với ai cả.  11 Hằng ngày Mạc-đô-chê đều tới lui trước sân hậu cung để dò la tin tức về Ê-xơ-tê hầu biết tình trạng của nàng ra sao.
                12 Bấy giờ đã đến lúc các thiếu nữ lần lượt theo phiên vào hầu Vua A-ha-suê-ru.  Số là mỗi người phải trải qua mười hai tháng chuẩn bị trước khi được vào hầu vua, như quy chế dành cho phụ nữ thời bấy giờ.  Các cô ấy phải tẩm ướp da thịt mình bằng mộc dược trong sáu tháng, sáu tháng còn lại phải tẩm ướp da thịt mình với nước hoa và các thứ mỹ phẩm dành cho phụ nữ.  13 Khi một thiếu nữ được vào hầu vua, cô gái ấy có quyền xin bất cứ món gì trong hậu cung để mang theo khi ra mắt vua trong hoàng cung.  14 Chiều tối cô gái ấy được đưa vào, sáng hôm sau cô ấy sẽ trở ra và được đưa đến một hậu cung khác, dưới quyền của Sa-ách-ga quan thái giám của vua, người trông coi các cung phi.  Cô gái ấy sẽ không được vào hầu vua nữa, nếu vua không sủng ái và cho gọi đích danh.
                15 Khi đến phiên Ê-xơ-tê con gái của A-bi-ha-in, chú của Mạc-đô-chê, người nhận Ê-xơ-tê làm con gái của mình, đi vào hầu vua, nàng không yêu cầu món gì đặc biệt, ngoại trừ những gì Hê-gai quan thái giám của vua, người trông coi các phụ nữ trong cung, đề nghị.  Lúc ấy tất cả những ai trông thấy nàng đều trầm trồ khen ngợi nàng.  16 Vậy Ê-xơ-tê được đem vào hầu Vua A-ha-suê-ru trong hoàng cung vào tháng mười, tức tháng Tê-bết, nhằm năm thứ bảy của triều đại vua.  17 Vua yêu thương Ê-xơ-tê hơn tất cả các phụ nữ khác.  Trong tất cả các trinh nữ, nàng được vua yêu mến và sủng ái nhất.  Vì thế vua đội mão triều trên đầu nàng và lập nàng làm hoàng hậu thay cho Vả-thi.  18 Vua mở tiệc linh đình khoản đãi tất cả triều thần và khanh tướng; đó là tiệc mừng tân Hoàng Hậu Ê-xơ-tê.  Vua cũng cho các tỉnh được nghỉ lễ một ngày và ban tặng các phẩm vật xứng đáng với sự giàu sang phú quý của bậc đế vương.

                """],
            ["Mạc-đô-chê Cứu Mạng Vua": """
                19 Số là khi các trinh nữ được tập họp đợt hai, lúc ấy Mạc-đô-chê đang ngồi ở cổng hoàng cung.  20 Ê-xơ-tê vẫn chưa tiết lộ tông tộc hay dòng giống của bà, y như Mạc-đô-chê đã căn dặn bà, vì Ê-xơ-tê vẫn vâng lời Mạc-đô-chê như lúc bà còn được nuôi dạy.  21 Lúc ấy Mạc-đô-chê đang ngồi ở cổng hoàng cung, Bích-than và Tê-rếch, hai quan thái giám của vua, đã giận vua và lập mưu ám sát Vua A-ha-suê-ru.  22 Nhưng Mạc-đô-chê biết được điều đó.  Ông báo tin đó cho Hoàng Hậu Ê-xơ-tê.  Ê-xơ-tê liền tâu với vua và nói rằng bà biết được tin đó nhờ Mạc-đô-chê.  23 Sau khi vua cho điều tra và thấy âm mưu đó là thật, vua truyền treo cổ hai quan thái giám ấy trên cây mộc hình.  Sự việc đó được ghi vào sách sử ký trước mặt vua.
                """]
            ]),
        Chapter(3, passages: [
            ["Ha-man Lập Mưu Diệt Dân Do-thái": """
                1 Sau các việc đó Vua A-ha-suê-ru thăng chức cho Ha-man con của Ham-mê-đa-tha, người A-ga-ghi.  Vua lập ông làm tể tướng, giữ địa vị cao trọng hơn mọi triều thần của vua.  2 Tất cả quần thần của vua ở cổng hoàng cung đều cúi đầu và lạy ông, vì vua đã truyền mọi người phải làm như thế đối với ông.  Tuy nhiên Mạc-đô-chê không cúi đầu hoặc lạy ông.  3 Bấy giờ các triều thần của vua ở cổng hoàng cung nói với Mạc-đô-chê, “Tại sao ông không vâng lệnh vua?”  4 Ngày nào họ cũng hỏi ông như thế, nhưng ông chẳng nghe lời họ.  Bấy giờ họ tâu với Ha-man để xem ai thắng hơn ai, vì ông đã bảo với họ rằng ông là người Do-thái.  5 Khi Ha-man thấy Mạc-đô-chê không cúi đầu hoặc lạy mình, Ha-man vô cùng tức giận.  6 Nhưng ông nghĩ rằng nếu chỉ ra tay giết một mình Mạc-đô-chê thì quá tầm thường.  Vì thế sau khi biết rõ Mạc-đô-chê là người Do-thái, Ha-man quyết định tiêu diệt toàn dân Do-thái đang sống trong đế quốc của Vua A-ha-suê-ru.
                7 Vào tháng giêng tức tháng Ni-san của năm thứ mười hai triều đại Vua A-ha-suê-ru, người ta gieo Pu-rơ, tức gieo thăm, trước mặt Ha-man, để định ngày và tháng.  Thăm rơi nhằm ngày mười ba tháng mười hai, tức tháng A-đa.  8 Sau đó Ha-man vào tâu với Vua A-ha-suê-ru, “Có một dân nọ sống rải rác và cách biệt với các dân tộc khác ở khắp các tỉnh trong vương quốc của hoàng thượng.  Luật lệ của chúng khác hẳn với luật lệ của các dân tộc khác.  Chúng không vâng giữ luật pháp của hoàng thượng.  Cứ để chúng như thế thật là bất lợi cho hoàng thượng.  9 Nếu đẹp lòng hoàng thượng, xin hoàng thượng ban một sắc chỉ để tiêu diệt chúng.  Hạ thần sẽ cho cân ba trăm bốn chục ngàn ký bạc trao vào tay các quan quản lý ngân khố của hoàng thượng, để họ đưa vào kho của hoàng thượng.”  10 Vua lấy chiếc nhẫn có ấn dấu đeo nơi tay mình mà trao cho Ha-man con của Ham-mê-đa-tha, người A-ga-ghi, kẻ thù của người Do-thái.  11 Vua nói với Ha-man, “Ngươi hãy giữ lại số bạc đó, ta trao dân đó vào tay ngươi, ngươi muốn làm gì chúng thì làm.”
                12 Thế là ngày mười ba tháng giêng, các ký lục của vua được triệu đến để ghi sắc chỉ.  Toàn thể nội dung của sắc chỉ đều cứ theo lệnh của Ha-man mà chép ra.  Sắc chỉ ấy được gởi cho các thống đốc, các tỉnh trưởng cai trị các tỉnh, và các tổng trấn của các dân, tỉnh nào theo chữ viết của tỉnh ấy, dân nào theo ngôn ngữ của dân ấy.  Sắc chỉ ấy được nhân danh Vua A-ha-suê-ru viết ra và được đóng bằng ấn dấu của vua.
                13 Các sắc chỉ ấy được những người đưa thư mang đến các tỉnh của vua, truyền lệnh phải tiêu diệt, giết chết, và tận diệt mọi người Do-thái, cả trẻ lẫn già, phụ nữ và trẻ thơ, trong một ngày, đó là ngày mười ba tháng mười hai, tức tháng A-đa, và cướp lấy tất cả tài sản của họ.  14 Bản sao của sắc chỉ ấy cũng được ban hành ở mỗi tỉnh dưới hình thức sắc lệnh để công bố và kêu gọi mọi dân tộc trong vương quốc phải chuẩn bị sẵn sàng cho ngày đó.
                15 Theo lệnh vua những người đưa thư cấp tốc mang sắc chỉ ra đi.  Ngay tại Kinh Ðô Su-sa một chiếu chỉ về việc ấy cũng được ban hành.  Sau đó vua và Ha-man ngồi xuống uống rượu trong khi cả Kinh Ðô Su-sa đều bối rối kinh hoàng.

                """]
            ]),
        Chapter(4, passages: [
            ["Ê-xơ-tê Nhận Lời Vào Cầu Xin Vua cho Dân Do-thái": """
                1 Khi Mạc-đô-chê biết mọi điều ấy đã được thực hiện, ông xé rách y phục của ông, mặc bao gai, và rắc tro trên đầu ông, rồi đi ra giữa thành, lớn tiếng khóc lóc đắng cay.  2 Ông cũng đã đến tận cổng của hoàng cung, vì không ai mặc bao gai mà được phép bước vào bên trong cổng của hoàng cung.  3 Trong mỗi tỉnh, nơi nào lệnh vua và sắc chỉ của vua được truyền đến, nơi ấy người Do-thái sầu thảm rất bi thương.  Họ kiêng ăn, khóc lóc, và than van.  Nhiều người đã mặc lấy bao gai và nằm trong tro.
                4 Khi các cung nữ và các thái giám đến báo tin cho Ê-xơ-tê biết, hoàng hậu rất đỗi buồn rầu.  Bà sai người mang áo quần đến cho Mạc-đô-chê để ông mặc mà cởi bỏ bao gai ra, nhưng ông không nhận những quần áo ấy.  5 Bấy giờ Ê-xơ-tê cho mời Hà-thạch, một trong các quan thái giám mà vua đã chỉ định để hầu bà, đến và bảo ông phải ra gặp Mạc-đô-chê để hỏi xem chuyện gì đã xảy ra và nguyên do của sự việc như thế nào.  6 Hà-thạch đi ra gặp Mạc-đô-chê ở quảng trường, phía trước cổng hoàng cung.  7 Mạc-đô-chê nói cho ông tất cả những gì đã xảy ra cho mình và nói luôn cho ông biết số tiền Ha-man đã hứa sẽ nộp vào ngân khố của vua, hầu được phép tiêu diệt người Do-thái.  8 Mạc-đô-chê cũng trao cho ông một bản sao chiếu chỉ đã ban hành tại Su-sa, truyền phải tiêu diệt họ, để ông mang về cho Ê-xơ-tê xem, giải thích ý nghĩa của nó cho bà, và yêu cầu bà đến gặp vua, để cầu xin vua và van nài vua cho dân tộc của bà.
                9 Hà-thạch trở về và thuật lại cho Ê-xơ-tê mọi việc Mạc-đô-chê đã nói.  10 Bấy giờ Ê-xơ-tê nói với Hà-thạch và truyền cho ông ra nói với Mạc-đô-chê, 11 “Tất cả các triều thần của vua và dân trong các tỉnh đều biết rằng, hễ ai, bất kỳ nam hay nữ, tự ý đi vào nội điện của triều cung mà không được triệu mời thì chỉ có một luật là bị xử tử, ngoại trừ vua đưa cây phủ việt bằng vàng ra cho người ấy, người ấy mới được để cho sống.  Tuy nhiên đã ba mươi ngày rồi con vẫn chưa được gọi vào để hầu vua.”
                12 Khi người ta đã thuật lại cho Mạc-đô-chê những gì Ê-xơ-tê đã nói, 13 Mạc-đô-chê bảo họ trở vào và nói lại với Ê-xơ-tê, “Con đừng tưởng rằng nhờ ở trong hoàng cung con sẽ thoát khỏi những điều mọi người Do-thái khác sẽ phải chịu, 14 vì nếu con yên lặng trong lúc này, dân Do-thái sẽ được tiếp trợ và giải cứu bằng cách khác, nhưng con và nhà cha con sẽ bị diệt mất; và nào ai biết rằng phải chăng vì thời điểm như thế này mà con đã được lập làm hoàng hậu?”
                15 Bấy giờ Ê-xơ-tê sai người ra trả lời với Mạc-đô-chê, 16 “Xin cha đi và mời tất cả những người Do-thái ở Su-sa nhóm lại, rồi vì cớ con mà kiêng ăn; xin kiêng ăn cữ uống trong ba ngày đêm.  Con và các cung nữ của con cũng sẽ kiêng cữ như vậy.  Sau đó con sẽ đi vào chầu vua, đó là một việc trái phép; và nếu con phải chết thì con sẽ chết.”  17 Mạc-đô-chê ra đi và làm theo mọi điều Ê-xơ-tê yêu cầu.

                """]
            ]),
        Chapter(5, passages: [
            ["Ê-xơ-tê Ðãi Tiệc": """
                1 Ngày thứ ba Ê-xơ-tê mặc bộ đồ triều phục và đến đứng chầu tại nội điện của triều cung, đối ngang cung thất của vua.  Lúc ấy vua đang ngồi trên ngai trong cung điện đối diện với cung môn.  2 Vừa khi vua thấy Hoàng Hậu Ê-xơ-tê đứng nơi sân chầu, bà liền được ơn trước mặt vua; vua đưa cây phủ việt đang cầm trong tay ra cho bà.  Ê-xơ-tê lại gần và rờ vào đầu cây phủ việt.  3 Vua nói với bà, “Hoàng Hậu Ê-xơ-tê, khanh có thỉnh nguyện gì?  Khanh muốn xin điều gì?  Dù đến phân nửa vương quốc của trẫm, trẫm cũng sẽ ban cho.”
                4 Bấy giờ Ê-xơ-tê đáp, “Nếu đẹp lòng hoàng thượng, kính mời hoàng thượng và Ha-man hôm nay đến dự tiệc do thần thiếp đã chuẩn bị để thết đãi hoàng thượng.”
                5 Vua phán, “Hãy mau mời Ha-man đến, để chúng ta có thể làm theo điều Ê-xơ-tê muốn.”
                Vậy vua và Ha-man đến dự tiệc do Ê-xơ-tê đã chuẩn bị.  6 Trong khi họ đang uống rượu, vua nói với Ê-xơ-tê, “Khanh có thỉnh nguyện gì?  Trẫm sẽ ban cho.  Khanh muốn xin điều gì?  Dù đến phân nửa vương quốc của trẫm, trẫm cũng sẽ ban cho.”
                7 Bấy giờ Ê-xơ-tê đáp, “Ðây là thỉnh nguyện và lời cầu xin của thần thiếp: 8 Nếu thần thiếp được ơn của hoàng thượng, và nếu đẹp lòng hoàng thượng để được hoàng thượng ban cho những gì thần thiếp muốn thỉnh nguyện và cầu xin, kính mời hoàng thượng và Ha-man ngày mai trở lại dự tiệc do thần thiếp thết đãi, rồi bấy giờ thần thiếp sẽ làm theo lời hoàng thượng dạy bảo.”
                """],
            ["Ha-man Dựng Mộc Hình Ðịnh Treo Cổ Mạc-đô-chê": """
                9 Ngày hôm ấy Ha-man ra về, tâm thần hớn hở và hân hoan.  Nhưng khi Ha-man thấy Mạc-đô-chê ở cổng hoàng cung, và thấy ông ấy không đứng dậy và cũng không run sợ trước mặt ông, Ha-man rất giận Mạc-đô-chê.  10 Tuy nhiên Ha-man cố nén giận và về nhà.  Sau đó ông mời các bạn của ông và gọi Xê-rếch vợ ông lại.  11 Ha-man kể cho họ nghe những vinh hoa phú quý của ông, số con cái ông có, những lần thăng quan tiến chức mà vua đã vinh thăng ông, thể nào vua đã cho ông thăng tiến hơn tất cả các triều thần và khanh tướng của vua.  12 Ha-man nói tiếp, “Ngay cả Hoàng Hậu Ê-xơ-tê cũng không mời ai ngoại trừ ta và vua đến dự tiệc do bà khoản đãi.  Ngày mai ta cũng được bà mời đến dự tiệc với vua nữa.  13 Tuy nhiên tất cả những điều đó đều chẳng có nghĩa lý gì, nếu ngày nào ta còn thấy tên Do-thái Mạc-đô-chê ngồi ở cổng hoàng cung.”
                14 Bấy giờ Xê-rếch vợ ông và các bạn ông nói với ông, “Hãy cho dựng một cây mộc hình cao hai mươi lăm thước, rồi sáng mai ông hãy xin vua cho treo cổ Mạc-đô-chê lên đó.  Xong rồi ông hãy vui vẻ đi dự tiệc với vua.”  Lời bàn đó đẹp lòng Ha-man, và ông truyền cho dựng ngay cây mộc hình ấy.

                """]
            ]),
        Chapter(6, passages: [
            ["Vua Tri Ơn Mạc-đô-chê": """
                1 Tối hôm đó vua ngủ không được; vua truyền lệnh mang các sách kỷ yếu và sách sử ký đến đọc cho vua nghe.  2 Người ta thấy trong đó có chép thể nào Mạc-đô-chê đã báo cáo âm mưu của Bích-than và Tê-rếch, hai quan thái giám của vua, những người có trách nhiệm canh giữ cung môn, đã âm mưu ám sát Vua A-ha-suê-ru.  3 Vua hỏi, “Mạc-đô-chê có được tưởng thưởng hay tuyên dương gì vì công trạng ấy chăng?”
                Các cận thần của vua đáp, “Ông ấy chẳng được gì cả.”
                4 Vua hỏi, “Ai đang ở ngoài nội điện?”
                Vả, bấy giờ Ha-man vừa bước vào tiền sảnh của nội điện để đến tâu với vua, xin phép treo cổ Mạc-đô-chê trên mộc hình ông đã dựng.  5 Vì thế các cận thần của vua tâu với vua, “Tâu, có Ha-man ở ngoài đó.  Ông ấy đang đứng ở sân chầu.”
                Vua phán, “Hãy truyền cho ông ấy vào.”
                6 Vậy Ha-man vào và vua nói với ông, “Người mà trẫm muốn tôn trọng thì phải làm gì cho người ấy?”
                Ha-man tự nhủ thầm, “Có ai mà vua muốn tôn trọng hơn ta chứ?”  7 Vì thế Ha-man tâu với vua, “Người mà hoàng thượng muốn tôn trọng thì xin hoàng thượng 8 cho mang lấy bộ triều phục của hoàng thượng mặc, con ngựa hoàng thượng cỡi, và vương miện hoàng thượng đội trên đầu đến.  9 Sau đó xin hoàng thượng truyền cho vị thượng quan được tôn trọng nhất, để vị ấy mặc bộ áo mão đó cho người được hoàng thượng muốn tôn trọng, rồi để vị ấy dắt con ngựa có người được hoàng thượng muốn tôn trọng cỡi, đi dạo khắp quảng trường ở kinh đô, và hô to trước mặt người ấy rằng: ‘Ðây là cách đãi ngộ cho người được vua muốn tôn trọng.’”
                10 Bấy giờ vua nói với Ha-man, “Hãy mau mau lấy bộ triều phục và ngựa, y như lời ngươi nói, mặc cho Mạc-đô-chê người Do-thái đang ngồi ở cổng hoàng cung.  Tất cả những gì ngươi nói, chớ bỏ sót điều nào.”
                11 Vậy Ha-man lãnh lấy bộ triều phục và ngựa.  Ông mặc bộ triều phục ấy cho Mạc-đô-chê, rồi dắt con ngựa có Mạc-đô-chê cỡi, đi dạo khắp quảng trường của kinh đô và hô to, “Ðây là cách đãi ngộ cho người được vua muốn tôn trọng.”
                12 Sau đó Mạc-đô-chê trở lại cổng hoàng cung, còn Ha-man thì vội vàng đi về nhà ông, lòng đầy sầu thảm và đầu trùm lại.  13 Ha-man thuật lại cho Xê-rếch vợ ông và cho các bạn ông về những gì đã xảy ra cho ông.  Các cố vấn của ông và Xê-rếch vợ ông nói với ông, “Nếu đó là Mạc-đô-chê, dòng dõi của dân Do-thái, thì hoạn lộ của ông đã bắt đầu suy bại rồi.  Ông sẽ không thắng nổi hắn đâu, nhưng ông chắc chắn sẽ thất bại trước mặt hắn.”
                14 Ðang khi họ còn nói chuyện với ông, các quan thái giám của vua đến mời Ha-man phải mau lẹ đến dự tiệc do Ê-xơ-tê đã chuẩn bị.

                """]
            ]),
        Chapter(7, passages: [
            ["Ha-man Bị Suy Bại": """
                1 Vậy vua và Ha-man đến dự tiệc do Hoàng Hậu Ê-xơ-tê thết đãi.  2 Vào ngày thứ hai, đang khi họ uống rượu, vua hỏi Ê-xơ-tê lần nữa, “Hoàng Hậu Ê-xơ-tê, khanh có thỉnh nguyện gì?  Trẫm sẽ ban cho.  Khanh muốn xin điều gì?  Dù đến phân nửa vương quốc của trẫm, trẫm cũng sẽ ban cho.”
                3 Bấy giờ Hoàng Hậu Ê-xơ-tê đáp, “Tâu hoàng thượng, nếu thần thiếp được ơn của hoàng thượng, và nếu đẹp lòng hoàng thượng, kính xin hoàng thượng giữ mạng sống của thần thiếp lại, đó là thỉnh nguyện của thần thiếp, và xin giữ mạng sống của dân tộc thần thiếp lại, đó là điều cầu xin của thần thiếp, 4 vì thần thiếp và dân tộc của thần thiếp đã bị bán để bị tiêu diệt, tàn sát, và tận diệt.  Nếu thần thiếp và dân tộc của thần thiếp phải bị bán để làm nam nữ nô lệ, thì thần thiếp chẳng dám nói gì, vì nỗi khổ như thế chẳng đáng để làm bận tâm đến hoàng thượng.”
                5 Bấy giờ Vua A-ha-suê-ru nói với Hoàng Hậu Ê-xơ-tê, “Kẻ đó là ai?  Nó ở đâu?  Kẻ nào dám cả gan làm như thế?”
                6 Ê-xơ-tê đáp, “Kẻ thù và kẻ nghịch đó chính là ông Ha-man gian ác này.”  Bấy giờ Ha-man khiếp sợ trước mặt vua và hoàng hậu.  7 Vua bừng bừng nổi giận, đứng lên, bỏ tiệc rượu, và bước ra vườn ngự uyển, nhưng Ha-man vẫn ở lại để van xin Hoàng Hậu Ê-xơ-tê cứu mạng, vì ông nhận thấy vua đã quyết định tiêu diệt ông.
                8 Khi vua từ vườn ngự uyển trở vào phòng tiệc, vua thấy Ha-man đang ngã mình trên trường kỷ nơi Ê-xơ-tê đang ngồi, vua nói, “Trong cung thất, ngay trước mặt ta, mà nó còn tính hãm hiếp hoàng hậu sao?”  Lời vừa ra khỏi miệng vua, người ta liền trùm mặt Ha-man lại.
                9 Bấy giờ Hạc-bô-na, một trong các thái giám đang hầu bên vua, nói, “Kìa, có cây mộc hình cao hai mươi lăm thước mà Ha-man đã dựng để treo cổ Mạc-đô-chê, người đã báo tin để cứu mạng vua, đang đứng sừng sững trong sân nhà Ha-man.”
                Vua phán, “Hãy treo cổ nó lên đó.”
                10 Vậy người ta treo cổ Ha-man trên mộc hình ông đã dựng để treo cổ Mạc-đô-chê.  Sau đó cơn giận của vua nguôi ngoai.

                """]
            ]),
        Chapter(8, passages: [
            ["Ê-xơ-tê Cứu Người Do-thái": """
                1 Trong chính ngày đó Vua A-ha-suê-ru ban cho Hoàng Hậu Ê-xơ-tê ngôi nhà của Ha-man, kẻ thù của người Do-thái; đồng thời Mạc-đô-chê cũng được triệu vào để ra mắt vua, vì Ê-xơ-tê đã tâu với vua về liên hệ giữa bà và ông ấy.  2 Bấy giờ vua cởi chiếc nhẫn có con dấu vua đã lấy lại nơi tay Ha-man và trao cho Mạc-đô-chê.  Thế là Ê-xơ-tê lập Mạc-đô-chê làm người quản cai mọi sự trong nhà của Ha-man.
                3 Kế đó Ê-xơ-tê tâu với vua.  Bà sấp mình nơi chân vua mà khóc và van nài, xin vua đẩy lui âm mưu thâm độc của Ha-man người A-ga-ghi, và kế hoạch ông ấy đã lập để hại người Do-thái.  4 Vua đưa cây phủ việt bằng vàng ra cho Ê-xơ-tê, 5 Ê-xơ-tê trỗi dậy và đứng trước mặt vua.  Bà nói, “Nếu đẹp lòng hoàng thượng, nếu thần thiếp được ơn của hoàng thượng, và nếu việc này được thấy là phải lẽ trước mặt hoàng thượng, kính xin hoàng thượng ban lệnh thu hồi những sắc chỉ mà Ha-man con của Ham-mê-đa-tha, người A-ga-ghi, đã viết ra để truyền lệnh tiêu diệt người Do-thái sống trong các tỉnh của hoàng thượng, 6 vì làm thể nào thần thiếp có thể chịu nổi khi nhìn thấy tai họa xảy đến cho dân tộc mình?  Hay làm thể nào thần thiếp có thể chịu nổi khi trông thấy cảnh đồng bào của mình bị tiêu diệt?”
                7 Bấy giờ Vua A-ha-suê-ru nói với Hoàng Hậu Ê-xơ-tê và với Mạc-đô-chê người Do-thái, “Này, trẫm đã ban cho Ê-xơ-tê ngôi nhà của Ha-man, và người ta đã treo hắn trên mộc hình rồi, vì hắn đã lập mưu để tiêu diệt dân Do-thái.  8 Bây giờ các khanh có thể nhân danh trẫm viết về việc dân Do-thái như thế nào tùy ý các khanh, sau đó niêm phong nó lại, rồi dùng chiếc nhẫn có ấn dấu của trẫm đóng vào, vì một khi sắc chỉ được nhân danh trẫm viết ra và dùng chiếc nhẫn có ấn dấu của trẫm đóng vào thì không thể thu hồi được.”
                9 Bấy giờ các ký lục của vua được triệu đến, vào ngày hai mươi ba tháng ba, tức tháng Si-van.  Một sắc chỉ theo lệnh của Mạc-đô-chê đã được viết ra, gởi cho người Do-thái và gởi cho các thống đốc, các tổng trấn, và các tỉnh trưởng ở các tỉnh, từ Ấn-độ cho đến Ê-thi-ô-pi, một trăm hai mươi bảy tỉnh, tỉnh nào theo chữ viết của tỉnh ấy, dân nào theo ngôn ngữ của dân ấy, và cũng gởi cho dân Do-thái theo chữ viết và ngôn ngữ của họ.  10 Ông nhân danh Vua A-ha-suê-ru viết các sắc chỉ ấy, rồi dùng ấn dấu của vua đóng vào.  Ðoạn những người đưa thư cỡi những ngựa nòi nhanh nhất của vua mang các sắc chỉ ấy cấp tốc ra đi.
                11 Nội dung các sắc chỉ ấy truyền rằng vua cho phép người Do-thái trong mỗi thành được quyền tụ họp lại để bảo vệ mạng sống mình; họ được quyền tiêu diệt, giết chết, và tận diệt bất cứ quân đội của dân nào hoặc tỉnh nào đến tấn công họ; họ được quyền đánh giết luôn vợ con và cướp lấy tài sản của những kẻ đó.  12 Lệnh ấy có hiệu lực trong một ngày, đó là ngày mười ba tháng mười hai, tức tháng A-đa, trong khắp các tỉnh của Vua A-ha-suê-ru.
                13 Bản sao của sắc chỉ ấy cũng được ban hành ở mỗi tỉnh dưới hình thức sắc lệnh, để công bố cho mọi dân tộc biết và đặc biệt là cho người Do-thái biết, hầu họ chuẩn bị sẵn sàng để báo trả những kẻ thù của họ.  14 Vậy những người đưa thư nhận lệnh vua, cỡi những ngựa nòi nhanh nhất của vua, cấp tốc mang các sắc chỉ ra đi.  Ngay tại Kinh Ðô Su-sa một chiếu chỉ về việc ấy cũng được ban hành.
                15 Khi Mạc-đô-chê từ trong hoàng cung đi ra, mình mặc triều phục màu tím và trắng, đầu đội mão triều lớn bằng vàng, bên ngoài khoác chiếc áo choàng màu tía làm bằng vải gai mịn, dân thành Su-sa trông thấy ông, họ cất tiếng reo hò và mừng rỡ.  16 Bấy giờ đối với người Do-thái, đó là dấu hiệu của sự sáng sủa và vui mừng, hân hoan và hãnh diện.  17 Trong mỗi tỉnh và mỗi thành, nơi nào lệnh của vua và sắc chỉ của vua đến, nơi đó người Do-thái hân hoan và mừng rỡ.  Họ mở tiệc ăn mừng và xem đó là một ngày phước hạnh.  Bấy giờ nhiều người trong các xứ tự nhận mình là người Do-thái, bởi vì nỗi sợ hãi người Do-thái đã giáng xuống trên họ.
                """]
            ]),
        Chapter(9, passages: [
            ["Những Kẻ Thù của Người Do-thái Bị Diệt": """
                1 Bấy giờ ngày mười ba tháng mười hai, tức tháng A-đa, đã đến, tức khi lệnh của vua và sắc chỉ của vua được đem ra thi hành.  Trong ngày những kẻ thù của người Do-thái chờ đợi để cướp giết họ, sự việc lại diễn biến ngược lại: người Do-thái đã lấn lướt trên những kẻ thù của họ.  2 Ở các thành trong tất cả các tỉnh của Vua A-ha-suê-ru, người Do-thái tụ họp nhau lại và tra tay trên những kẻ toan giết hại họ.   Không ai có thể chống cự nổi họ, bởi vì nỗi sợ hãi họ đã giáng xuống trên mọi dân tộc.  3 Tất cả các tỉnh trưởng của các tỉnh, các thống đốc, các tổng trấn, và các quan trong triều đều ủng hộ người Do-thái, bởi vì ai nấy đều nể sợ Mạc-đô-chê, 4 bởi vì Mạc-đô-chê đã trở thành người có quyền lực trong triều đình.  Danh tiếng ông được vang lừng khắp các tỉnh, vì Mạc-đô-chê trở thành một người càng ngày càng có thêm quyền lực.
                5 Vậy người Do-thái đã dùng gươm đánh hạ tất cả kẻ thù của họ.  Họ giết chết và tiêu diệt chúng.  Họ đã đối xử với những kẻ ghét họ theo ý họ muốn.  6 Trong Kinh Ðô Su-sa, người Do-thái đã giết chết và tiêu diệt năm trăm người.  7 Họ đã giết chết Pạc-san-đa-tha, Ðan-phôn, Át-pa-tha, 8 Pô-ra-tha, A-đa-lia, A-ri-đa-tha, 9 Pạc-mách-ta, A-ri-sai, A-ri-đai, và Va-giê-xa-tha, 10 tức mười con trai của Ha-man con trai Ham-mê-đa-tha, người A-ga-ghi, kẻ thù của người Do-thái; nhưng họ không đụng đến tài sản của chúng.
                11 Ngày hôm ấy người ta báo cáo cho vua số người bị giết ở Kinh Ðô Su-sa.  12 Vua nói với Hoàng Hậu Ê-xơ-tê, “Trong Kinh Ðô Su-sa người Do-thái đã giết chết năm trăm người và mười con trai của Ha-man.  Còn trong các tỉnh của trẫm thì chưa biết họ đã làm gì?  Bây giờ khanh còn thỉnh nguyện gì nữa chăng?  Trẫm sẽ ban cho khanh.  Khanh muốn xin điều gì nữa không?  Trẫm sẽ cho khanh được toại nguyện.”
                13 Ê-xơ-tê tâu, “Nếu đẹp lòng hoàng thượng, xin hoàng thượng cho phép người Do-thái được làm theo sắc chỉ hôm nay thêm ngày mai nữa tại Kinh Ðô Su-sa, và xin hoàng thượng cho phép họ được treo xác của mười con trai Ha-man trên các mộc hình.”  14 Vua bèn truyền lịnh cho thi hành y như vậy.  Một sắc lệnh được ban ra và mười con trai của Ha-man bị treo xác.  15 Người Do-thái ở Su-sa cũng tập họp lại vào ngày mười bốn tháng A-đa và đánh giết thêm ba trăm người nữa tại Su-sa; nhưng họ không đụng đến tài sản của chúng.
                16 Lúc ấy những người Do-thái khác ở trong các tỉnh của vua cũng họp nhau lại để bảo vệ mạng sống của họ và được giải cứu khỏi những kẻ thù của họ.  Họ giết chết bảy mươi lăm ngàn kẻ ghét họ; nhưng họ không đụng tay đến tài sản của chúng.  17 Họ làm điều ấy vào ngày mười ba tháng A-đa, còn ngày mười bốn họ nghỉ và biến ngày ấy thành một ngày ăn mừng và hoan hỉ.

                """],
            ["Lập Lễ Pu-rim": """
                18 Tuy nhiên người Do-thái ở Su-sa đã tập họp nhau vào ngày mười ba và mười bốn, nên họ nghỉ ngày mười lăm và biến ngày ấy thành một ngày ăn mừng và hoan hỉ.  19 Vì thế những người Do-thái sống trong các làng mạc, tức trong những thành không tường bao quanh, đã chọn ngày mười bốn của tháng A-đa làm ngày hoan hỉ và ăn mừng, một ngày gởi các thực phẩm làm quà cho nhau.
                20 Mạc-đô-chê ghi lại những điều ấy, rồi gởi thư đến tất cả người Do-thái sống trong các tỉnh của Vua A-ha-suê-ru, cả gần lẫn xa, 21 truyền cho họ phải chọn ngày mười bốn của tháng A-đa và ngày mười lăm của tháng ấy làm ngày lễ hằng năm, 22 tức biến những ngày ấy thành những ngày kỷ niệm người Do-thái được giải thoát khỏi các kẻ thù của họ, đồng thời cũng xem tháng đó là tháng đã biến đổi tình cảnh của họ từ sầu thảm thành vui mừng, từ than khóc thành ngày phước hạnh; và họ phải biến hai ngày ấy thành những ngày ăn mừng và hoan hỉ, những ngày để gởi các thực phẩm làm quà cho nhau và tặng quà cho người nghèo.  23 Vậy người Do-thái ghi nhận điều ấy và biến hai ngày đó thành một thông lệ thường niên, rồi họ khởi sự làm y như Mạc-đô-chê đã viết thư căn dặn họ.  24 Nguyên do là Ha-man con của Ham-mê-đa-tha, người A-ga-ghi, kẻ thù của người Do-thái, đã lập mưu chống người Do-thái, định tiêu diệt họ.  Ông ấy đã cho gieo Pu-rơ, tức gieo thăm, để tàn sát và tiêu diệt họ; 25 nhưng khi Ê-xơ-tê ra mắt vua, vua đã truyền chiếu chỉ rằng mưu đồ gian ác của ông ấy phải giáng xuống trên đầu ông ấy, và ông ấy cùng các con trai ông ấy đã bị treo trên mộc hình.  26 Vì thế những ngày ấy được gọi là Pu-rim, ra từ chữ Pu-rơ.
                Thế thì vì mọi điều đã viết trong văn thư ấy, vì những gì họ đã chứng kiến, và vì những gì đã xảy đến cho họ, 27 người Do-thái đã thiết lập và chấp nhận một thông lệ thường niên cho họ, cho con cháu họ, và cho tất cả những ai gia nhập vào cộng đồng của họ rằng hằng năm họ không được bỏ qua nhưng phải giữ hai ngày lễ ấy, như đã viết trong văn thư, theo ngày giờ đã ấn định.  28 Những ngày ấy phải được ghi nhớ và phải giữ trải qua mọi thế hệ, trong mỗi gia đình, mỗi tỉnh, và mỗi thành.  Người Do-thái không được quên những ngày lễ Pu-rim này, và con cháu họ cũng không được ngưng kỷ niệm những ngày lễ ấy.
                29 Hoàng Hậu Ê-xơ-tê con gái của A-bi-ha-in cùng với Mạc-đô-chê người Do-thái đã lấy thẩm quyền của họ xác nhận bức thư thứ hai ấy về Lễ Pu-rim.  30 Bản sao bức thư ấy đã được gởi đến tất cả người Do-thái trong một trăm hai mươi bảy tỉnh của Vua A-ha-suê-ru, cầu chúc họ được hòa bình thịnh vượng và an ninh, 31 và ra lệnh rằng những ngày Lễ Pu-rim này phải được giữ theo ngày giờ đã ấn định, y như Mạc-đô-chê người Do-thái và Hoàng Hậu Ê-xơ-tê đã truyền cho người Do-thái, theo tập quán mà họ đã lập cho họ và cho con cháu họ về việc kiêng ăn và than khóc.
                32 Lệnh của Hoàng Hậu Ê-xơ-tê đã biến việc giữ Lễ Pu-rim này thành một lễ cố định, và điều ấy đã được ghi vào sách.

                """]
            ]),
        Chapter(10, passages: [
            ["Lời Kết": """
                1 Vua A-ha-suê-ru bắt dân trong các xứ và các hải đảo xa xăm phải nộp thuế.  2 Tất cả các công việc để biểu dương uy quyền và thế lực của vua, cùng mọi điều vua đã làm để khiến cho Mạc-đô-chê được tôn trọng, tức những lần vua thăng chức cho ông, há không phải chúng đã được chép trong các sách Sử Ký của Các Vua Mê-đi và Ba-tư sao?  3 Thật vậy Mạc-đô-chê người Do-thái được ban cho quyền hành đứng hàng thứ nhì sau Vua A-ha-suê-ru.  Ông là người có quyền giữa vòng người Do-thái và luôn được đông đảo đồng bào ông thương mến, bởi vì ông luôn làm những gì có lợi cho dân tộc ông, và lên tiếng binh vực cho quyền lợi của đồng bào ông. 
                """]
            ])
    ]
    
}

