
class ICoRinhTo: Book {
    
    override init() {
        super.init()
        title = "I CÔ-RINH-TÔ"
        chapters = allChapters
        allChapters.forEach{ $0.book = self }
    }
    
    var allChapters: [Chapter] = [
        Chapter(1, passages: [
            ["Lời Chào Thăm": """
                1 Phao-lô, do ý muốn Ðức Chúa Trời được gọi làm sứ đồ của Ðức Chúa Jesus Christ, và Sốt-then, anh em chúng ta, 2 kính gởi hội thánh của Ðức Chúa Trời tại Cô-rinh-tô, những người được thánh hóa trong Ðức Chúa Jesus Christ, được gọi là thánh đồ, cùng gởi cho mọi người ở mọi nơi đang kêu cầu danh Chúa chúng ta, là Ðức Chúa Jesus Christ, Chúa của họ và Chúa của chúng ta. 3 Nguyện xin ân sủng và bình an từ Ðức Chúa Trời, Cha chúng ta, và từ Ðức Chúa Jesus Christ, Chúa chúng ta, đến với anh chị em.

                """],
            ["Phước Hạnh Trong Chúa": """
                4 Tôi luôn cảm tạ Ðức Chúa Trời của tôi về anh chị em, vì ân sủng của Ðức Chúa Trời đã được ban cho anh chị em trong Ðức Chúa Jesus Christ.  5 Vì nhờ ở trong Ngài anh chị em đã trở nên giàu có đủ mọi mặt, cả lời nói lẫn tri thức, 6 ngay cả lời chứng về Ðấng Christ cũng đã được vững lập giữa anh chị em, 7 khiến anh chị em không thiếu bất cứ ân tứ thuộc linh nào, trong khi chờ đợi sự hiện đến của Ðức Chúa Jesus Christ, Chúa chúng ta, 8 Ðấng sẽ làm cho anh chị em được vững mạnh đến cuối cùng, để anh chị em được toàn vẹn trong ngày của Ðức Chúa Jesus Christ, Chúa chúng ta.  9 Ðức Chúa Trời là Ðấng thành tín; Ngài đã gọi anh chị em vào sự hiệp thông với Con Ngài, là Ðức Chúa Jesus Christ, Chúa chúng ta.

                """],
            ["Khuyên Phải Hiệp Một": """
                10 Thưa anh chị em, nhân danh Ðức Chúa Jesus Christ, Chúa chúng ta, tôi nài khuyên anh chị em hãy đồng tâm nhất trí với nhau, đừng để có sự chia rẽ giữa anh chị em, nhưng hãy hiệp một, đồng lòng hiệp ý với nhau.
                11 Vì thưa anh chị em của tôi, những người trong gia đình của Cơ-lô-ê đã báo cho tôi hay rằng giữa anh chị em đang có sự tranh cãi với nhau.  12 Ðiều tôi muốn nói là thế nầy: Người nào trong anh chị em cũng nói, “Tôi là người của Phao-lô,” hoặc “Tôi là người của A-pô-lô,” hoặc “Tôi là người của Sê-pha,” hoặc “Tôi là người của Ðấng Christ.”  13 Có phải Ðấng Christ đã bị chia cắt sao?  Có phải Phao-lô đã chịu đóng đinh trên cây thập tự thay cho anh chị em sao?  Hay là anh chị em đã nhân danh Phao-lô mà chịu phép báp-têm sao?
                14 Tôi cảm tạ Ðức Chúa Trời vì tôi không làm báp-têm cho ai trong anh chị em, ngoại trừ Cơ-rít-pu và Gai-út, 15 để không ai có thể nói rằng họ đã nhân danh tôi mà chịu báp-têm.  16 À, tôi cũng đã làm báp-têm cho những người trong gia đình của Tê-pha-na.  Ngoài ra tôi không nhớ tôi đã làm báp-têm cho ai khác.  17 Vì Ðấng Christ không sai tôi đi làm báp-têm, nhưng để giảng Tin Mừng, và không dùng những lời lẽ khôn khéo để giảng, kẻo quyền năng thể hiện qua sự chết của Ðấng Christ trên thập tự giá trở nên vô hiệu chăng.

                """],
            ["Ðấng Christ Là Quyền Phép và Sự Khôn Ngoan của Ðức Chúa Trời": """
                18 Vì sứ điệp về thập tự giá bị xem là rồ dại đối với những người hư mất, nhưng đối với chúng ta, những người được cứu, thì đó là quyền phép của Ðức Chúa Trời, 19 như có chép rằng,
                “Ta sẽ hủy bỏ sự khôn ngoan của người khôn ngoan;
                Ta sẽ loại trừ sự thông thái của người thông thái.”
                20 Người khôn ngoan ở đâu?  Người học thức ở đâu?  Nhà hùng biện của đời nầy ở đâu?  Chẳng phải Ðức Chúa Trời đã làm cho sự khôn ngoan của thế gian trở nên rồ dại sao?  21 Vì thế gian không chịu nhận biết Ðức Chúa Trời bằng sự khôn ngoan của mình, nên trong sự khôn ngoan của Ðức Chúa Trời, Ðức Chúa Trời đã vui lòng dùng sự rao giảng rồ dại của chúng ta để cứu những người tin.
                22 Trong khi người Do-thái đòi hỏi dấu lạ, người Hy-lạp tìm kiếm sự khôn ngoan, 23 thì chúng ta rao giảng Ðấng Christ chịu đóng đinh trên thập tự giá; đó là điều người Do-thái cho là ô nhục, còn các dân ngoại cho là điên rồ, 24 nhưng đối với những người được kêu gọi, bất luận là người Do-thái hay người Hy-lạp, thì Ðấng Christ là quyền phép của Ðức Chúa Trời và sự khôn ngoan của Ðức Chúa Trời, 25 vì sự rồ dại của Ðức Chúa Trời khôn hơn sự khôn ngoan của loài người, và sự yếu đuối của Ðức Chúa Trời mạnh hơn sự mạnh mẽ của loài người.
                26 Xin anh chị em hãy nghĩ lại xem, lúc anh chị em được gọi, trong anh chị em chẳng có nhiều người khôn ngoan theo tiêu chuẩn đời nầy, chẳng có nhiều người quyền thế, và chẳng có nhiều người quý tộc.  27 Nhưng Ðức Chúa Trời đã chọn những gì thế gian cho là rồ dại để làm hổ thẹn những kẻ khôn ngoan; Ðức Chúa Trời đã chọn những gì thế gian cho là yếu đuối để làm hổ thẹn những kẻ mạnh mẽ.  28 Ðức Chúa Trời đã chọn những gì thế gian cho là thấp kém, đáng khinh, và không ra gì, để vô hiệu hóa những gì thế gian cho là có giá trị, 29 hầu không người nào có thể tự phụ trước mặt Ðức Chúa Trời.
                
                30 Nhờ Ngài anh chị em được ở trong Ðức Chúa Jesus Christ, Ðấng từ Ðức Chúa Trời đến, Ðấng đã làm cho chúng ta trở nên khôn ngoan, được kể là công chính, được thánh hóa, và được cứu chuộc, 31 thật phù hợp với lời đã chép rằng,
                “Ai muốn tự hào, hãy tự hào trong Chúa.”

                """]
            ]),
        Chapter(2, passages: [
            ["Giảng về Chúa Chịu Nhục Hình trên Thập Tự Giá": """
                1 Thưa anh chị em, lúc tôi đến với anh chị em, tôi không đến để rao giảng huyền nhiệm của Ðức Chúa Trời cho anh chị em bằng những lời lẽ cao siêu hoặc uyên bác.  2 Vì tôi đã quyết định rằng, ở giữa anh chị em, tôi không biết gì ngoài Ðức Chúa Jesus Christ là Ðấng đã chịu đóng đinh trên thập tự giá.  3 Tôi ở giữa anh chị em có vẻ yếu kém, sợ sệt, và run rẩy.  4 Lời giảng của tôi và cách giảng dạy của tôi không dựa vào những lời lẽ khôn khéo mang tính cách thuyết phục, nhưng để thể hiện quyền năng của Ðức Thánh Linh, 5 hầu đức tin anh chị em không đặt trên sự khôn ngoan của loài người, nhưng trên quyền năng của Ðức Chúa Trời.

                """],
            ["Sự Khôn Ngoan của Ðức Chúa Trời": """
                6 Tuy nhiên giữa những tín hữu đã trưởng thành, chúng tôi vẫn giảng sự khôn ngoan, nhưng không phải sự khôn ngoan của đời nầy, cũng không phải sự khôn ngoan của những nhà lãnh đạo đời nầy, những người sẽ thành hư không; 7 nhưng chúng tôi rao giảng sự khôn ngoan của Ðức Chúa Trời, là huyền nhiệm vốn được giữ kín, mà Ðức Chúa Trời đã định trước từ muôn đời cho vinh hiển của chúng ta.  8 Ðó là điều không nhà lãnh đạo nào ở đời nầy biết được, vì nếu họ biết, họ đã không đóng đinh Chúa vinh hiển của chúng ta trên thập tự giá, 9 như có chép rằng,
                “Những điều mắt chưa thấy, tai chưa nghe, và lòng chưa nghĩ đến,
                Ðức Chúa Trời đã chuẩn bị những điều ấy cho những kẻ yêu kính Ngài.”
                10 Ðức Chúa Trời đã bày tỏ những điều ấy cho chúng ta qua Ðức Thánh Linh, vì Ðức Thánh Linh dò thấu mọi sự, ngay cả những gì sâu nhiệm của Ðức Chúa Trời.  11 Vì ai biết được những gì trong lòng người ta, ngoại trừ tâm linh của người ấy?  Cũng vậy, không ai biết được những gì trong lòng Ðức Chúa Trời, ngoại trừ Ðức Thánh Linh của Ðức Chúa Trời.
                12 Bây giờ chúng ta đã nhận lãnh, không phải linh của thế gian, nhưng Ðức Thánh Linh đến từ Ðức Chúa Trời, để chúng ta có thể nhận biết những ân tứ Ðức Chúa Trời ban cho chúng ta.  13 Chúng ta nói những điều ấy không dựa vào những lời lẽ khôn ngoan do loài người dạy bảo, nhưng dựa vào sự dạy dỗ của Ðức Thánh Linh, dùng những lời lẽ thuộc linh giãi bày những việc thuộc linh.
                14 Một người sống theo bản tính tự nhiên sẽ không nhận biết những gì thuộc về Ðức Thánh Linh của Ðức Chúa Trời, vì người ấy sẽ cho những điều đó là rồ dại; người ấy không thể biết được những điều đó, vì chúng phải được nhận thức theo cách thuộc linh.  15 Một người thuộc linh có thể nhận biết mọi sự, còn chính người ấy, không ai có thể nhận biết chính xác được.
                16 “Vì ai biết được tâm trí của Chúa, để chỉ bảo Ngài?”
                Nhưng chúng ta có tâm trí của Ðấng Christ.

                """]
            ]),
        Chapter(3, passages: [
            ["Những Ðầy Tớ Chúa": """
                1 Thưa anh chị em, tôi không thể nói với anh chị em như nói với những người thuộc linh, nhưng như với những người xác thịt, như với những trẻ sơ sinh trong Ðấng Christ.  2 Tôi cho anh chị em uống sữa chứ không cho thức ăn đặc, vì anh chị em không chịu nổi.  Ngay đến bây giờ anh chị em cũng chưa chịu nổi,  3 vì anh chị em vẫn còn xác thịt, bởi giữa anh chị em đang có sự ganh tị và tranh cãi.  Chẳng phải anh chị em là người xác thịt và đối xử với nhau như người đời sao?  4 Vì khi trong anh chị em có người nói, “Tôi là người của Phao-lô,” và người khác nói, “Tôi là người của A-pô-lô,” anh chị em chẳng phải như người đời sao?
                5 Vậy A-pô-lô là gì?  Phao-lô là gì?  Chúng tôi chẳng qua là các đầy tớ Chúa, mà qua chức vụ của chúng tôi anh chị em đã tin Ngài, theo ơn Chúa đã ban cho mỗi chúng tôi.  6 Tôi đã trồng, A-pô-lô đã tưới, nhưng Ðức Chúa Trời đã làm cho lớn lên.  7 Thế thì người trồng và kẻ tưới đều chẳng là gì cả, nhưng chỉ Ðức Chúa Trời, Ðấng làm cho lớn lên, mà thôi.  8 Người trồng và kẻ tưới đều như nhau; mỗi người sẽ nhận phần thưởng tùy theo công lao khó nhọc của mình.  9 Vì chúng tôi chỉ là bạn đồng lao cùng làm đầy tớ của Ðức Chúa Trời, còn anh chị em mới là ruộng của Ðức Chúa Trời, nhà của Ðức Chúa Trời.
                10 Theo ơn Ðức Chúa Trời ban cho tôi, tôi đã đặt nền như một thợ xây dựng khôn ngoan, và người khác đã xây lên trên.  Nhưng mỗi người phải cẩn thận về những gì mình xây trên nền ấy.  11 Vì không ai có thể đặt một nền khác hơn nền đã được đặt, nền đó là Ðức Chúa Jesus Christ.  12 Nếu ai lấy vàng, bạc, đá quý, gỗ, cỏ khô, rơm rạ xây trên nền ấy, 13 công việc của mỗi người sẽ bị lộ ra.  Ngày phán xét sẽ rõ ràng tất cả, bởi vì lửa sẽ bày tỏ ra.  Giá trị công việc của mỗi người như thế nào, lửa sẽ thử luyện và cho biết kết quả.  14 Nếu công trình xây dựng của ai còn lại, người ấy sẽ lãnh thưởng.  15 Nếu công việc của ai bị thiêu hủy, người ấy phải chấp nhận sự mất mác, còn chính người ấy sẽ được cứu, nhưng dường như qua lửa.

                """],
            ["Tôi Con Chúa Là Ðền Thờ": """
                16 Anh chị em chẳng biết rằng anh chị em là đền thờ của Ðức Chúa Trời, và Ðức Thánh Linh của Ðức Chúa Trời đang ngự trong anh chị em sao?  17 Nếu ai phá hủy đền thờ của Ðức Chúa Trời, Ðức Chúa Trời sẽ phá hủy kẻ ấy, vì đền thờ của Ðức Chúa Trời là thánh, mà chính anh chị em là đền thờ.
                18 Ðừng tự dối mình.  Nếu ai trong anh chị em nghĩ mình là người khôn ngoan theo đời nầy, hãy trở nên một kẻ rồ dại, để có thể trở nên khôn ngoan.  19 Vì sự khôn ngoan của đời nầy là rồ dại đối với Ðức Chúa Trời, vì có lời chép rằng,
                “Chúa bắt lấy những người khôn ngoan trong chính mưu mô của họ.”
                20 Lại rằng,
                “Chúa biết rõ mọi tư tưởng của những người khôn ngoan;
                Chúng chỉ là hư ảo.”
                21 Vậy xin đừng ai cậy vào loài người mà tự phụ, vì mọi sự đều thuộc về anh chị em, 22 bất kể Phao-lô, hay A-pô-lô, hay Sê-pha, hay thế gian, hay sự sống, hay sự chết, hay những việc hiện tại, hay những việc tương lai, tất cả đều thuộc về anh chị em, 23 và anh chị em thuộc về Ðấng Christ, và Ðấng Christ thuộc về Ðức Chúa Trời.

                """]
            ]),
        Chapter(4, passages: [
            ["Chức Vụ của Các Sứ Ðồ": """
                1 Vậy mọi người nên xem chúng tôi như những đầy tớ của Ðấng Christ và những người quản lý các huyền nhiệm của Ðức Chúa Trời.  2 Vả lại, điều đòi hỏi nơi người quản lý là đáng tin cậy.
                3 Về phần tôi, dù tôi bị anh chị em xét đoán hay bị tòa án đời nầy xét đoán thì điều đó cũng chẳng quan trọng gì.  Thật ra tôi cũng không xét đoán chính mình.  4 Vì tôi biết tôi không làm gì sai, nhưng không vì thế mà tôi được xem là công chính, vì còn Chúa là Ðấng sẽ xét đoán tôi.  5 Vậy xin anh chị em đừng xét đoán quá sớm trước khi Chúa đến, vì khi Chúa đến, Ngài sẽ đưa ra ánh sáng những gì còn bị che giấu trong bóng tối và sẽ phơi bày những động cơ thầm kín trong lòng người ra.  Bấy giờ mỗi người sẽ nhận lãnh sự khen ngợi tương xứng của Ðức Chúa Trời.
                6 Thưa anh chị em, vì lợi ích của anh chị em, tôi áp dụng những điều nầy cho tôi và cho A-pô-lô, để anh chị em có thể học nơi chúng tôi câu nầy, “Ðừng vượt ra ngoài những gì đã chép,” hầu không ai sinh lòng kiêu ngạo, kẻo sẽ ủng hộ người nầy mà chống lại người kia.  7 Vì ai thấy bạn có gì khác biệt hơn người khác chăng?  Có gì bạn có mà không do đã nhận lãnh chăng?  Vậy nếu bạn đã nhờ nhận lãnh mà có, tại sao bạn lại tự hào như thể không hề nhận lãnh điều gì vậy?
                8 Anh chị em đã đầy đủ rồi, anh chị em đã giàu có rồi, anh chị em đã làm vua rồi, không cần chúng tôi.  Ước gì anh chị em được thật sự làm vua để chúng tôi cũng được trị vì chung với anh chị em!
                9 Vì tôi nghĩ rằng Ðức Chúa Trời đã phô bày chúng tôi là các sứ đồ vào hạng chót hết, như những kẻ bị tuyên án tử hình, vì chúng tôi đã trở thành trò cười cho thế gian, cho cả thiên sứ và loài người.  10 Chúng tôi là những kẻ rồ dại vì cớ Ðấng Christ, còn anh chị em được khôn ngoan trong Ðấng Christ.  Chúng tôi yếu kém, còn anh chị em mạnh mẽ.  Anh chị em được tôn trọng, còn chúng tôi bị khinh khi.  11 Cho đến giờ nầy chúng tôi vẫn còn bị khi đói khi khát, chúng tôi không đủ áo quần để thay đổi, thường bị đánh đập, và sống đời phiêu bạt không nhà.  12 Chúng tôi phải lao động vất vả bằng đôi tay mình để sống.  Khi bị mắng nhiếc, chúng tôi chúc phước; khi bị bắt bớ, chúng tôi cam chịu; 13 khi bị vu khống, chúng tôi đáp lại ôn tồn.  Chúng tôi đã trở thành như rác rến của thế gian, như đồ phế thải của mọi người cho đến bây giờ.

                """],
            ["Lời Nghiêm Trách": """
                14 Tôi viết những điều nầy không phải để làm cho anh chị em xấu hổ, nhưng để khuyên anh chị em như những đứa con yêu dấu của tôi.  15 Cho dù anh chị em có mười ngàn người hướng dẫn trong Ðấng Christ đi nữa, anh chị em cũng không có nhiều cha, vì tôi đã sinh anh chị em ra trong Ðức Chúa Jesus Christ bằng Tin Mừng.  16 Vậy tôi nài khuyên anh chị em, hãy bắt chước tôi.
                17 Vì lý do đó tôi sai Ti-mô-thê, con yêu quý và trung thành của tôi trong Chúa, đến để nhắc nhở anh chị em về đường lối của tôi trong Ðức Chúa Jesus Christ, đó là đường lối tôi đã dạy trong mỗi hội thánh ở khắp nơi.  18 Có mấy người trong anh chị em nghĩ rằng tôi sẽ không đến với anh chị em, nên đã lên mình kiêu ngạo.  19 Nhưng nếu Chúa muốn, không bao lâu nữa tôi sẽ đến với anh chị em.  Lúc ấy không những tôi muốn xem những kẻ đã lên mình kiêu ngạo đó nói năng ra sao, mà còn muốn biết họ dựa vào quyền năng nào nữa, 20 vì vương quốc Ðức Chúa Trời không dựa vào lời nói, nhưng dựa vào quyền năng.  21 Anh chị em muốn gì đây?  Anh chị em muốn tôi cầm roi đến hay đến với tình thương và một tinh thần dịu dàng?

                """]
            ]),
        Chapter(5, passages: [
            ["Sự Loạn Luân Trong Hội Thánh": """
                1 Tôi đã nghe báo rằng giữa anh chị em có sự gian dâm, một sự gian dâm mà ngay cả giữa vòng người ngoại cũng không có như vậy: có kẻ đã ăn nằm với vợ kế của cha mình.  2 Thế mà anh chị em còn lên mình kiêu ngạo!  Lẽ ra anh chị em phải buồn rầu hầu loại trừ kẻ làm điều loạn luân đó khỏi giữa anh chị em mới đúng.
                3 Về phần tôi, tuy vắng mặt trong thân xác nhưng hiện diện bằng tinh thần; và như thể tôi đã hiện diện, tôi tuyên án kẻ làm việc loạn luân ấy.  4 Nhân danh Ðức Chúa Jesus, Chúa chúng ta, -khi anh chị em họp lại với nhau, có tôi hiện diện với anh chị em bằng tinh thần, cùng với quyền năng của Ðức Chúa Jesus, Chúa chúng ta,- 5 anh chị em hãy phó người ấy cho Sa-tan để nó hủy diệt xác thịt, hầu tâm linh người ấy có thể được cứu trong ngày của Ðức Chúa Jesus.
                6 Ðiều anh chị em khoe khoang chẳng có gì tốt đẹp.  Anh chị em không biết rằng một chút men làm dậy cả đống bột sao?   7 Hãy loại sạch men cũ, để anh chị em thành một đống bột mới, như anh chị em là bột không men, vì Ðấng Christ là Con Chiên của Lễ Vượt Qua đã được dâng làm con vật hiến tế cho chúng ta rồi.  8 Thế thì chúng ta hãy ăn mừng thánh lễ, không với men cũ, không với men hiểm ác và gian tà, nhưng với bánh không men của sự ngay thật và chân thành.
                9 Trong thư tôi viết cho anh chị em, tôi có dặn đừng giao tiếp với những kẻ gian dâm.  10 Tôi không có ý nói phải đoạn giao với những kẻ gian dâm trong thế gian nầy, hay với những kẻ tham lam và trộm cướp, hay với những kẻ thờ thần tượng đâu, vì nếu vậy thì anh chị em phải ra khỏi thế gian nầy.  11 Nhưng ý tôi viết cho anh chị em là đừng giao tiếp với những người nào được gọi là anh chị em nhưng gian dâm, tham lam, thờ thần tượng, chưởi rủa, say sưa, hoặc lừa đảo; đừng ăn chung với những người như thế.
                12 Xét xử những người ngoài nào phải là việc của tôi sao?  Không phải anh chị em xét xử những người trong hội thánh sao?  13 Những người ngoài, Ðức Chúa Trời sẽ xét xử.  Hãy loại bỏ kẻ tội lỗi ra khỏi anh chị em.

                """]
            ]),
        Chapter(6, passages: [
            ["Tín Hữu Kiện Cáo Nhau": """
                1 Khi ai trong anh chị em có việc tranh chấp với người khác, sao người ấy dám đưa sự việc ra trước những người không tin kính Chúa để họ xét xử, nhưng không đưa ra trước các thánh đồ?  2 Hay anh chị em không biết rằng các thánh đồ sẽ xét xử thế gian sao?  Nếu thế gian sẽ bị xét xử bởi anh chị em, anh chị em không đủ khả năng xét xử những việc nhỏ nhặt giữa nhau sao?  3 Anh chị em không biết rằng chúng ta sẽ xét xử các thiên sứ, huống chi những việc thuộc về đời nầy sao?  4 Khi có những vụ tranh chấp thuộc đời nầy, sao anh chị em lại chỉ định những người không được hội thánh kính trọng đứng ra xét xử?  5 Tôi nói điều ấy để anh chị em xấu hổ.  Chẳng lẽ giữa vòng anh chị em không ai đủ khôn ngoan để phân xử những vụ tranh chấp giữa nhau sao?  6 Thế thì tại sao anh chị em lại kiện cáo anh chị em mình trước mặt những kẻ chẳng tin như thế?
                7 Thật vậy chỉ việc kiện cáo nhau đủ cho thấy anh chị em đã thất bại rồi.  Sao chẳng thà chịu bị đối xử bất công đi?  Sao chẳng thà chịu bị lừa gạt đi?  8 Nhưng chính anh chị em đã bất công, lừa gạt, và làm như thế đối với anh chị em mình kia mà.  9 Hay là anh chị em không biết rằng những kẻ bất chính sẽ không được thừa hưởng vương quốc Ðức Chúa Trời sao?  Ðừng tự dối mình!  Những kẻ gian dâm, những kẻ thờ thần tượng, những kẻ ngoại tình, những người nam làm điếm, những kẻ đồng tính luyến ái, 10 những kẻ trộm cắp, những kẻ tham lam, những kẻ say sưa, những kẻ chưởi rủa, và những kẻ lừa đảo đều sẽ không được thừa hưởng vương quốc Ðức Chúa Trời.  11 Ðây là những điều trước kia một số người trong anh chị em cũng đã như thế, nhưng bây giờ anh chị em đã được thanh tẩy, anh chị em đã được thánh hóa, anh chị em đã được xưng công chính trong danh Ðức Chúa Jesus Christ và trong Ðức Thánh Linh của Ðức Chúa Trời chúng ta rồi.

                """],
            ["Khuyên Dùng Thân Thể Làm Vinh Hiển Ðức Chúa Trời": """
                12 Tôi được phép làm mọi sự, nhưng không phải mọi sự đều có ích.  Tôi được phép làm mọi sự, nhưng tôi sẽ không để sự gì làm chủ tôi.  13 Thức ăn dành cho bụng, bụng dành cho thức ăn, nhưng Ðức Chúa Trời sẽ hủy diệt cái nọ và cái kia.  Thân thể không phải để cho sự gian dâm, nhưng cho Chúa, và Chúa cho thân thể.  14 Ðức Chúa Trời đã làm cho Chúa sống lại, Ngài cũng sẽ làm cho chúng ta sống lại bởi quyền năng Ngài.  15 Anh chị em không biết rằng thân thể anh chị em là chi thể của Ðấng Christ sao?  Vậy tôi có nên lấy chi thể của Ðấng Christ làm thành chi thể của đĩ điếm chăng?  Không bao giờ!  16 Anh chị em có biết rằng hễ ai kết hợp với đĩ điếm thì trở nên một thân với nó chăng?  Vì có lời chép rằng,
                “Hai người sẽ trở nên một thịt.”
                17 Nhưng ai kết hiệp với Chúa thì trở nên một tâm linh với Ngài.  18 Hãy tránh sự gian dâm.  Mọi tội người ta phạm đều ở ngoài thân thể, nhưng kẻ gian dâm thì phạm đến chính thân thể mình.
                19 Anh chị em không biết rằng thân thể anh chị em là đền thờ của Ðức Thánh Linh, Ðấng đang ngự trong anh chị em, Ðấng Ðức Chúa Trời ban cho anh chị em, và anh chị em không còn thuộc về chính mình nữa sao?  20 Vì anh chị em đã được mua bằng giá rất cao rồi; vậy hãy lấy thân thể mình làm vinh hiển Ðức Chúa Trời.

                """]
            ]),
        Chapter(7, passages: [
            ["Giải Ðáp Thắc Mắc về Vấn Ðề Hôn Nhân": """
                1 Bây giờ tôi xin đề cập đến những vấn đề anh chị em đã viết để hỏi tôi, tức vấn đề về đàn ông không đụng đến đàn bà là tốt.  2 Tuy nhiên để tránh sự gian dâm, mỗi người nam nên có vợ, và mỗi người nữ nên có chồng.  3 Chồng phải làm tròn bổn phận đối với vợ, và vợ phải làm tròn bổn phận đối với chồng.  4 Vợ không có quyền làm chủ thân thể mình nhưng là chồng.  Cũng vậy chồng không có quyền làm chủ thân thể mình nhưng là vợ.  5 Vợ chồng đừng từ chối nhau, trừ khi hai người đồng ý dành một thời gian để dốc lòng cầu nguyện, sau đó hai người hãy ăn ở lại với nhau, kẻo khi anh chị em không tự chế nổi, Sa-tan sẽ cám dỗ anh chị em.  6 Ðiều tôi nói đây là sự nhân nhượng, chứ không phải mệnh lệnh.  7 Tôi mong tất cả quý ông đều như tôi; nhưng mỗi người được Ðức Chúa Trời ban cho mỗi ơn riêng, người được ơn nầy, kẻ được ơn khác.
                8 Ðối với những người chưa lập gia đình và những người đang ở góa, tôi xin đề nghị rằng: nếu họ cứ ở được như vậy, giống như tôi, thì tốt.  9 Nhưng nếu họ không thể tự chế, họ nên lập gia đình, vì thà lập gia đình còn hơn để dục tình un đốt.
                10 Ðối với những người đã lập gia đình rồi thì tôi, không phải chỉ tôi mà Chúa nữa, truyền lịnh nầy: vợ không được bỏ chồng.  11 Nhưng nếu vợ đã ly thân với chồng, bà ấy phải ở độc thân hoặc phải làm hòa lại với chồng, và chồng cũng không được ly dị vợ.
                12 Ðối với những người còn lại thì tôi nói, tôi chứ không phải Chúa nói: Nếu anh em nào có vợ không tin Chúa, và người vợ ấy bằng lòng sống đời với mình, anh em đó không được ly dị nàng.  13 Nếu một người vợ có chồng không tin Chúa, và người chồng đó muốn sống suốt đời với nàng, nàng không được ly dị chồng nàng.  14 Vì người chồng không tin Chúa nhờ người vợ mà được mối liên hệ thánh, và người vợ không tin Chúa nhờ người chồng mà được mối liên hệ thánh.  Nếu không, con cái của anh chị em đều bị ô uế, nhưng bây giờ chúng đều có mối liên hệ thánh.
                15 Nhưng nếu người bạn đời không tin Chúa nhất định đòi phải dứt khoát chia lìa, hãy để người ấy chia lìa.  Trong trường hợp đó người anh em hay chị em không còn bị ràng buộc nữa, vì Ðức Chúa Trời đã gọi anh chị em sống hòa bình.
                16 Vì hỡi người làm vợ, biết đâu chị em sẽ cứu được chồng mình?  Và hỡi người làm chồng, biết đâu anh em sẽ cứu được vợ mình?

                """],
            ["Sống Như Chúa Ðã Gọi": """
                17 Thế thì Chúa đã giao phó cho mỗi người làm sao, Ðức Chúa Trời đã kêu gọi mỗi người thể nào, hãy sống như vậy.  Ðó là điều tôi đã chỉ thị trong tất cả các hội thánh.  18 Người nào khi được kêu gọi mà đã được cắt bì, người ấy không cần làm ra vẻ như không được cắt bì.  Người nào khi được kêu gọi mà chưa được cắt bì, người ấy không cần được cắt bì.  19 Ðược cắt bì không quan trọng, mà không được cắt bì cũng không quan trọng.  Ðiều quan trọng là vâng giữ các điều răn của Ðức Chúa Trời.  20 Lúc được kêu gọi, mỗi người đang ở trong tình trạng nào, hãy giữ nguyên tình trạng ấy.
                21 Bạn là nô lệ khi được kêu gọi chăng?  Ðừng để điều đó làm bận tâm bạn.  Nhưng nếu bạn có cơ hội trở thành người tự do, hãy nên bắt lấy cơ hội đó.  22 Vì một người nô lệ khi được Chúa kêu gọi thì trở thành một người tự do của Chúa; cũng vậy một người tự do khi được Ðấng Christ kêu gọi thì trở thành một nô lệ của Ngài.  23 Anh chị em đã được mua bằng một giá rất cao rồi, đừng để mình trở thành nô lệ của người ta nữa.  24 Thưa anh chị em, lúc anh chị em được kêu gọi, anh chị em ở trong tình trạng nào, hãy cứ ở trong tình trạng đó với Ðức Chúa Trời.

                """],
            ["Giải Ðáp Thắc Mắc về Vấn Ðề Sống Ðộc Thân và Ở Góa": """
                25 Về vấn đề sống độc thân, tôi không có mệnh lệnh của Chúa, nhưng tôi xin chia sẻ ý kiến của tôi, như một người đáng tin cậy, nhờ ơn thương xót của Chúa.  26 Tôi nghĩ rằng vì những khó khăn hiện nay, một người cứ ở vậy là tốt.  27 Nếu bạn đang bị ràng buộc với vợ, đừng tìm cách thoát ra.  Nếu bạn đang còn tự do chưa vợ, đừng kiếm vợ.  28 Nếu bạn lập gia đình, bạn không phạm tội gì.  Nếu một trinh nữ lấy chồng, nàng không phạm tội gì, vì những người lập gia đình sẽ mang lấy khổ vào thân, và ấy là điều tôi mong anh chị em khỏi bị.
                29 Thưa anh chị em, ý tôi muốn nói là thế nầy: thời gian còn quá ngắn, nên từ bây giờ, người có vợ hãy nên như người không vợ, 30 người đang khóc hãy nên như người không khóc, người đang vui hãy nên như người không vui, người đang mua hãy nên như người không làm chủ vật gì, 31 người đang thụ hưởng những gì thuộc về thế gian hãy nên như người không thụ hưởng, vì hình trạng của thế gian nầy sẽ qua đi.
                32 Tôi muốn anh chị em không bận tâm lo lắng gì cả.  Người không lấy vợ thì chăm lo việc Chúa, và tìm cách làm sao cho vui lòng Chúa.  33 Người lấy vợ rồi thì chăm lo việc đời, và làm sao cho vợ vui lòng; 34 thế là người ấy đã bị phân tâm rồi.  Phụ nữ độc thân và trinh nữ thì chăm lo việc Chúa, để cả thân thể lẫn tâm linh được nên thánh; còn phụ nữ đã có chồng thì chăm lo việc đời, làm sao cho chồng được vui lòng.
                35 Tôi nói điều ấy vì ích lợi của anh chị em, chứ không phải để gài bẫy anh chị em đâu, nhưng tôi chỉ muốn hướng dẫn anh chị em làm điều thích đáng, để không bị phân tâm mà liên tục hầu việc Chúa.
                36 Nếu người nào nghĩ rằng mình đã xử sự không phải với vị hôn thê của mình, nếu nàng đã quá tuổi thành niên, mà bây giờ muốn cưới nàng, thì hãy để người ấy cưới nàng, như đáng phải làm.  Người ấy không phạm tội gì.  Hãy để cho họ cưới nhau.  37 Nhưng nếu ai trong lòng đã vững lập trường, cảm thấy mình không bị thúc ép phải lập gia đình, nhưng chế ngự được dục vọng mình; nếu người ấy đã quyết định trong lòng như thế và giữ cho người đã thuộc về mình vẫn là trinh nữ, thì đó cũng là một việc tốt.  38 Thế thì người cưới vị hôn thê của mình là làm một việc tốt; còn người không cưới vợ lại làm một việc tốt hơn.
                39 Chồng còn sống bao lâu, vợ phải bị ràng buộc với chồng bấy lâu.  Nhưng nếu chồng qua đời, người vợ góa được tự do, nàng muốn lấy ai tùy ý, miễn là lấy người trong Chúa.  40 Nhưng theo ý tôi, góa phụ ấy sẽ được phước hơn nếu nàng cứ ở vậy.  Tôi nghĩ rằng tôi cũng có Ðức Thánh Linh của Ðức Chúa Trời.

                """]
            ]),
        Chapter(8, passages: [
            ["Giải Ðáp Thắc Mắc về Vấn Ðề Ăn Của Cúng Thần Tượng": """
                1 Về vấn đề của cúng thần tượng: Chúng tôi biết rằng tất cả chúng ta đều hiểu biết.  Tuy nhiên sự hiểu biết dễ sinh ra kiêu ngạo, còn tình yêu mới thật sự xây dựng.  2 Ai tưởng rằng mình hiểu biết điều gì, chưa hẳn người ấy đã hiểu biết như cần phải hiểu biết đâu.  3 Nhưng nếu ai yêu kính Ðức Chúa Trời, Ngài biết người ấy.
                4 Vậy về vấn đề ăn của cúng thần tượng, chúng ta biết rằng thần tượng không thực hữu trong thế gian, và không có thần nào khác ngoài chân thần duy nhất là Ðức Chúa Trời.  5 Mặc dù người ta cho rằng có nhiều thần, hoặc ở trên trời hoặc ở dưới đất –quả thật là người ta tin có nhiều thần, nhiều chúa– 6 nhưng đối với chúng ta, chỉ có một Thần, đó là Ðức Chúa Trời, là Cha, Ðấng dựng nên muôn vật, chúng ta hiện hữu vì Ngài; và chỉ có một Chúa, đó là Ðức Chúa Jesus Christ, nhờ Ngài muôn vật được dựng nên, và nhờ Ngài chúng ta hiện hữu.
                7 Tuy nhiên không phải mọi người đều hiểu biết như thế.  Một số người từ trước đến nay đã biết quá rõ về thần tượng, nên khi họ ăn của cúng cho thần tượng, lương tâm yếu đuối của họ cảm thấy bị ô uế.  8 Thức ăn không làm cho chúng ta được gần với Ðức Chúa Trời hơn; nếu không ăn chúng ta chẳng xấu hơn, nếu ăn chúng ta chẳng tốt hơn.  9 Nhưng hãy thận trọng, kẻo anh chị em sử dụng quyền tự do ấy làm cớ vấp ngã cho những người yếu đuối.  10 Vì nếu một người có lương tâm yếu đuối thấy bạn, người hiểu biết, ngồi ăn trong đền thờ thần tượng thì người ấy cũng bị cám dỗ mà ăn của cúng thần tượng chăng?  11 Như vậy sự hiểu biết của bạn đã làm hư mất một người yếu đuối, một anh em hay chị em mà Ðấng Christ đã chết thay cho.  12 Khi bạn phạm tội như thế đối với anh chị em mình và làm cho lương tâm yếu đuối của họ bị thương tổn, bạn đã phạm tội đối với Ðấng Christ.  13 Thế thì nếu vì thức ăn mà làm cho anh chị em tôi bị vấp ngã, tôi sẽ không bao giờ ăn thịt nữa, để khỏi làm cớ vấp ngã cho anh chị em tôi.

                """]
            ]),
        Chapter(9, passages: [
            ["Quyền Lợi của Sứ Ðồ": """
                1 Tôi không có tự do sao?  Tôi không phải là một sứ đồ sao?  Không phải tôi đã thấy Ðức Chúa Jesus, Chúa chúng ta sao?  Anh chị em không phải là thành quả của tôi trong Chúa sao?  2 Nếu tôi không phải là sứ đồ của người khác, ít nữa tôi cũng là sứ đồ của anh chị em, vì anh chị em là ấn chứng về chức vụ sứ đồ của tôi trong Chúa.
                3 Ðây là lời biện hộ của tôi đối với những người đang hạch sách tôi.  4 Chúng tôi không có quyền ăn và uống sao?  5 Chúng tôi không có quyền dẫn vợ, là một người nữ đã tin Chúa, đi theo để hầu việc Ngài, như các sứ đồ khác, hoặc như các em trai Chúa, và Sê-pha đã làm sao?  6 Hay chỉ có tôi và Ba-na-ba là không có quyền khỏi làm việc đời để sinh sống?  7 Có ai đi lính mà ăn lương nhà bao giờ chăng?  Có ai trồng vườn nho mà không ăn trái của nó chăng?  Hay có ai chăn bầy mà không dùng sữa của bầy súc vật mình chăn nuôi chăng?
                8 Tôi nói vậy chẳng phải vì theo quan điểm của người đời đâu; Luật Pháp không nói như thế sao?  9 Vì trong Luật Pháp của Môi-se có viết,
                “Ngươi chớ khớp miệng con bò trong khi nó đạp lúa.”
                Phải chăng Ðức Chúa Trời lo cho bò?  10 Chẳng phải Ngài nói như thế vì chúng ta sao?  Quả thật lời ấy đã chép vì chúng ta, vì ai cày, hãy cày với hy vọng, và ai đập lúa, hãy đập lúa với hy vọng được chia phần.  11 Nếu chúng tôi đã gieo của thuộc linh cho anh chị em mà gặt của thuộc thể nơi anh chị em, thì đó có phải là việc quá đáng chăng?  12 Nếu những người khác mà còn có quyền đó trên anh chị em, thì chúng tôi lại chẳng có quyền đó hơn sao?
                Tuy nhiên chúng tôi đã không sử dụng quyền đó, nhưng chúng tôi chịu đựng tất cả, để khỏi gây trở ngại cho Tin Mừng của Ðấng Christ.  13 Anh chị em chẳng biết rằng ai phục vụ trong đền thờ thì được hưởng của dâng trong đền thờ, và ai phục vụ nơi bàn thờ thì có phần về của dâng nơi bàn thờ chăng?  14 Cũng vậy, Chúa đã truyền rằng, ai rao giảng Tin Mừng thì phải được nuôi sống bằng Tin Mừng.  15 Nhưng tôi không sử dụng quyền nào trong các quyền ấy cả.  Tôi không viết những điều nầy để đòi các quyền ấy đâu, vì tôi thà chết còn hơn để ai cất lấy vinh dự ấy khỏi tôi.  16 Vì nếu tôi rao giảng Tin Mừng, tôi chẳng có lý do gì để hãnh diện, vì nhu cầu bắt buộc tôi phải làm vậy, còn nếu tôi không rao giảng Tin Mừng thì khốn thay cho tôi.  17 Nếu tôi rao giảng Tin Mừng một cách vui lòng, tôi sẽ được thưởng; còn nếu tôi không vui mà làm, nhiệm vụ đó vẫn được giao phó cho tôi.  18 Vậy thì phần thưởng của tôi là gì?  Ðó là khi tôi rao giảng Tin Mừng, tôi giảng miễn phí, không sử dụng quyền lợi của người rao giảng Tin Mừng.
                19 Dù tôi được tự do đối với mọi người, nhưng tôi tự ý làm nô lệ cho mọi người, để có thể chinh phục được nhiều người.  20 Ðối với người Do-thái, tôi đã trở nên như người Do-thái, để có thể chinh phục những người Do-thái.  Ðối với người ở dưới Luật Pháp, tôi đã trở nên như người ở dưới Luật Pháp, dù chính tôi không cần phải ở dưới Luật Pháp, để có thể chinh phục những người ở dưới Luật Pháp.  21 Ðối với những người không có Luật Pháp, tôi đã trở nên như người không có Luật Pháp, dù tôi không phải là người không có luật pháp của Ðức Chúa Trời, nhưng tôi ở dưới luật pháp của Ðấng Christ, để tôi có thể chinh phục những người không có Luật Pháp.  22 Ðối với những người yếu đuối, tôi đã trở nên như người yếu đuối, để có thể chinh phục những người yếu đuối.  Tôi đã trở nên mọi sự cho mọi người, để bởi mọi cách tôi có thể cứu được một số người.  23 Mọi sự tôi làm là làm vì cớ Tin Mừng, để tôi có thể dự phần trong những phước hạnh của Tin Mừng.
                24 Anh chị em không biết rằng mọi người chạy đua trong vận động trường đều chạy, nhưng chỉ có một người đoạt giải sao?  Hãy chạy cách nào để có thể đoạt giải.  25 Những lực sĩ tranh tài đều tự mình kiêng cữ đủ điều.  Họ làm vậy để được mão miện đắc thắng hay hư nát, nhưng chúng ta sẽ nhận mão miện đắc thắng không hề hư nát.  26 Vậy tôi chạy, không phải chạy lông bông; tôi đánh, không phải đánh vào không khí; 27 nhưng tôi đãi thân thể tôi cách nghiêm khắc, bắt nó làm nô lệ cho tôi, kẻo tôi giảng dạy cho người khác mà chính mình lại bị bất hợp lệ chăng.

                """]
            ]),
        Chapter(10, passages: [
            ["Cảnh Cáo về Thần Tượng": """
                1 Thưa anh chị em, tôi không muốn anh chị em không biết rằng tất cả tổ phụ chúng ta đều ở dưới đám mây, tất cả đều đã vượt qua biển, 2 tất cả đã cùng đi theo Môi-se nên đã được báp-têm dưới đám mây và xuyên qua lòng biển, 3 tất cả đã ăn cùng một thức ăn thiêng liêng, 4 và tất cả đã uống cùng một thức uống thiêng liêng, vì họ đã cùng uống từ một vầng đá thiêng liêng đi với họ, và vầng đá đó là Ðấng Christ.  5 Tuy nhiên, phần đông họ đã không sống đẹp lòng Ðức Chúa Trời, nên đã ngã chết trong đồng hoang.
                6 Những điều ấy đã xảy ra để làm gương cho chúng ta, hầu chúng ta không chiều theo những ham muốn xấu xa như họ đã ham muốn.  7 Ðừng thờ thần tượng như một số người trong vòng họ đã thờ, như lời đã chép,
                “Dân chúng ngồi lại ăn uống, rồi đứng dậy mà trửng giỡn.”
                8 Chúng ta chớ dâm loạn như một số người trong vòng họ đã dâm loạn, khiến hai mươi ba ngàn người ngã chết trong một ngày.  9 Chúng ta đừng thử Ðấng Christ như một số người trong vòng họ đã thử Chúa, để bị các rắn độc cắn chết.  10 Chúng ta cũng đừng lầm bầm oán trách như một số người trong vòng họ đã lầm bầm oán trách, để bị thiên thần hủy diệt tiêu diệt.
                11 Những điều ấy xảy đến với họ để làm gương cho chúng ta.  Những chuyện ấy được ghi lại để cảnh cáo chúng ta, những người đang sống ở cuối các thời đại.  12 Vậy ai tưởng mình đứng, hãy cẩn trọng kẻo ngã.
                13 Không thử thách nào xảy đến với anh chị em là quá sức người.  Ðức Chúa Trời là thành tín; Ngài không để anh chị em bị thử thách quá sức của mình đâu, nhưng trong sự thử thách Ngài sẽ mở đường cho ra khỏi, để anh chị em có thể chịu đựng nổi.
                14 Vậy thưa anh chị em yêu dấu của tôi, xin anh chị em hãy lánh xa sự thờ thần tượng.  15 Tôi nói với anh chị em như nói với những người khôn ngoan hiểu biết; xin anh chị em hãy suy xét những điều tôi nói.  16 Cái chén phước hạnh chúng ta chúc tạ chẳng phải hiệp thông với huyết của Ðấng Christ sao?  Cái bánh chúng ta bẻ chẳng phải hiệp thông với thân thể của Ðấng Christ sao?  17 Vì có một cái bánh, chúng ta dù nhiều người cũng chỉ một thân, vì tất cả chúng ta cùng hưởng cái bánh ấy.
                18 Hãy xem dân I-sơ-ra-ên theo phương diện huyết thống: chẳng phải những người ăn thịt con vật hiến tế là hiệp thông với bàn thờ sao?  19 Tôi nói vậy có ý gì?  Của cúng thần tượng có là gì, hay chính thần tượng có là gì chăng?  20 Dĩ nhiên là không, nhưng lễ vật người ngoại đạo cúng tế là cúng tế các quỷ, chứ không phải dâng hiến lên Ðức Chúa Trời, nên tôi không muốn anh chị em trở thành những người hiệp thông với các quỷ.  21 Anh chị em không thể uống chén của Chúa và uống chén của các quỷ.  Anh chị em không thể dự bàn tiệc của Chúa và dự bàn tiệc của các quỷ.  22 Hay chúng ta muốn chọc Chúa nổi ghen chăng?  Chúng ta mạnh hơn Ngài sao?
                23 Tôi có quyền làm mọi sự, nhưng không phải mọi sự đều có ích.  Tôi có quyền làm mọi sự, nhưng không phải mọi sự đều xây dựng.  24 Ðừng ai tìm lợi riêng cho mình, nhưng hãy tìm lợi cho người khác nữa.  25 Ðối với tất cả những thứ thịt bán ở hàng thịt, cứ mua về ăn, đừng vì lương tâm mà thắc mắc gì cả, 26 vì trái đất và mọi vật trong đó đều thuộc về Chúa.  27 Nếu có người không tin mời anh chị em dùng bữa và anh chị em đã nhận lời, cứ ăn tự nhiên những gì họ dọn ra trước mặt, đừng vì lương tâm mà thắc mắc gì cả.
                28 Nhưng nếu có người nói với anh chị em rằng, “Món nầy đã cúng rồi,” thì đừng ăn món đó, bởi vì người đó đã tỏ cho anh chị em biết và cũng vì lương tâm nữa.  29 Tôi không nói về lương tâm của anh chị em, nhưng lương tâm của người đó.  Nhưng tại sao sự tự do của tôi lại bị lương tâm của người khác xét đoán?   30 Nếu tôi cảm tạ Chúa trước khi ăn, tại sao tôi còn bị chỉ trích về thức ăn tôi đã cảm tạ?  31 Vậy anh chị em hoặc ăn, hoặc uống, hoặc làm sự chi khác, hãy làm tất cả vì vinh hiển của Ðức Chúa Trời.  32 Ðừng làm cớ vấp ngã cho người Do-thái, hay cho người Hy-lạp, hay cho hội thánh của Ðức Chúa Trời, 33 giống như tôi cố gắng làm hài lòng mọi người trong mọi sự, không tìm lợi ích riêng cho mình, nhưng cho nhiều người, để họ có thể được cứu.

                """]
            ]),
        Chapter(11, passages: [
            ["": """
                1 Hãy bắt chước tôi như tôi bắt chước Ðấng Christ.
                
                """],
            ["Phong Tục Phụ Nữ Trùm Ðầu": """
                2 Tôi có lời khen anh chị em, vì anh chị em luôn nhớ đến tôi trong mọi sự, và duy trì những truyền thống tôi đã truyền lại cho anh chị em.  3 Nhưng tôi muốn anh chị em biết rằng Ðấng Christ là đầu của mọi người nam, người nam là đầu của người nữ, và Ðức Chúa Trời là đầu của Ðấng Christ.  4 Người nam nào cầu nguyện hoặc nói tiên tri mà trùm đầu lại là làm nhục đầu mình.  5 Nhưng người nữ nào cầu nguyện hoặc nói tiên tri mà không trùm đầu lại là làm nhục đầu mình, như thể nàng đã bị cạo đầu vậy.  6 Vì nếu một phụ nữ không trùm đầu lại, nàng nên cắt tóc đi; nhưng nếu người nữ nào xem việc cắt tóc hay cạo đầu là xấu hổ thì hãy trùm đầu lại.
                7 Thật vậy người nam không nên trùm đầu mình lại, vì người nam là hình ảnh và vinh hiển của Ðức Chúa Trời, còn người nữ là vinh hiển của người nam.  8 Không phải người nam đầu tiên được dựng nên từ người nữ, nhưng người nữ đầu tiên ra từ người nam.  9 Cũng không phải người nam đầu tiên được dựng nên vì cớ người nữ, nhưng người nữ đầu tiên được dựng nên vì cớ người nam.  10 Vì lý do đó và vì các thiên sứ đang nhìn, người nữ phải trùm đầu lại để bày tỏ sự chấp nhận thẩm quyền.
                11 Tuy nhiên trong Chúa người nữ không độc lập với người nam, và người nam không độc lập với người nữ.  12 Vì như người nữ ra từ người nam, thì người nam cũng ra từ người nữ, và mọi sự ra từ Ðức Chúa Trời.
                13 Chính anh chị em hãy xét xem: một người nữ cầu nguyện với Ðức Chúa Trời mà không trùm đầu lại thì có hợp lẽ chăng?  14 Chẳng phải lẽ tự nhiên dạy anh chị em rằng một người nam để tóc dài là làm xấu hổ chính mình, 15 nhưng nếu một người nữ để tóc dài thì chẳng phải đó là vinh hiển của nàng sao?  Vì mái tóc dài được ban cho nàng như một khăn trùm đầu vậy.  16 Nếu ai nghĩ rằng phải cãi cho ra lẽ việc nầy thì chúng tôi không có thói quen đó, và các hội thánh của Ðức Chúa Trời cũng vậy.

                """],
            ["Tổ Chức Tiệc Thánh Sai": """
                17 Trong những lời chỉ dẫn sau đây tôi không khen anh chị em đâu, bởi vì khi anh chị em đến với nhau, anh chị em chẳng những đã không làm cho tốt hơn, mà còn làm cho tệ hơn.  18 Vì trước hết tôi được nghe rằng khi anh chị em nhóm lại với nhau, giữa anh chị em có sự chia rẽ.  Tôi tin rằng điều ấy có phần nào đúng.  19 Thật vậy việc phe phái giữa anh chị em chắc khó tránh khỏi, nhưng nhờ vậy mới biết rõ ai là người được tôi luyện.
                20 Khi anh chị em nhóm lại với nhau, chắc hẳn không phải anh chị em đến dự tiệc của Chúa rồi, 21 vì khi dự tiệc thì mạnh ai nấy ăn phần của mình đem đến, đến nỗi kẻ thì no say, người thì đói khát.  22 Anh chị em không có nhà để ăn uống sao?  Hay anh chị em khinh thường hội thánh của Ðức Chúa Trời, và muốn làm cho những người nghèo khó thiếu ăn phải hổ thẹn?  Tôi phải nói với anh chị em thế nào đây?  Tôi có nên khen anh chị em không?  Về việc nầy tôi không khen anh chị em đâu.

                """],
            ["Tiệc Thánh": """
                (Mat 26:26-29; Mác 14:22-25; Lu 22:14-20)
                
                23 Vì những gì tôi đã nhận từ Chúa, tôi truyền lại cho anh chị em, đó là Ðức Chúa Jesus trong đêm Ngài bị phản nộp đã lấy bánh, 24 sau khi dâng lời tạ ơn, Ngài bẻ ra và phán, “Ðây là thân thể Ta, vì các ngươi phó cho; hãy làm điều nầy để nhớ Ta.”
                25 Sau bữa ăn tối, Ngài lấy chén và cũng làm như vậy, rồi phán rằng, “Chén nầy là giao ước mới trong huyết Ta; hãy làm điều nầy, mỗi khi các ngươi uống, để nhớ Ta.”
                26 Vậy mỗi khi ăn bánh nầy và uống chén nầy, anh chị em rao truyền sự chết của Chúa cho tới lúc Ngài đến.  27 Do đó những ai ăn bánh và uống chén của Chúa cách không xứng đáng sẽ mắc tội với thân và huyết của Chúa.  28 Vậy mỗi người phải tự xét chính mình, và như thế mới ăn bánh và uống chén, 29 vì người nào không phân biệt thân Chúa mà ăn bánh và uống chén ấy là ăn uống sự đoán xét cho mình.
                30 Vì cớ đó trong anh chị em có lắm người đau yếu, bịnh tật, và một số người đã ngủ.  31 Nhưng nếu chúng ta biết tự xét đoán chính mình, chúng ta sẽ không bị xét đoán.  32 Nhưng khi chúng ta bị Chúa xét đoán, Ngài sẽ sửa dạy chúng ta, để chúng ta không bị kết án chung với thế gian.
                33 Thưa anh chị em, vì thế mỗi khi anh chị em họp lại để ăn chung với nhau, hãy chờ đợi nhau.  34 Nếu ai đói, hãy ăn trước ở nhà, kẻo anh chị em sẽ bị xét đoán khi nhóm họp với nhau.  Còn những việc khác, khi tôi đến, tôi sẽ chỉ dẫn cho anh chị em.

                """]
            ]),
        Chapter(12, passages: [
            ["Ân Tứ Thuộc Linh": """
                1 Thưa anh chị em, tôi không muốn anh chị em không biết gì về những ân tứ thuộc linh.  2 Anh chị em biết rằng khi còn là người ngoại đạo, anh chị em đã bị lôi cuốn và bị dẫn dụ thờ lạy những thần tượng câm.  3 Vì vậy tôi muốn anh chị em biết rằng không ai được Ðức Thánh Linh của Ðức Chúa Trời cảm động mà nói, “Ðức Chúa Jesus đáng bị nguyền rủa!” và cũng không ai có thể nói, “Ðức Chúa Jesus là Chúa!” nếu không bởi Ðức Thánh Linh thúc giục.
                4 Có nhiều ân tứ khác nhau, nhưng chỉ cùng một Ðức Thánh Linh.  5 Có nhiều cách phục vụ khác nhau, nhưng chỉ cùng một Chúa.  6 Có nhiều hoạt động khác nhau, nhưng chỉ cùng một Ðức Chúa Trời, Ðấng làm mọi sự trong mọi người.
                7 Vì lợi ích chung, sự ban cho của Ðức Thánh Linh thể hiện qua mỗi người mỗi khác. 8 Từ một Ðức Thánh Linh có người được ban cho những lời nói khôn ngoan, cùng một Ðức Thánh Linh người khác được ban cho những lời nói tri thức.  9 Từ cùng một Ðức Thánh Linh người nầy được ơn đức tin, người kia được ơn chữa bịnh.  Cũng từ một Ðức Thánh Linh 10 có người được ơn làm phép lạ, người khác được ơn nói tiên tri, có người được ơn phân biệt các linh, người khác được ơn nói tiếng lạ, và người khác nữa được ơn thông giải tiếng lạ.  11 Tất cả những điều ấy đều là việc của cùng một Ðức Thánh Linh; Ngài phân phối cho mỗi người tùy ý Ngài muốn.

                """],
            ["Một Thân với Nhiều Bộ Phận": """
                12 Vì giống như thân thể con người, một thân nhưng có nhiều bộ phận, và tất cả các bộ phận của thân dù nhiều, nhưng vẫn thuộc về một thân; Ðấng Christ cũng vậy.  13 Vì cùng một Ðức Thánh Linh mà tất cả chúng ta đã được báp-têm vào một thân, bất luận người Do-thái hay người Hy-lạp, bất kể nô lệ hay tự do, và tất cả đã được uống chung một Ðức Thánh Linh.
                14 Vì thân không phải chỉ là một bộ phận mà gồm nhiều bộ phận.  15 Nếu chân nói, “Vì tôi không phải là tay, tôi không thuộc về thân,” có phải vì vậy mà chân không là một phần trong thân chăng?  16 Nếu tai nói, “Vì tôi không phải là mắt, tôi không thuộc về thân,” có phải vì thế mà tai không là một phần trong thân chăng?  17 Nếu cả thân là mắt thì làm sao nghe?  Nếu cả thân là tai thì làm sao ngửi?  18 Nhưng Ðức Chúa Trời đã sắp đặt các bộ phận trong thân, cái nào vào việc nấy theo ý Ngài muốn.  19 Nếu tất cả là một bộ phận thì thân ở đâu?  20 Thế thì có nhiều bộ phận, nhưng chỉ có một thân.  21 Mắt không thể nói với tay rằng, “Tôi không cần đến bạn,” hay đầu cũng không thể nói với chân rằng, “Tôi không cần các bạn.”  22 Ngược lại, những bộ phận nào trong thân tưởng là yếu hơn thì lại là cần thiết.  23 Những bộ phận nào trong thân chúng ta nghĩ là tầm thường, chúng ta phải đối xử cách tôn trọng hơn; những bộ phận nào kém đẹp đẽ, chúng ta phải trang điểm nhiều hơn cho được đẹp đẽ lên.  24 Còn những bộ phận nào đã đẹp sẵn rồi thì không cần trang điểm thêm.  Ðức Chúa Trời đã khéo sắp đặt các bộ phận trong thân, để bộ phận nào yếu kém thì được tôn trọng nhiều, 25 hầu trong thân không có sự chia rẽ, nhưng tất cả các bộ phận phải lo tưởng đến nhau.  26 Nếu một bộ phận nào đau, tất cả các bộ phận cùng đau; nếu bộ phận nào được tôn trọng, tất cả các bộ phận cùng vui mừng.
                27 Anh chị em là thân thể của Ðấng Christ và mỗi người là một bộ phận.  28 Ðức Chúa Trời đã đặt để trong hội thánh một số người, thứ nhất các sứ đồ, thứ nhì các tiên tri, thứ ba các giáo sư, kế đến những người được ơn làm phép lạ, rồi những người được ơn chữa bịnh, những người được ơn giúp đỡ, những người được ơn điều hành, những người được ơn nói tiếng lạ.
                29 Không lẽ tất cả đều là sứ đồ sao?  Không lẽ tất cả đều là tiên tri sao?  Không lẽ tất cả đều là giáo sư sao?  Không lẽ tất cả đều làm phép lạ sao?  30 Không lẽ tất cả đều được ơn chữa bịnh sao?  Không lẽ tất cả đều nói tiếng lạ sao?  Không lẽ tất cả đều thông giải tiếng lạ sao?  31 Anh chị em hãy khao khát các ân tứ cao trọng hơn, rồi tôi sẽ chỉ cho anh chị em con đường tuyệt vời hơn nữa.

                """]
            ]),
        Chapter(13, passages: [
            ["Tình Yêu": """
                1 Dù tôi nói được các thứ tiếng của loài người và thiên sứ nhưng không có tình yêu thì tôi chỉ như chiêng cồng rền vang hay não bạt khua tiếng.  2 Dù tôi được ơn nói tiên tri, cùng quán thông mọi huyền nhiệm và mọi ngành tri thức, và dù tôi có tất cả đức tin đến nỗi có thể dời non chuyển núi, nhưng không có tình yêu thì tôi chẳng ra gì.  3 Dù tôi đem tất cả tài sản của mình ra bố thí, và dù tôi hiến thân để chịu hỏa thiêu, nhưng không có tình yêu thì những điều đó chẳng ích gì cho tôi.
                4 Tình yêu hay nhẫn nhục, tình yêu hay nhân từ, tình yêu không ganh tị, không khoe khoang, không tự cao, 5 không cư xử trái lẽ, không tìm tư lợi, không nhạy giận, không giữ lòng oán hận, 6 không vui về việc bất chính, nhưng vui về sự chân thật.  7 Tình yêu dung thứ tất cả, tin tưởng tất cả, hy vọng tất cả, chịu đựng tất cả.
                8 Tình yêu sẽ trường tồn mãi mãi.  Ơn nói tiên tri sẽ dứt, ơn nói tiếng lạ sẽ ngưng, ơn hiểu biết sẽ bị đào thải.  9 Vì chúng ta hiểu biết chỉ phần nào, và chúng ta nói tiên tri chỉ phần nào; 10 nhưng khi sự vẹn toàn đến thì những gì bất toàn sẽ bị loại bỏ.  11 Khi tôi còn là trẻ con, tôi nói như trẻ con, suy nghĩ như trẻ con, lập luận như trẻ con; nhưng khi tôi đã trưởng thành, thì tôi từ bỏ những gì có vẻ trẻ con.  12 Bây giờ chúng ta thấy không rõ như nhìn vào tấm gương mờ, nhưng khi ấy chúng ta sẽ thấy rõ như mặt đối mặt.  Bây giờ chúng ta hiểu biết chỉ có hạn, nhưng khi ấy tôi sẽ biết tận tường, như Chúa biết rõ tôi.
                13 Bây giờ còn lại ba điều nầy: đức tin, hy vọng, và tình yêu; nhưng điều cao trọng hơn cả là tình yêu.

                """]
            ]),
        Chapter(14, passages: [
            ["Ơn Nói Tiếng Lạ và Ơn Nói Tiên Tri": """
                1 Hãy đeo đuổi tình yêu và khao khát các ân tứ thuộc linh, đặc biệt là ơn nói tiên tri.  2 Vì người được ơn nói tiếng lạ không nói với loài người, nhưng nói với Ðức Chúa Trời, bởi không ai hiểu được, vì người ấy nói các huyền nhiệm trong Ðức Thánh Linh.  3 Trong khi đó người nói tiên tri thì nói với loài người để xây dựng, khích lệ, và an ủi.  4 Người nói tiếng lạ xây dựng chính mình, còn người nói tiên tri xây dựng hội thánh.  5 Dù tôi muốn tất cả anh chị em được ơn nói tiếng lạ, nhưng tôi càng mong muốn tất cả anh chị em được ơn nói tiên tri hơn.  Người được ơn nói tiên tri cao trọng hơn người được ơn nói tiếng lạ, ngoại trừ có người thông giải, để hội thánh được xây dựng.
                6 Bây giờ thưa anh chị em, nếu tôi đến với anh chị em và chỉ nói tiếng lạ, mà không nói cho anh chị em một sự mặc khải, hoặc một sự hiểu biết, hoặc một lời tiên tri, hoặc một sự dạy dỗ nào thì tôi giúp ích được gì cho anh chị em chăng?  7 Các nhạc cụ không có sự sống cũng vậy, giống như ống sáo hoặc hạc cầm, nếu chúng không phát ra những âm thanh độc đáo riêng thì làm sao người ta biết đó là tiếng sáo thổi hay hạc cầm đang trỗi khúc?  8 Nếu tiếng kèn thổi lên không rõ điệu thì ai sẽ chuẩn bị ra trận?  9 Anh chị em cũng vậy, nếu miệng lưỡi anh chị em không phát âm những lời có thể hiểu được thì ai biết anh chị em nói gì?  Chẳng qua là nghe anh chị em nói líu lo thôi.  10 Hẳn nhiên trên thế giới nầy có nhiều ngôn ngữ, nhưng không ngôn ngữ nào là không có ý nghĩa.  11 Nếu tôi không hiểu ý nghĩa của một ngôn ngữ thì người nói ngôn ngữ ấy sẽ xem tôi là người ngoại quốc, và tôi cũng xem người ấy là người ngoại quốc.  12 Anh chị em cũng vậy, vì anh chị em nhiệt thành tìm kiếm các ân tứ thuộc linh, vậy hãy tìm kiếm cho nhiều để dùng xây dựng hội thánh.
                13 Vậy người được ơn nói tiếng lạ hãy cầu nguyện để có người thông giải điều mình nói.  14 Vì nếu tôi cầu nguyện bằng tiếng lạ thì tâm linh tôi cầu nguyện, nhưng tâm trí tôi chẳng được kết quả gì.  15 Vậy tôi phải làm gì?  Tôi sẽ cầu nguyện bằng tâm linh và tôi cũng cầu nguyện bằng tâm trí; tôi sẽ ca ngợi bằng tâm linh và tôi cũng ca ngợi bằng tâm trí.  16 Nếu không, khi bạn chúc tụng bằng tâm linh thì làm sao một người không hiểu đang ở đó có thể nói “A-men” về những lời bạn cảm tạ, khi người ấy không hiểu bạn nói gì?  17 Dù rằng lời cảm tạ của bạn thật tốt nhưng người khác không được xây dựng.  18 Tôi tạ ơn Ðức Chúa Trời vì tôi nói tiếng lạ nhiều hơn mọi người trong anh chị em.  19 Nhưng trong hội thánh, tôi thà nói năm lời bằng tâm trí để có thể dạy dỗ người khác hơn nói mười ngàn lời bằng tiếng lạ.
                20 Thưa anh chị em, về sự hiểu biết xin đừng như trẻ con; nhưng về điều ác, hãy nên như trẻ con; về sự hiểu biết, hãy như người trưởng thành.
                21 Trong Luật Pháp có chép rằng,
                “Bởi các thứ tiếng lạ và bởi môi miệng của những người ngoại quốc,
                Ta sẽ nói với dân nầy;
                Nhưng dù như thế, chúng vẫn chẳng nghe Ta.
                Chúa phán vậy.”
                22 Thế thì các tiếng lạ không phải là dấu kỳ cho các tín hữu, nhưng cho người chưa tin; còn lời tiên tri thì không phải cho người chưa tin, nhưng cho các tín hữu.  23 Khi cả hội thánh nhóm lại với nhau và ai cũng nói tiếng lạ, nếu có những người không biết hoặc những người chưa tin bước vào, họ sẽ chẳng bảo rằng anh chị em đã khùng cả rồi hay sao?  24 Nhưng nếu tất cả đều nói tiên tri, và có người chưa tin hoặc người không biết bước vào, tất cả sẽ làm cho người ấy bị bắt phục về tội lỗi mình, và tất cả sẽ làm cho người ấy bị cáo trách; 25 những gì bí mật trong lòng người ấy bị phơi bày, người ấy sẽ sấp mình xuống thờ lạy Ðức Chúa Trời và nói, “Quả thật, có Ðức Chúa Trời hiện diện giữa quý vị.”

                """],
            ["Trật Tự Khi Nhóm Lại": """
                26 Vậy thưa anh chị em, chúng ta phải làm thế nào?  Khi anh chị em nhóm lại với nhau, ai có một thánh thi, ai có lời dạy dỗ, ai có sự mặc khải, ai có tiếng lạ, ai có ơn thông giải tiếng lạ, hãy thực hiện tất cả để xây dựng lẫn nhau.  27 Nếu có ai nói tiếng lạ, thì tối đa chỉ hai hoặc ba người; và mỗi người phải nói theo thứ tự của mình, và phải có người thông giải.  28 Nhưng nếu không có người thông giải, người có ơn nói tiếng lạ phải im lặng trong hội thánh, người ấy hãy nói riêng giữa mình với Ðức Chúa Trời.  29 Các vị tiên tri cũng vậy, chỉ hai hoặc ba người, và những người khác sẽ thẩm định.  30 Nếu ai trong những người ngồi đó nhận được sự mặc khải từ Chúa thì người đang nói hãy ngưng lại để nhường lời, 31 vì mọi người trong anh chị em có thể lần lượt nói tiên tri để tất cả được học hỏi và khích lệ.  32 Tâm linh của các vị tiên tri thuận phục các vị tiên tri, 33 vì Ðức Chúa Trời không phải là Ðức Chúa Trời của hỗn loạn nhưng của hòa bình.
                Như trong tất cả các hội thánh của các thánh đồ, 34 phụ nữ phải im lặng trong các hội thánh; họ không được phép phát biểu ý kiến, nhưng phải thuận phục như Luật Pháp đã dạy.  35 Nếu họ muốn học hỏi điều gì, họ nên hỏi chồng của họ ở nhà, vì thật là xấu hổ khi phụ nữ nói giữa hội thánh.
                36 Không phải lời Ðức Chúa Trời đã phát xuất từ anh chị em sao?  Không lẽ lời Ngài chỉ đến với anh chị em thôi sao?
                37 Nếu ai nghĩ mình là một tiên tri hay một người thuộc linh, người ấy phải nhìn nhận rằng những gì tôi viết cho anh chị em đây là lịnh của Chúa.  38 Nếu ai không nhìn nhận điều đó, xin anh chị em đừng nhìn nhận người ấy.
                39 Vậy thưa anh chị em, hãy khao khát được ơn nói tiên tri, nhưng cũng đừng cấm cản việc nói tiếng lạ.  40 Xin chúng ta hãy làm mọi sự một cách lễ độ và có trật tự.

                """]
            ]),
        Chapter(15, passages: [
            ["Sự Sống Lại của Ðấng Christ": """
                1 Thưa anh chị em, tôi xin nhắc lại Tin Mừng tôi đã rao giảng cho anh chị em, đó là Tin Mừng anh chị em đã nhận lãnh, và anh chị em đang đứng vững trong đó.  2 Nhờ Tin Mừng đó anh chị em được cứu, nếu anh chị em cứ giữ vững sứ điệp tôi đã rao giảng cho anh chị em, bằng không, dù anh chị em tin cũng vô ích.
                3 Trước hết tôi đã truyền lại cho anh chị em những gì chính tôi đã nhận lãnh, đó là Ðấng Christ đã chịu chết vì tội chúng ta theo lời Kinh Thánh, 4 Ngài đã được chôn, đến ngày thứ ba Ngài đã sống lại theo lời Kinh Thánh, 5 và Ngài đã hiện ra cho Sê-pha và cho nhóm mười hai sứ đồ.  6 Sau đó cùng một lúc Ngài đã hiện ra cho hơn năm trăm anh chị em xem thấy, nhiều người trong số đó hiện nay vẫn còn sống, dù có vài người đã ngủ.  7 Sau đó Ngài đã hiện ra cho Gia-cơ, rồi cho tất cả các sứ đồ.  8 Cuối cùng Ngài cũng đã hiện ra cho tôi, như cho một người sinh sau đẻ muộn.  9 Vì tôi là người hèn mọn nhất trong các sứ đồ, một người không đáng được gọi là sứ đồ, vì tôi đã bắt bớ hội thánh của Ðức Chúa Trời.  10 Nhưng nhờ ân sủng của Ðức Chúa Trời mà ngày nay tôi được như thế nầy, và ân sủng của Ngài ban cho tôi thật đã không uổng phí, vì tôi đã làm việc vất vả hơn tất cả các vị ấy, nhưng nào phải tôi, đúng ra là ân sủng của Ðức Chúa Trời đã hành động qua tôi.  11 Nhưng bất kể các vị ấy hay tôi, chúng tôi đều rao giảng những điều ấy, và anh chị em cũng đã tin như vậy.

                """],
            ["Sự Sống Lại của Chúng Ta": """
                12 Nếu chúng tôi đã giảng rằng Ðấng Christ đã sống lại, tại sao trong anh chị em lại có người bảo rằng không có việc người chết sống lại?  13 Nếu người chết không sống lại thì Ðấng Christ cũng đã không sống lại.  14 Nếu Ðấng Christ đã không sống lại thì sự giảng dạy của chúng tôi là vô ích, và đức tin của anh chị em cũng vô ích.  15 Ngoài ra chúng tôi bị xem là những kẻ làm chứng dối cho Ðức Chúa Trời, vì chúng tôi đã làm chứng cho Ðức Chúa Trời rằng Ngài đã làm cho Ðấng Christ sống lại trong khi Ngài không làm cho Ðấng Christ sống lại.  16 Vì nếu người chết không sống lại, thì Ðấng Christ cũng đã không sống lại.  17 Và nếu Ðấng Christ đã không sống lại thì đức tin của anh chị em là vô ích; anh chị em vẫn còn sống trong tội lỗi mình.  18 Như vậy những người đã ngủ trong Ðấng Christ đều chết mất.  19 Nếu chúng ta chỉ hy vọng trong Ðấng Christ về đời nầy mà thôi thì trong mọi người chúng ta là những kẻ đáng thương hại hơn cả.
                20 Nhưng sự thật là Ðấng Christ đã từ cõi chết sống lại rồi.  Ngài là trái đầu mùa của những người đã ngủ.  21 Vì bởi một người sự chết đã đến, thì cũng bởi một Người, sự sống lại của những người chết cũng sẽ đến.  22 Vì trong A-đam mọi người đều chết thì trong Ðấng Christ mọi người đều sẽ được làm cho sống lại.  23 Nhưng mỗi người sẽ theo thứ tự của mình: Ðấng Christ là trái đầu mùa nên sống lại trước hết, kế đó đến lượt những người thuộc về Ðấng Christ sẽ sống lại trong sự hiện đến của Ngài.  24 Sau đó sự cuối cùng sẽ đến, khi Ngài trao vương quốc lại cho Ðức Chúa Trời là Cha, sau khi Ngài đã phế bỏ tất cả quyền cai trị, tất cả quyền hành và quyền lực.  25 Vì Ngài phải trị vì cho đến khi Ngài đặt mọi kẻ thù của Ngài dưới chân Ngài.  26 Kẻ thù cuối cùng bị tiêu diệt là tử thần.  27 Vì Ðức Chúa Trời sẽ bắt mọi vật phải đầu phục dưới chân Ngài.  Nhưng khi nói “mọi vật phải đầu phục” thì hiển nhiên là ngoại trừ Ðấng bắt mọi vật phải đầu phục Ngài.  28 Khi mọi vật đã đầu phục Ngài rồi, thì chính Ngài là Con, cũng sẽ đầu phục Ðấng đã khiến mọi vật đầu phục Ngài, để Ðức Chúa Trời luôn là Ðấng trị vì tối thượng trong mọi sự và trên mọi loài.
                29 Nếu không, những người chịu báp-têm thay cho những người chết có hy vọng gì?  Nếu những người chết không sống lại thì tại sao họ chịu báp-têm thay cho những người chết?  30 Và tại sao chúng tôi phải đương đầu với nguy hiểm từng giờ?  31 Tôi chết mỗi ngày, thưa anh chị em; điều đó là thật đối với tôi như niềm hãnh diện của tôi về anh chị em trong Ðức Chúa Jesus Christ, Chúa chúng ta, là thật vậy.  32 Nếu chỉ hy vọng nơi con người ở đời nầy mà thôi thì tôi được lợi gì khi chiến đấu với những thú dữ ở Ê-phê-sô?  Nếu người chết không sống lại thì
                “Chúng ta hãy ăn, hãy uống, vì ngày mai chúng ta sẽ chết.”
                33 Ðừng để bị mắc lừa: “Bạn bè xấu làm hư tính nết tốt.”  34 Hãy giác ngộ mà sống ngay lành, và đừng phạm tội nữa, vì có một số người sống như không biết gì về Ðức Chúa Trời.  Tôi nói thế để anh chị em cảm thấy xấu hổ.

                """],
            ["Sự Sống Lại của Thân Thể": """
                35 Nhưng có người sẽ hỏi, “Làm thể nào người chết sống lại được?  Họ lấy thân thể nào mà sống lại?”
                36 Hỡi người khờ dại! Những gì bạn gieo xuống sẽ không phát sinh sự sống nếu không chết đi.  37 Những gì bạn gieo, không phải bạn gieo thân thể khi mọc lên sẽ có, mà chỉ là một hạt giống, chẳng hạn như hạt lúa mì hay hạt giống gì khác.  38 Ðức Chúa Trời ban cho nó sinh ra một thân thể theo ý Ngài muốn; mỗi hạt giống sinh ra một thân thể riêng.  39 Không phải mọi loài xác thịt đều có xác thịt giống nhau; xác thịt của loài người khác, xác thịt của loài thú khác, xác thịt của loài chim khác, xác thịt của loài cá khác.  40 Có những thân thể thuộc về trời, và có những thân thể thuộc về đất, nhưng vinh quang của thân thể thuộc về trời khác với vinh quang của thân thể thuộc về đất.  41 Vinh quang của mặt trời khác, vinh quang của mặt trăng khác, vinh quang của các vì sao khác, vinh quang của vì sao nầy với vinh quang của vì sao kia cũng khác.
                42 Sự sống lại của người chết cũng vậy.  Những gì gieo xuống là hư nát, nhưng sống lại là bất diệt; 43 gieo xuống là nhục nhã, nhưng sống lại là vinh hiển; gieo xuống là yếu đuối, nhưng sống lại là mạnh mẽ; 44 gieo xuống là thân thể thiên nhiên, nhưng sống lại là thân thể thiêng liêng.  Nếu có thân thể thiên nhiên, thì cũng có thân thể thiêng liêng, 45 như có lời chép rằng,
                “A-đam, con người đầu tiên, đã trở thành một linh hồn sống.”
                A-đam cuối cùng chính là Thần ban sự sống.
                46 Không phải thân thể thiêng liêng đến trước nhưng thân thể thiên nhiên, sau đó mới đến thân thể thiêng liêng.  47 Người thứ nhất ra từ đất nên thuộc về đất; người thứ nhì thì đến từ trời.  48 Người thuộc về đất thế nào, những người thuộc về đất cũng thể ấy; người đến từ trời thế nào, những người thuộc về trời cũng thể ấy.  49 Như chúng ta đã mang hình ảnh của người thuộc về đất thì chúng ta cũng sẽ mang hình ảnh của người đến từ trời.
                50 Thưa anh chị em, điều tôi muốn nói là thế nầy: xác thịt và máu huyết không thể thừa hưởng vương quốc Ðức Chúa Trời; những gì hay hư nát không thể thừa hưởng những gì bất diệt.
                51 Nầy, tôi báo cho anh chị em một huyền nhiệm: không phải tất cả chúng ta sẽ ngủ hết, nhưng tất cả chúng ta sẽ được biến hóa, 52 trong giây lát, trong chớp mắt, lúc tiếng kèn chót thổi, vì tiếng kèn sẽ thổi vang, bấy giờ những người chết sẽ sống lại để hưởng sự bất diệt, và chúng ta sẽ được biến hóa.  53 Vì thân thể sẽ hư nát nầy phải mặc lấy thân thể bất diệt, và thân thể sẽ chết nầy phải mặc lấy thân thể bất tử.  54 Khi thân thể sẽ hư nát nầy mặc lấy thân thể bất diệt, và thân thể sẽ chết nầy mặc lấy thân thể bất tử, thì lời đã chép sẽ được ứng nghiệm,
                “Tử thần đã bị sự đắc thắng nuốt mất.”
                55 “Hỡi tử thần, chiến thắng của ngươi đâu?
                Hỡi tử thần, nọc độc của ngươi đâu?”
                56 Nọc độc của tử thần là tội lỗi, và sức mạnh của tội lỗi là Luật Pháp, 57 nhưng tạ ơn Ðức Chúa Trời, Ðấng ban chiến thắng cho chúng ta qua Ðức Chúa Jesus Christ, Chúa chúng ta.
                58 Vậy thưa anh chị em yêu dấu của tôi, hãy vững vàng, đừng rúng động, hãy gia tăng làm công việc Chúa luôn, vì biết rằng công khó của anh chị em trong Chúa không vô ích đâu.

                """]
            ]),
        Chapter(16, passages: [
            ["Vấn Ðề Quyên Góp Giúp Các Tín Hữu Gặp Khốn Khó": """
                1 Bây giờ về vấn đề quyên góp giúp các thánh đồ, xin anh chị em hãy theo cách tôi đã hướng dẫn các hội thánh ở vùng Ga-la-ti: 2 Cứ vào ngày thứ nhất trong tuần, mỗi người trong anh chị em hãy tùy khả năng mình để riêng ra một phần lợi tức kiếm được, và để dành đó, chứ đừng đợi khi tôi đến mới quyên.  3 Khi tôi đến, tôi sẽ gởi những người được anh chị em tín nhiệm mang thư và món quà của anh chị em về Giê-ru-sa-lem, 4 và nếu cần, tôi cũng sẽ đi, và những người ấy sẽ đi với tôi.

                """],
            ["Chương Trình của Phao-lô": """
                5 Tôi sẽ đến thăm anh chị em sau khi tôi đi xuyên qua vùng Ma-xê-đô-ni-a, vì tôi định sẽ đi xuyên qua vùng Ma-xê-đô-ni-a, 6 và có lẽ tôi sẽ ở lại với anh chị em một thời gian, có thể suốt mùa đông, rồi sau đó mong anh chị em sẽ đưa tôi đến những nơi tôi định đi.  7 Lần nầy nếu Chúa cho phép, tôi không muốn chỉ ghé thăm anh chị em rồi đi ngay, nhưng tôi hy vọng có thể ở lại với anh chị em ít lâu.  8 Nhưng bây giờ tôi phải ở lại Ê-phê-sô cho đến Lễ Ngũ Tuần, 9 vì một cánh cửa lớn mang lại nhiều kết quả đang mở rộng cho tôi, mặc dù có nhiều kẻ chống đối.
                10 Nếu Ti-mô-thê đến, xin anh chị em đừng làm anh ấy sợ, vì anh ấy cũng làm công việc Chúa như tôi.  11 Vậy xin đừng ai khinh dể anh ấy, nhưng hãy tiễn anh ấy ra đi bình an để anh ấy trở về với tôi, vì tôi đang trông đợi anh ấy với các anh em khác đến đây.
                12 Về A-pô-lô anh em chúng ta, tôi đã hết sức thúc giục anh ấy đi với các anh em khác đến thăm anh chị em, nhưng anh ấy chưa muốn đi bây giờ.  Anh ấy sẽ đi khi có cơ hội.

                """],
            ["Những Lời Khuyên Cuối Thư": """
                13 Xin anh chị em hãy tỉnh thức, hãy đứng vững trong đức tin, hãy chứng tỏ khí phách của những bậc trượng phu, hãy mạnh mẽ.  14 Mọi điều anh chị em làm, hãy làm trong tình yêu thương.
                15 Thưa anh chị em, tôi xin khuyên anh chị em điều nầy nữa: Anh chị em đều biết những người trong gia đình của Tê-pha-na; họ là những trái đầu mùa ở vùng A-chai, và họ đã hết lòng phục vụ các thánh đồ.  16 Xin anh chị em hãy thuận phục những người ấy và thuận phục những người cùng làm việc khó nhọc và vất vả với họ.
                17 Tôi rất vui vì Tê-pha-na, Phô-tu-na-tu, và A-chai-cơ đã đến đây.  Các anh em ấy đã bù lại sự thiếu sót của anh chị em, 18 vì các anh em ấy đã làm cho tinh thần tôi và của anh chị em được tươi mới.  Vậy hãy quý trọng những người như thế.
                19 Các hội thánh ở vùng A-si-a gởi lời chào thăm anh chị em.  A-qui-la và Pơ-rít-ca với hội thánh nhóm họp trong nhà họ gởi lời chào thăm nồng nàn trong Chúa đến anh chị em.
                20 Tất cả anh chị em ở đây gởi lời chào thăm anh chị em.
                Hãy chào nhau bằng nụ hôn thánh.
                21 Tôi, Phao-lô, viết lời chào thăm nầy bằng chính tay tôi.
                22 Nếu ai không yêu mến Chúa, người ấy thật đáng bị nguyền rủa!
                Lạy Chúa, xin Ngài mau đến!
                23 Nguyện xin ân sủng của Ðức Chúa Jesus ở với anh chị em.  24 Tình thương của tôi ở với tất cả anh chị em trong Ðức Chúa Jesus Christ.  A-men.

                """]
            ])
    ]
    
}

