
class IICoRinhTo: Book {
    
    override init() {
        super.init()
        title = "II CÔ-RINH-TÔ"
        chapters = allChapters
        allChapters.forEach{ $0.book = self }
    }
    
    var allChapters: [Chapter] = [
        Chapter(1, passages: [
            ["Lời Mở Ðầu": """
                1 Phao-lô, theo ý muốn Ðức Chúa Trời làm sứ đồ của Ðức Chúa Jesus Christ, và Ti-mô-thê anh em chúng ta, kính gởi hội thánh của Ðức Chúa Trời tại Cô-rinh-tô với tất cả các thánh đồ ở khắp miền A-chai.  2 Nguyện xin ân sủng và bình an từ Ðức Chúa Trời, Cha chúng ta, và từ Ðức Chúa Jesus Christ, Chúa chúng ta, đến với anh chị em.

                """],
            ["Cảm Tạ Sau Khi Chịu Khổ": """
                3 Tôn ngợi Ðức Chúa Trời, Cha của Ðức Chúa Jesus Christ, Chúa chúng ta.  Ngài là Cha thương xót và Ðức Chúa Trời của mọi niềm an ủi. 4 Ngài an ủi chúng ta trong mọi cơn đau buồn, để chúng ta có thể an ủi những người khác trong mọi cơn đau buồn của họ bằng niềm an ủi mà chính chúng ta đã được Ðức Chúa Trời an ủi.  5 Vì khi chúng ta càng mang lấy những đau đớn của Ðấng Christ nhiều bao nhiêu, thì nhờ Ðấng Christ chúng ta càng nhận được nhiều an ủi bấy nhiêu.
                6 Nếu chúng tôi phải mang lấy đau buồn ấy là để anh chị em được an ủi và được cứu.  Nếu chúng tôi được an ủi ấy là để anh chị em được an ủi, và kinh nghiệm đó sẽ tạo cho anh chị em khả năng chịu đựng những đau đớn, giống như những đau đớn chúng tôi đã từng chịu.  7 Hy vọng của chúng tôi về anh chị em thật vững chắc, vì chúng tôi biết rằng anh chị em chia sẻ những đau đớn với chúng tôi thể nào, anh chị em cũng sẽ chia sẻ niềm an ủi với chúng tôi thể ấy.
                8 Thưa anh chị em, chúng tôi không muốn anh chị em không biết về những đau buồn đã xảy ra cho chúng tôi ở vùng A-si-a; những đau buồn ấy thật lớn lao, quá sức chịu đựng, khiến chúng tôi gần tuyệt vọng, tưởng hết hy vọng còn sống rồi.  9 Thật vậy chúng tôi có cảm tưởng như đã lãnh bản án tử hình, nên chúng tôi không cậy vào mình nữa, nhưng cậy hoàn toàn vào Ðức Chúa Trời, Ðấng làm cho người chết sống lại.  10 Ngài đã cứu chúng tôi thoát khỏi cái chết cận kề như thế, và Ngài sẽ tiếp tục giải cứu chúng tôi.  Chúng tôi đặt hy vọng hoàn toàn nơi Ngài rằng Ngài sẽ tiếp tục giải cứu chúng tôi.  11 Xin anh chị em hỗ trợ chúng tôi trong lời cầu nguyện, để nhờ nhiều người cầu thay mà chúng tôi được ơn, và do đó nhiều người sẽ vì cớ chúng tôi dâng lời tạ ơn Chúa.

                """],
            ["Giải Thích Sự Thay Ðổi Chương Trình": """
                12 Ðiều chúng tôi hãnh diện là thế nầy, và có lương tâm chúng tôi làm chứng: Chúng tôi cư xử giữa thế gian và đặc biệt với anh chị em bằng sự đơn thành và chân thật của Ðức Chúa Trời, không bằng sự khôn ngoan xác thịt, nhưng bằng ân sủng của Ðức Chúa Trời.  13 Vì chúng tôi viết cho anh chị em không gì khác hơn những điều anh chị em đã đọc và hiểu.  Tôi hy vọng anh chị em sẽ thấu hiểu tận tường 14 –như anh chị em đã hiểu chúng tôi phần nào– rằng trong ngày của Ðức Chúa Jesus, Chúa chúng ta, chúng tôi là niềm hãnh diện của anh chị em, cũng như anh chị em là niềm hãnh diện của chúng tôi.
                15 Với niềm tin quả quyết đó, tôi dự tính sẽ đến thăm anh chị em trước, để anh chị em có thể được phước thêm lần thứ nhì.  16 Tôi muốn ghé thăm anh chị em trên đường đến Ma-xê-đô-ni-a; sau đó tôi sẽ từ Ma-xê-đô-ni-a trở lại với anh chị em, để nhờ anh chị em đưa tôi về Giu-đê.  17 Tôi dự tính như thế có phải là tôi cứ đổi tới đổi lui chăng?  Hay những gì tôi dự tính là dự tính theo xác thịt, nên cứ nói “Phải, Phải” và “Không, Không” cùng một lúc chăng?  18 Có Ðức Chúa Trời là Ðấng Thành Tín biết, lời chúng tôi nói với anh chị em không phải là vừa “Phải” và vừa “Không.”  19 Vì Con Ðức Chúa Trời là Ðức Chúa Jesus Christ, Ðấng chúng tôi –tức tôi, Sin-va-nu, và Ti-mô-thê– đã rao giảng cho anh chị em không phải là vừa “Phải” và vừa “Không,” nhưng trong Ngài luôn luôn là “Phải.”  20 Vì bất kể bao nhiêu lời hứa Ðức Chúa Trời đã hứa, trong Ngài chúng đều được trả lời là “Phải” cả.  Vì thế nhờ Ngài chúng ta có thể nói “A-men,” và dâng vinh hiển về Ðức Chúa Trời.
                21 Chính Ðức Chúa Trời đã lập vững chúng tôi với anh chị em trong Ðấng Christ, và đã xức dầu cho chúng tôi.  22 Ngài cũng đã đóng ấn trên chúng ta và ban Ðức Thánh Linh vào lòng chúng ta để làm bảo chứng.
                23 Tôi cầu xin Ðức Chúa Trời làm chứng cho linh hồn tôi rằng tôi chưa trở lại Cô-rinh-tô như dự tính bởi vì tôi muốn bỏ qua cho anh chị em.  24 Tôi không có ý ám chỉ rằng chúng tôi có quyền gì trên đức tin của anh chị em, nhưng chúng tôi chỉ muốn làm những bạn đồng lao với anh chị em để phục vụ niềm vui của anh chị em, vì anh chị em đang đứng vững trong đức tin của mình.

                """]
            ]),
        Chapter(2, passages: [
            ["": """
                1 Vì thế tôi đã quyết định không trở lại thăm để khỏi làm anh chị em đau buồn.  2 Vì nếu tôi đã làm anh chị em đau buồn, thì ai sẽ là người làm tôi vui trở lại, nếu không phải là những người tôi đã làm đau buồn?  3 Tôi viết điều nầy cho anh chị em để khi tôi đến, tôi sẽ không bị đau buồn bởi những người đáng lý phải làm tôi vui; nhưng tôi tin tưởng nơi anh chị em rằng tất cả anh chị em sẽ lấy niềm vui của tôi làm niềm vui của mình.  4 Vì tôi viết cho anh chị em mà trong lòng buồn đau và quặn thắt, với nước mắt dầm dề, không phải để làm anh chị em đau buồn, nhưng để anh chị em biết rằng tôi thương anh chị em tha thiết biết bao.

                """],
            ["Tha Thứ Kẻ Phạm Tội": """
                5 Nếu người nào đã gây nên đau buồn, người ấy không chỉ đã làm tôi đau buồn, nhưng ít nhiều cũng đã làm tất cả anh chị em đau buồn nữa; tôi không nói quá lời đâu.  6 Người ấy đã bị đa số anh chị em trừng phạt như vậy cũng đủ rồi, 7 nên bây giờ xin anh chị em làm ngược lại mà tha thứ và an ủi người ấy, kẻo người ấy bị sự đau buồn quá lớn nuốt mất.  8 Vậy tôi khuyên anh chị em hãy tái xác nhận cho người ấy biết rằng anh chị em vẫn còn yêu thương người ấy.  9 Vì mục đích đó mà tôi đã viết cho anh chị em, để thử xem anh chị em có vâng lời trong mọi sự chăng.  10 Bây giờ hễ anh chị em tha thứ ai, thì tôi cũng tha thứ người ấy.  Nếu tôi tha thứ ai, ấy là vì cớ anh chị em mà tha thứ trước mặt Ðấng Christ, 11 để Sa-tan không thể thừa cơ đánh phá chúng ta, vì chúng ta không lạ gì mưu chước của nó.

                """],
            ["Mối Quan Tâm của Phao-lô Khi Ở Trô-ách": """
                12 Khi tôi đến Trô-ách để rao giảng Tin Mừng của Ðấng Christ, Chúa đã mở một cánh cửa cho tôi ở đó, 13 nhưng tôi không được an tâm, vì tôi không tìm được anh em tôi là Tít ở đó, nên tôi đành tạm biệt họ để đi qua Ma-xê-đô-ni-a.

                """],
            ["Ðắc Thắng Nhờ Ðấng Christ": """
                14 Nhưng tạ ơn Ðức Chúa Trời, vì Ngài luôn luôn làm cho chúng tôi được đắc thắng vẻ vang trong Ðấng Christ, và đã dùng chúng tôi tỏa lan mùi thơm về sự hiểu biết Ngài ra khắp nơi.  15 Vì chúng tôi là hương thơm của Ðấng Christ được dâng lên Ðức Chúa Trời giữa những người được cứu và những người bị hư mất.  16 Ðối với những người bị hư mất, chúng tôi là mùi tử khí để họ biết rằng họ đang tiến dần đến sự chết, nhưng đối với những người được cứu, chúng tôi là mùi sinh khí dẫn họ đến sự sống.  Ai có khả năng làm những điều ấy chăng?  17 Thật vậy chúng tôi không rao giảng lời của Ðức Chúa Trời để kiếm sống như nhiều người đang làm, nhưng với tư cách là những người được Ðức Chúa Trời sai phái trong Ðấng Christ, chúng tôi đã rao giảng cách chân thành trước mặt Ðức Chúa Trời.

                """]
            ]),
        Chapter(3, passages: [
            ["Các Ðầy Tớ của Giao Ước Mới": """
                1 Có phải chúng tôi lại bắt đầu nói về mình chăng?  Chúng tôi phải cần ai viết thư giới thiệu chúng tôi với anh chị em hay nhờ anh chị em viết thư giới thiệu chúng tôi với ai như mấy người khác chăng?  2 Chính anh chị em là bức thư của chúng tôi, được viết trong lòng chúng tôi, được mọi người biết và đọc.  3 Anh chị em đã chứng tỏ rằng anh chị em là bức thư của Ðấng Christ, là kết quả của chức vụ chúng tôi, không phải viết bằng mực, nhưng bằng Ðức Thánh Linh của Ðức Chúa Trời hằng sống, không phải viết trên những bảng bằng đá, nhưng trên những bảng bằng thịt của lòng người.
                4 Nhờ Ðấng Christ chúng tôi có được niềm tin vững vàng như thế về Ðức Chúa Trời.  5 Chúng tôi không cho rằng nhờ khả năng mình mà chúng tôi đã làm được việc gì, nhưng khả năng chúng tôi có được là do Ðức Chúa Trời ban.  6 Ngài là Ðấng đã ban cho chúng tôi khả năng làm những đầy tớ của giao ước mới, không phải giao ước bằng văn tự, nhưng giao ước bằng Ðức Thánh Linh, vì văn tự giết chết, nhưng Ðức Thánh Linh làm cho sống.
                7 Vậy nếu chức vụ của sự chết được ghi khắc bằng văn tự trên những bảng đá mà còn được vinh hiển dường ấy, đến nỗi dân I-sơ-ra-ên không thể nhìn vào mặt Môi-se vì hào quang rực rỡ nhưng chóng phai tàn trên mặt ông, 8 thì chức vụ của Ðức Thánh Linh lại càng không vinh hiển nhiều hơn sao?  9 Vì nếu chức vụ của sự kết án mà còn được vinh hiển dường ấy, thì chức vụ của sự công chính càng được vinh hiển nhiều hơn biết dường nào.  10 Thật vậy về trường hợp nầy, những gì vốn đã vinh hiển không còn được vinh hiển nữa, vì vinh hiển sau quá rực rỡ.  11 Vì nếu những gì chóng qua mà còn được vinh hiển như thế, thì những gì trường tồn sẽ được vinh hiển nhiều hơn biết dường bao.
                12 Vì có niềm hy vọng như thế, nên chúng tôi đã hành động bạo dạn.  13 Chúng tôi không như Môi-se, người phải lấy một tấm màn che mặt lại, để dân I-sơ-ra-ên khỏi nhìn thấy ánh hào quang chóng phai tàn.  14 Thế mà tâm trí họ vẫn tối tăm, vì cho đến ngày nay, khi đọc Cựu Ước, tấm màn che ấy vẫn còn chưa được gỡ đi, bởi vì chỉ trong Ðấng Christ tấm màn ấy mới bị bỏ đi.  15 Nhưng cho đến ngày nay, mỗi khi nghe đọc Luật Pháp của Môi-se, tấm màn che kín lòng họ vẫn còn đó.  16 Chỉ khi nào một người quay về với Chúa, tấm màn ấy mới được cất khỏi người ấy.  17 Chúa là Ðức Thánh Linh; nơi nào có Ðức Thánh Linh của Chúa, nơi đó có tự do.  18 Tất cả chúng ta để mặt không màn che ngắm xem vinh hiển của Chúa như thể được phản chiếu qua một tấm gương, và nhờ Chúa là Ðức Thánh Linh, chúng ta đang được biến đổi dần dần để trở nên giống như hình ảnh Ngài, từ mức độ vinh hiển bình thường đến mức độ cực kỳ vinh hiển.

                """]
            ]),
        Chapter(4, passages: [
            ["Bửu Vật trong Bình Ðất": """
                1 Vì vậy nhờ ơn thương xót của Ðức Chúa Trời, chúng tôi được giao cho chức vụ nầy, nên chúng tôi chẳng ngã lòng. 2 Ngược lại chúng tôi khước từ mọi đường lối ám muội và đáng xấu hổ.  Chúng tôi không sử dụng những phương thức xảo quyệt hoặc giả mạo lời của Ðức Chúa Trời, nhưng cứ thẳng thắn trình bày chân lý và để lương tâm mọi người nhận định về chúng tôi trước mặt Ðức Chúa Trời.  3 Nếu Tin Mừng chúng tôi rao giảng bị che khuất ấy là bị che khuất đối với những kẻ đang chết mất, 4 vì thần của đời nầy đã làm mù tâm trí những kẻ không tin để họ không trông thấy ánh sáng của Tin Mừng đang tỏa rạng vinh quang của Ðấng Christ, là hình ảnh của Ðức Chúa Trời.  5 Vì chúng tôi chẳng giảng về chính mình nhưng giảng về Ðức Chúa Jesus Christ là Chúa, và vì cớ Ðức Chúa Jesus, chúng tôi là đầy tớ của anh chị em, 6 vì Ðức Chúa Trời là Ðấng đã phán,
                “Ánh sáng hãy chiếu ra từ cõi tối tăm,”
                đã chiếu sáng lòng chúng tôi, ban cho chúng tôi ánh sáng của trí tuệ để nhận biết vinh hiển của Ðức Chúa Trời đang rạng ngời trên gương mặt Ðức Chúa Jesus Christ.
                7 Chúng tôi đựng bửu vật nầy trong những bình bằng đất để bày tỏ rằng quyền năng diệu kỳ là của Ðức Chúa Trời, chứ không phải của chúng tôi.  8 Chúng tôi bị áp lực đủ mọi mặt nhưng không bị nghiền nát, bị bối rối nhưng không hề tuyệt vọng, 9 bị bách hại nhưng không bị bỏ rơi, bị quật ngã nhưng không bị tiêu diệt.  10 Chúng tôi luôn mang sự chết của Ðức Chúa Jesus trong thân thể mình, để sự sống của Ðức Chúa Jesus cũng được thể hiện trong thân thể chúng tôi.  11 Dù chúng tôi đang sống, nhưng vì cớ Ðức Chúa Jesus lúc nào chúng tôi cũng sẵn sàng chết, để sự sống của Ðức Chúa Jesus được thể hiện trong thân thể sẽ chết của chúng tôi.  12 Thế thì sự chết đang hành động trong chúng tôi, nhưng sự sống đang hành động trong anh chị em.
                13 Do có cùng một tinh thần đức tin như lời đã chép,
                “Tôi tin nên tôi nói,”
                chúng tôi cũng tin nên chúng tôi cũng nói; 14 vì chúng tôi biết rằng Ðấng đã làm cho Ðức Chúa Jesus sống lại cũng sẽ làm cho chúng ta sống lại với Ðức Chúa Jesus và sẽ đem chúng tôi và anh chị em đến trình diện trước mặt Ngài.
                15 Vậy mọi sự đã được thực hiện vì cớ anh chị em, để có nhiều người nhận được ân sủng của Ðức Chúa Trời hơn, và sự tạ ơn Ngài nhờ thế được gia tăng nhiều hơn, hầu đem vinh hiển về Ðức Chúa Trời.

                """],
            ["Sống Bởi Ðức Tin": """
                16 Vì vậy chúng ta không ngã lòng; dù con người bên ngoài đang tàn tạ, nhưng con người bên trong vẫn mỗi ngày một đổi mới.  17 Vì hoạn nạn tạm và nhẹ của chúng ta hiện nay sẽ đem lại cho chúng ta vinh hiển đời đời vô lượng vô biên, 18 bởi chúng ta không nhìn chăm vào những gì thấy được, nhưng vào những gì không thấy được, vì những gì thấy được chỉ là tạm thời, còn những gì không thấy được mới là đời đời bất diệt.

                """]
            ]),
        Chapter(5, passages: [
            ["Chỗ Ở Trên Trời": """
                1 Vì chúng ta biết rằng nếu căn lều tạm của chúng ta, nơi chúng ta đang sống dưới đất nầy bị phá hủy, chúng ta có một tòa nhà đời đời trên trời, không do bàn tay loài người dựng nên nhưng do Ðức Chúa Trời.  2 Thật vậy chúng ta đang rên rỉ trong nơi ở tạm nầy, mong mỏi sớm được mặc lấy chỗ ở trên trời; 3 một khi chúng ta được mặc lấy chỗ ở ấy, chúng ta sẽ không còn trần trụi nữa.  4 Vì khi còn ở trong lều tạm nầy, chúng ta rên rỉ dưới những gánh nặng, không phải vì chúng ta muốn cổi bỏ thân xác thuộc về đất nầy, nhưng vì chúng ta muốn được mặc lấy thân thể thuộc về trời, để những gì sẽ chết nầy có thể bị sự sống nuốt đi.  5 Ðấng đã chuẩn bị chúng ta cho mục đích nầy là Ðức Chúa Trời, Ðấng ban Ðức Thánh Linh làm bảo chứng cho chúng ta.
                6 Vậy chúng ta phải luôn có niềm tin vững vàng đó, và biết rằng khi chúng ta còn ở trong thân thể nầy, chúng ta còn ở ngoài thân thể Chúa sẽ ban.  7 Vì chúng ta bước đi bởi đức tin, chứ không phải bởi mắt thấy.
                8 Do chúng tôi có niềm tin vững vàng đó, chúng tôi nghĩ rằng thà vắng mặt khỏi thân xác để về hiện diện với Chúa thì hơn.  9 Vì vậy dù ở trong thân xác nầy hay dù ra khỏi, mục đích của chúng ta vẫn là làm vui lòng Chúa.  10 Vì tất cả chúng ta phải trình diện trước tòa của Ðấng Christ, để mỗi người được báo trả xứng đáng cho những việc tốt hay xấu mình làm lúc còn trong thân xác.

                """],
            ["Chức Vụ Giải Hòa": """
                11 Vậy do biết kính sợ Chúa, chúng tôi cố gắng thuyết phục mọi người.  Ðức Chúa Trời biết rõ chúng tôi và tôi hy vọng rằng lương tâm anh chị em cũng biết rõ chúng tôi.  12 Chúng tôi không muốn lại nói về mình với anh chị em, nhưng muốn cho anh chị em có cơ hội để hãnh diện về chúng tôi, hầu có thể đối đáp với những kẻ thích phô trương bề ngoài nhưng không có thực chất trong lòng.  13 Vì nếu chúng tôi cuồng nhiệt, ấy là vì Ðức Chúa Trời; hoặc nếu chúng tôi thận trọng, ấy là vì anh chị em.
                14 Vì tình yêu của Ðấng Christ thúc giục chúng tôi, chúng tôi tin rằng, khi một người đã chết thay cho mọi người thì mọi người coi như đã chết, 15 và vì Ngài đã chết thay cho mọi người, nên những người đang sống không nên sống cho mình nữa, nhưng hãy sống cho Ðấng đã chết và đã sống lại cho mình.
                16 Vậy từ nay trở đi chúng tôi không nhận thức ai theo xác thịt nữa, dù rằng đã có lần chúng tôi nhận thức Ðấng Christ theo xác thịt, nhưng nay chúng tôi không nhận thức Ngài theo cách ấy nữa.  17 Vậy nếu ai ở trong Ðấng Christ thì người ấy là một tạo vật mới; những gì cũ đã qua đi; nầy, mọi sự đều trở nên mới.
                18 Mọi điều ấy đều đến từ Ðức Chúa Trời, Ðấng đã giải hòa chúng ta với chính Ngài qua Ðấng Christ và đã ban cho chúng ta chức vụ giải hòa; 19 hay nói cách khác, trong Ðấng Christ, Ðức Chúa Trời đang giải hòa thế gian với chính Ngài, không kể đến các vi phạm của họ nữa, và đã trao cho chúng ta sứ điệp giải hòa.  20 Vậy chúng ta là những đại sứ của Ðấng Christ, như thể Ðức Chúa Trời đang mời gọi qua chúng ta.  Thay cho Ðấng Christ chúng tôi nài xin anh chị em: hãy làm hòa với Ðức Chúa Trời.  21 Vì cớ chúng ta, Ðức Chúa Trời đã khiến Ðấng không biết tội lỗi thành người có tội, để nhờ ở trong Ngài, chúng ta trở nên những người công chính trước mặt Ðức Chúa Trời.

                """]
            ]),
        Chapter(6, passages: [
            ["Những Gian Khó Trong Chức Vụ Hầu Việc Chúa": """
                1 Với tư cách những người cùng làm việc với Chúa, chúng tôi nài xin anh chị em đừng nhận ân sủng của Ðức Chúa Trời cách uổng phí, 2 vì Ngài phán,
                “Ta đã nhậm lời ngươi trong thời điểm thuận lợi.
                Ta đã phù hộ ngươi trong ngày cứu rỗi.”
                Này, bây giờ là thời điểm thuận lợi!  Này, hôm nay là ngày cứu rỗi!
                3 Chúng tôi không để điều gì làm cớ vấp ngã cho ai, kẻo chức vụ của chúng tôi bị người ta chê trách.  4 Nhưng trong mọi sự chúng tôi luôn luôn chứng tỏ mình là những đầy tớ của Ðức Chúa Trời, trong sự kiên trì chịu đựng, trong những hoạn nạn, trong những gian khổ, trong những lúc khốn cùng, 5 trong những lần bị đánh đập, trong những ngày bị giam cầm, trong những khi người ta nổi loạn, trong những lúc lao động nhọc nhằn, trong những đêm thiếu ngủ, trong những ngày thiếu ăn, 6 trong sự trong sạch, trong sự hiểu biết, trong sự nhịn nhục, trong sự nhân từ, trong Ðức Thánh Linh, trong tình thương chân thật, 7 trong khi rao giảng lời chân lý, trong quyền năng Ðức Chúa Trời.  Chúng tôi dùng sự công chính làm vũ khí để tấn công và tự vệ, 8 khi được vinh hiển cũng như khi bị tủi nhục, khi bị chê bai cũng như khi được khen ngợi. Chúng tôi bị tưởng như những kẻ lừa đảo nhưng là những người chân thật, 9 tưởng như những kẻ vô danh tiểu tốt nhưng lại được nhiều người biết đến, tưởng như những kẻ sắp chết đến nơi, nhưng xem đây, chúng tôi vẫn sống sờ sờ, tưởng như những kẻ bị trừng phạt nhưng vẫn không bị giết chết, 10 tưởng như những kẻ phải đau buồn nhưng luôn luôn vui vẻ, tưởng như những kẻ nghèo khó nhưng đã làm cho nhiều người giàu có, tưởng như những kẻ chẳng có gì nhưng có đủ mọi sự.
                11 Thưa anh chị em người Cô-rinh-tô, chúng tôi nói thật lòng với anh chị em, chúng tôi đang mở rộng lòng chúng tôi.  12 Chúng tôi không hẹp hòi với anh chị em, nhưng lòng anh chị em hẹp hòi với chúng tôi.  13 Tôi nói với anh chị em như nói với các con cái tôi: xin hãy đối xử với chúng tôi như cách chúng tôi đã đối xử với anh chị em; xin hãy mở rộng lòng anh chị em.

                """],
            ["Cảnh Cáo về Sự Kết Hiệp với Quyền Lực Ðối Nghịch Thuộc Linh": """
                14 Chớ mang ách chung với những kẻ không tin, vì công chính và gian tà có hợp tác với nhau được chăng?  Ánh sáng và bóng tối có hiệp thông được chăng?  15 Ðấng Christ và Bê-li-an có hòa hợp chăng?  Hay người tin Chúa có gì chung với kẻ không tin chăng?  16 Ðền thờ của Ðức Chúa Trời có thỏa hiệp gì với các thần tượng chăng?  Vì chúng ta là đền thờ của Ðức Chúa Trời hằng sống, như Ðức Chúa Trời đã phán,
                “Ta sẽ ở giữa họ và đi lại giữa họ,
                Ta sẽ là Ðức Chúa Trời của họ,
                Và họ sẽ làm dân Ta.
                17 Vậy hãy ra khỏi chúng nó,
                Và hãy phân rẽ khỏi chúng nó,
                Chúa phán,
                Ðừng đụng đến đồ ô uế,
                Thì Ta sẽ tiếp nhận các ngươi.
                18 Ta sẽ làm Cha các ngươi,
                Các ngươi sẽ làm con trai và con gái Ta,
                Chúa Toàn Năng phán vậy.”

                """]
            ]),
        Chapter(7, passages: [
            ["": """
                1 Anh chị em yêu dấu, vì chúng ta có những lời hứa ấy, hãy tẩy sạch khỏi chúng ta mọi thứ ô uế của thể xác và tâm linh, để được hoàn toàn thánh hóa trong sự kính sợ Ðức Chúa Trời.

                """],
            ["Niềm Vui của Phao-lô": """
                2 Xin dành cho chúng tôi một chỗ trong lòng anh chị em; chúng tôi chưa hề làm gì sai với ai, chúng tôi chưa hề làm hại ai, chúng tôi chưa hề lợi dụng ai.  3 Tôi không nói thế để lên án anh chị em, vì như tôi đã nói trước đây, anh chị em luôn ở trong lòng tôi, như thể chúng ta sống chết có nhau.  4 Tôi rất tin tưởng nơi anh chị em và rất hãnh diện về anh chị em; tôi đã được đầy tràn an ủi; tôi đã được tràn ngập niềm vui ngay giữa lúc chúng tôi chịu mọi thứ hoạn nạn.
                5 Thật vậy khi chúng tôi đến Ma-xê-đô-ni-a, thể xác chúng tôi không được nghỉ ngơi chút nào, nhưng chúng tôi gặp khốn khó mọi bề; bên ngoài phải đối phó với những tấn công, bên trong phải đương đầu với những lo sợ.  6 Nhưng Ðức Chúa Trời, Ðấng an ủi những kẻ ngã lòng, đã an ủi chúng tôi bằng cách sai Tít đến.  7 Chúng tôi không những đã được an ủi vì Tít đến, nhưng còn được an ủi vì sự an ủi anh ấy đã nhận được từ anh chị em.  Anh ấy đã tường thuật cho chúng tôi biết niềm khao khát, nỗi thở than, và lòng nhiệt thành của anh chị em dành cho tôi; do đó tôi càng vui mừng hơn.

                """],
            ["Sự Ðau Buồn Theo Ý Chúa": """
                8 Nếu như trong thư tôi có làm cho anh chị em đau buồn, tôi cũng không hối tiếc.  Giả như tôi có hối tiếc đi nữa, vì tôi thấy bức thư ấy đã làm cho anh chị em đau buồn trong ít lâu, 9 thì nay tôi lại vui mừng; không phải vui mừng vì thấy anh chị em đau buồn, nhưng vui mừng vì sự đau buồn ấy đã đưa đến sự ăn năn; vì anh chị em đau buồn theo ý Ðức Chúa Trời, nên chúng tôi đã không gây thiệt hại gì cho anh chị em, 10 vì sự đau buồn theo ý Ðức Chúa Trời đưa đến sự ăn năn để được cứu; đó là điều không có gì đáng phải hối tiếc, nhưng sự đau buồn theo kiểu thế gian ắt đưa đến sự chết.  11 Vì nầy, sự đau buồn theo ý Ðức Chúa Trời đã tạo nên sự nhiệt tình cho anh chị em như thế nào, rồi tiếp theo đó là biện minh, phẫn nộ, lo sợ, khao khát, nhiệt thành, và sửa phạt.  Trong mọi sự anh chị em đã chứng tỏ anh chị em trong sạch trong việc nầy.
                12 Vậy dù tôi đã viết cho anh chị em, nhưng tôi làm thế không phải vì cớ kẻ đã làm sai, cũng không phải vì cớ người đã bị làm hại, nhưng để sự nhiệt tình của anh chị em đối với chúng tôi được tỏ ra cho anh chị em trước mặt Ðức Chúa Trời.  13 Do đó chúng tôi đã được an ủi.
                Ngoài sự an ủi đó, chúng tôi lại được vui mừng nhiều hơn vì thấy Tít thật vui vẻ, bởi tất cả anh chị em đã làm cho tâm linh anh ấy được tươi mới.  14 Vì nếu tôi đã khoe về anh chị em với anh ấy điều gì thì tôi đã không bị hổ thẹn; vì tất cả những gì tôi nói với anh chị em đều là sự thật như thế nào, thì những gì chúng tôi khoe về anh chị em trước mặt Tít đã được chứng tỏ là đúng sự thật cũng thể ấy.  15 Lòng quý mến của anh ấy đối với anh chị em đã gia tăng bội phần, khi anh ấy nhớ lại thế nào tất cả anh chị em đã vâng lời anh ấy, lo ngại và lo sợ khi đón tiếp anh ấy.  16 Tôi thật vui mừng, vì trong mọi sự tôi có thể tin tưởng nơi anh chị em.
                
                """]
            ]),
        Chapter(8, passages: [
            ["Lòng Dâng Hiến Rộng Rãi": """
                1 Thưa anh chị em, chúng tôi muốn anh chị em biết về ân sủng Ðức Chúa Trời đã ban cho các hội thánh ở Ma-xê-đô-ni-a; 2 đó là trong khi họ chịu hoạn nạn thử thách nặng nề, lòng họ vẫn đầy niềm vui; và trong khi họ chịu cảnh nghèo khó cùng cực, lòng rộng rãi của họ vẫn cứ giàu thêm.  3 Tôi có thể làm chứng rằng họ đã tự động quyên góp không những theo khả năng của họ, nhưng còn quá khả năng của họ.  4 Họ tha thiết nài xin chúng tôi cho họ được dự phần trong sự phục vụ các thánh đồ.  5 Họ đã làm việc ấy vượt quá điều chúng tôi mong ước; trước hết họ dâng chính mình cho Chúa, rồi theo ý Ðức Chúa Trời, cho chúng tôi nữa.
                6 Vì thế chúng tôi đã thúc giục Tít cố gắng hoàn tất công việc phúc thiện nầy giữa anh chị em như anh ấy đã khởi sự làm.  7 Như anh chị em đã trỗi hơn trong mọi phương diện, nào là đức tin, lời nói, kiến thức, sự tích cực về mọi sự, và tình thương dành cho chúng tôi, mong rằng anh chị em cũng sẽ trỗi hơn trong việc phúc thiện nầy nữa.
                8 Tôi nói vậy không có ý ra lệnh cho anh chị em làm điều ấy đâu, nhưng tôi muốn nêu lên sự nhiệt tình của những người khác để xem tình yêu thương của anh chị em chân thành như thế nào.  9 Vì anh chị em đã biết ân sủng của Ðức Chúa Jesus Christ, Chúa chúng ta, ra sao; Ngài vốn giàu nhưng vì anh chị em đã trở nên nghèo, để nhờ sự nghèo khó của Ngài, anh chị em được trở nên giàu.
                10 Về việc nầy tôi xin đưa ra một ý kiến mà tôi nghĩ là có lợi cho anh chị em, đó là năm trước không những anh chị em đã nghĩ phải làm một việc gì, mà còn rất muốn làm, và đã bắt đầu trước, 11 thì bây giờ xin anh chị em hãy hoàn tất việc ấy trong khả năng mình, theo lòng nhiệt thành đã khiến anh chị em khởi sự.  12 Thật vậy những gì chúng ta có và dâng theo lòng nhiệt thành của mình mới quý, chứ không phải những gì chúng ta không có.  13 Tôi không có ý khuyên anh chị em phải chịu khốn khó để giúp những người khác vơi đi phần nào nỗi khốn khó của họ, nhưng tôi chỉ mong có sự quân bình.  14 Hiện tại anh chị em đang dư dả, xin hãy giúp họ trong lúc họ bị túng thiếu, để khi họ được dư dả, họ sẽ giúp lại anh chị em khi anh chị em lâm cảnh túng thiếu.  Như thế là có sự quân bình, 15 như có chép rằng,
                “Người lượm nhiều cũng không dư, và người lượm ít cũng chẳng thiếu.”

                """],
            ["Giới Thiệu Tít và Các Bạn Ðồng Hành": """
                16 Cảm tạ Ðức Chúa Trời, Ðấng đã đặt vào lòng Tít sự quan tâm nhiệt tình về anh chị em như chúng tôi.  17 Vì không những anh ấy đã nhận sự khuyến khích của chúng tôi mà cũng do sự nhiệt tình của anh ấy, anh ấy đã tự nguyện đến với anh chị em.  18 Chúng tôi phái một anh em được khen ngợi trong việc rao giảng Tin Mừng trong khắp các hội thánh cùng đi với anh ấy.  19 Không những thế, người anh em nầy còn được tất cả các hội thánh cử làm bạn đồng hành với chúng tôi, trong khi chúng tôi thực hiện công tác phúc thiện nầy để làm vinh hiển danh Chúa và cũng để bảo đảm cho lòng nhiệt thành của chúng tôi.  20 Chúng tôi phải thận trọng như thế để không ai có thể chỉ trích chúng tôi trong việc thực hiện công tác phúc thiện lớn lao nầy, 21 vì chúng tôi đã quyết tâm làm những việc nầy cách tốt đẹp không những trước mặt Chúa nhưng trước mặt người ta nữa.
                22 Cùng đi với họ, chúng tôi phái thêm một anh em nữa của chúng tôi; anh ấy là người đã được chúng tôi thử nghiệm nhiều lần và thấy anh ấy mẫn cán trong mọi việc; nay anh ấy lại càng mẫn cán hơn, vì anh ấy rất tin tưởng anh chị em.
                23 Về phần Tít, anh ấy là người cộng sự của tôi và là bạn đồng lao với tôi trong sự phục vụ anh chị em.  Còn các anh em kia của chúng ta là các sứ giả của các hội thánh, vinh hiển của Ðấng Christ.
                24 Như vậy xin anh chị em hãy chứng tỏ cho họ tình yêu thương của anh chị em và lý do khiến chúng tôi hãnh diện về anh chị em là không sai để các hội thánh đều thấy.

                """]
            ]),
        Chapter(9, passages: [
            ["Lạc Quyên Giúp Các Tín Hữu Gặp Cảnh Khốn Cùng": """
                1 Về việc lạc quyên giúp các thánh đồ, tôi không cần viết gì thêm cho anh chị em nữa, 2 vì tôi biết anh chị em rất nhiệt tình về việc ấy; đó là điều tôi đã khoe với anh chị em ở Ma-xê-đô-ni-a rằng anh chị em ở A-chai đã chuẩn bị từ năm trước, và sự nhiệt tình của anh chị em quả đã động viên nhiều người của họ.  3 Nay tôi gởi các anh em nầy đến với anh chị em, để chứng tỏ rằng lời khoe của tôi về anh chị em không phải là rỗng tuếch, mà anh chị em thật sự đã chuẩn bị như tôi đã nói.  4 Tôi chỉ lo là nếu vài anh em ở Ma-xê-đô-ni-a đến với chúng tôi, và họ thấy anh chị em chưa chuẩn bị gì cả, khi ấy chắc chúng tôi sẽ mắc cỡ lắm; còn anh chị em thì khỏi phải nói rồi, bởi vì chúng tôi đã quá tin tưởng anh chị em.  5 Vì thế tôi thấy cần phải khuyến khích các anh em nầy đến với anh chị em trước và chuẩn bị sẵn sàng những gì anh chị em đã hứa cho công tác phúc thiện đó, để việc ấy sẽ đúng là một món quà hào phóng, chứ không là một việc làm miễn cưỡng.
                6 Xin anh chị em nhớ rằng ai gieo ít sẽ gặt ít, ai gieo nhiều sẽ gặt nhiều.  7 Mỗi người hãy theo lòng mình đã định mà dâng hiến, không dâng một cách miễn cưỡng hoặc bị cưỡng ép, vì Ðức Chúa Trời yêu người dâng hiến cách vui lòng.  8 Ðức Chúa Trời có khả năng ban cho anh chị em mọi ân phước cách dư dật, để anh chị em luôn luôn đầy đủ trong mọi phương diện, hầu có thể chia sẻ rời rộng trong mọi việc phúc thiện, 9 như có chép rằng,
                “Người nào rải của mình ra giúp người nghèo khổ,
                Công đức của người ấy sẽ trường tồn mãi mãi.”
                10 Nguyện Ðấng cung cấp hạt giống cho người gieo và cơm bánh làm lương thực chu cấp hạt giống và khiến chúng sinh lợi bội phần cho anh chị em, và nguyện Ngài làm gia tăng kết quả công đức của anh chị em.  11 Nguyện anh chị em được giàu có trong mọi phương diện, để anh chị em luôn rộng rãi trong mọi việc, hầu qua việc làm của chúng ta, nhiều người sẽ tạ ơn Ðức Chúa Trời.  12 Vì công tác phục vụ nầy không chỉ đáp ứng nhu cầu túng thiếu của các thánh đồ, nhưng cũng tạo cơ hội cho nhiều người tạ ơn Ðức Chúa Trời.  13 Qua thành quả của sự phục vụ nầy họ sẽ tôn vinh Ðức Chúa Trời, vì anh chị em đã vâng phục Tin Mừng của Ðấng Christ mà anh chị em đã tuyên xưng, và vì sự chia sẻ rộng rãi của anh chị em cho họ và cho mọi người khác.  14 Còn họ, họ sẽ cầu nguyện cho anh chị em và quý mến anh chị em, vì ân sủng của Ðức Chúa Trời ban cho anh chị em quá đỗi dồi dào.  15 Tạ ơn Ðức Chúa Trời vì sự ban cho của Ngài không thể tả!

                """]
            ]),
        Chapter(10, passages: [
            ["Phao-lô Binh Vực Chức Vụ Ông": """
                1 Tôi, Phao-lô, là người ở trước mặt anh chị em có vẻ mềm yếu, nhưng lại cứng rắn đối với anh chị em khi vắng mặt; tôi cậy vào đức khiêm nhu và mềm mại của Ðấng Christ mà nài xin anh chị em: 2 Tôi xin anh chị em đừng đặt tôi vào thế mà khi gặp mặt phải sử dụng biện pháp cứng rắn đối với một số người đã cho rằng chúng tôi là những kẻ sống theo xác thịt.  3 Dù chúng tôi đang sống trong xác thịt, nhưng chúng tôi không chiến đấu theo xác thịt đâu, 4 vì các vũ khí chúng tôi dùng trong cuộc chiến của chúng ta không phải là thứ vũ khí xác thịt, nhưng là quyền năng thiên thượng để phá tan mọi thành lũy, đánh đổ mọi lý luận 5 và mọi chướng ngại cao ngạo chống lại sự hiểu biết Ðức Chúa Trời, và bắt nhốt mọi tư tưởng, để người ta vâng phục Ðấng Christ.  6 Sau khi anh chị em đã hoàn toàn vâng phục, chúng tôi sẵn sàng sửa trị mọi kẻ không vâng phục.
                7 Anh chị em nhìn vào bề ngoài chăng?  Nếu ai cho rằng mình thuộc về Ðấng Christ, người đó hãy nghĩ lại xem; nếu người đó là người của Ðấng Christ, chúng tôi cũng vậy.  8 Ngay cả khi tôi có tự hào ít nhiều về quyền năng Chúa ban cho chúng tôi, để xây dựng anh chị em chứ không phải để phá đổ, thì tôi cũng không có gì hổ thẹn, 9 vì tôi không muốn làm ra vẻ hù dọa anh chị em bằng thư từ.  10 Số là đã có người nói rằng, “Các thư của ông ấy có vẻ nghiêm khắc và mạnh mẽ, nhưng đến khi gặp mặt thì ông ấy yếu xìu và nói năng chẳng ra gì.”  11 Xin những người nói như thế hãy biết rằng khi vắng mặt chúng tôi nói trong thư thế nào, khi có mặt chúng tôi cũng hành động thể ấy.
                12 Chúng tôi không dám kể mình ngang hàng hoặc so sánh chúng tôi với những người tự đề cao mình đó.  Nhưng khi họ lấy mình làm tiêu chuẩn để đo nhau, hoặc so sánh mình với nhau, họ không mấy hiểu biết.  13 Còn chúng tôi, chúng tôi không dám tự hào quá đáng, nhưng chỉ ở trong phạm vi Ðức Chúa Trời đã quy định cho chúng tôi, và phạm vi đó bao gồm cả anh chị em.  14 Chúng tôi không vượt quá phạm vi của chúng tôi như thể chúng tôi chưa hề đến với anh chị em, vì chúng tôi là những người đầu tiên đem Tin Mừng của Ðấng Christ đến tận nơi anh chị em.  15 Chúng tôi không lấy công lao khó nhọc của người khác cho là của mình để tự hào quá đáng, nhưng chúng tôi hy vọng rằng, khi đức tin của anh chị em tăng trưởng, phạm vi hoạt động của chúng tôi qua anh chị em sẽ nới rộng nhiều hơn; 16 bấy giờ chúng tôi có thể rao giảng Tin Mừng ở những nơi xa xôi và không bị mang tiếng là tự hào về công việc đã thực hiện trong phạm vi hoạt động của người khác.  17 Nhưng ai muốn tự hào, hãy tự hào trong Chúa.  18 Vì không phải ai tự đề cao mình sẽ được công nhận đâu, nhưng chỉ người nào được Chúa khen ngợi mà thôi.

                """]
            ]),
        Chapter(11, passages: [
            ["Phao-lô và Các Sứ Ðồ Giả": """
                1 Tôi ước ao anh chị em có thể chịu đựng sự điên khùng của tôi một chút, và có lẽ anh chị em đã chịu đựng tôi rồi.  2 Vì tôi đang ghen cho anh chị em, một nỗi ghen thiên thượng, bởi tôi đã hứa gả anh chị em cho một người chồng, để trình diện anh chị em như một trinh nữ trong trắng lên Ðấng Christ.  3 Nhưng bây giờ tôi lo ngại rằng giống như Ê-va đã bị con rắn dùng những mưu chước quỷ quyệt lừa gạt, những suy nghĩ của anh chị em đã bị nhiễm độc, mất đi tính chất đơn thành và tinh khiết dành cho Ðấng Christ.  4 Vì nếu có ai đến rao giảng cho anh chị em một Jesus khác với Ðức Chúa Jesus chúng tôi rao giảng, hoặc giới thiệu đến anh chị em một linh khác với Ðức Thánh Linh anh chị em đã nhận lãnh, hoặc một tin mừng khác với Tin Mừng anh chị em đã tiếp nhận, có lẽ anh chị em sẽ chịu đựng những điều đó một cách dễ dàng!
                5 Tôi nghĩ rằng tôi không thua kém gì các sứ đồ siêu đẳng ấy đâu.  6 Có thể tôi không giỏi về nghệ thuật nói trước công chúng, nhưng về kiến thức tôi không thua kém gì họ; vì trong mọi hoàn cảnh và mọi sự, tôi đã chứng tỏ điều đó cho anh chị em rồi.
                7 Phải chăng tôi có tội khi hạ mình xuống để anh chị em được tôn lên, bởi vì tôi rao giảng Tin Mừng của Ðức Chúa Trời mà không đòi thù lao?  8 Tôi đã lấy từ các hội thánh khác, tức nhận sự trợ cấp tài chính của họ, để phục vụ anh chị em.  9 Khi tôi ở với anh chị em và lâm vào cảnh túng thiếu, tôi đã không trở thành gánh nặng cho ai, vì các anh em từ Ma-xê-đô-ni-a đến đã chu cấp đầy đủ các nhu cầu của tôi.  Trong mọi việc tôi luôn giữ mình để khỏi trở thành gánh nặng cho anh chị em, và tôi sẽ giữ luôn như thế.  10 Ngày nào lẽ thật của Ðấng Christ còn trong tôi, ngày ấy không ai có quyền cấm tôi không được nói lên niềm tự hào nầy của tôi trong các miền ở A-chai.  11 Tại sao như thế?  Phải chăng vì tôi không yêu thương anh chị em?  Có Ðức Chúa Trời biết.
                12 Nhưng những gì tôi đang làm, tôi sẽ tiếp tục làm, để loại trừ mọi cơ hội mà những kẻ chuyên lợi dụng cơ hội mong muốn hầu có thể khoe rằng họ cũng phục vụ như chúng tôi.  13 Những kẻ ấy là những sứ đồ giả, những viên chức gian dối, đội lốt các sứ đồ của Ðấng Christ.  14 Thật chẳng lạ gì, vì chính Sa-tan đã đội lốt một thiên sứ sáng láng.  15 Vì thế chẳng có gì lạ khi những kẻ phục vụ nó cũng đội lốt những người phục vụ sự công chính; đến ngày chung cuộc, họ sẽ chuốc lấy hậu quả của những việc họ làm.

                """],
            ["Những Gian Khổ Trong Chức Vụ của Phao-lô": """
                16 Tôi xin nói lại, xin đừng ai nghĩ tôi là một kẻ điên khùng; nhưng nếu ai nghĩ vậy, thì xin cứ nhận tôi như một kẻ điên khùng đi, để tôi cũng có thể tự hào đôi chút.  17 Những gì tôi sắp nói đây không phải là nói theo ý Chúa, nhưng nói theo ý của một kẻ điên khùng đang tự tin và tự hào.
                18 Vì đã có lắm người tự hào về những gì thuộc xác thịt, tôi cũng có thể tự hào vậy.  19 Bởi anh chị em là những người khôn ngoan mà đã hoan hỉ chịu đựng những kẻ điên khùng kia mà!  20 Nếu ai bắt anh chị em làm nô lệ, nếu ai cắn nuốt anh chị em, nếu ai tước đoạt của cải anh chị em, nếu ai lên mình hách dịch với anh chị em, thậm chí nếu ai tát vào mặt anh chị em, anh chị em cũng vẫn chịu đựng được kia mà.  21 Tôi lấy làm hổ thẹn mà nói rằng chúng tôi đã quá yếu đuối, nên không thể làm được như họ!  Nhưng nếu ai dám tự hào về bất cứ điều gì, thì tôi nói như một kẻ điên khùng rằng, tôi cũng dám tự hào về điều đó.  22 Họ là người Hê-bơ-rơ chăng?  Tôi cũng vậy.  Họ là người I-sơ-ra-ên chăng?  Tôi cũng vậy.  Họ là dòng dõi của Áp-ra-ham chăng?  Tôi cũng vậy.  23 Họ là những người phục vụ Ðấng Christ chăng?  Tôi nói như một kẻ điên khùng, tôi còn phục vụ nhiều hơn họ.  Tôi đã lao động vất vả hơn, bị tù thường xuyên hơn, bị đánh đập vô kể, biết bao lần suýt chết.  24 Năm lần tôi bị người Do-thái đánh bằng roi dây, mỗi lần thiếu một roi đầy bốn chục.  25 Ba lần tôi bị đánh đòn, một lần bị ném đá, ba lần bị chìm tàu, một ngày một đêm lênh đênh trên biển cả.  26 Trong những cuộc hành trình, tôi gặp nguy hiểm trên sông rạch, nguy hiểm với bọn cướp, nguy hiểm với đồng bào mình, nguy hiểm với các dân ngoại, nguy hiểm trong thành phố, nguy hiểm trong đồng hoang, nguy hiểm trên biển cả, nguy hiểm với anh chị em giả dối, 27 Tôi phải lao động vất vả và làm việc khó nhọc, thường khi thiếu ngủ, chịu đói chịu khát, nhiều lúc thiếu ăn, chịu rét mướt, và thiếu mặc.  28 Ngoài bao nhiêu việc khác, mỗi ngày tôi phải chịu áp lực lo lắng cho tất cả các hội thánh.  29 Có ai yếu đuối mà tôi không yếu đuối chăng?  Có ai bị vấp ngã mà tôi không như nung như đốt chăng?
                30 Nếu phải tự hào, tôi sẽ tự hào về những yếu đuối của tôi.  31 Ðức Chúa Trời, Cha của Ðức Chúa Jesus, Ðấng đáng được chúc tụng đời đời, biết rõ rằng tôi không nói dối.  32 Ở Ða-mách, quan tổng trấn dưới quyền Vua A-rê-ta đã ra lệnh canh giữ Thành Ða-mách để bắt tôi, 33 nhưng tôi đã được dòng xuống trong một cái thúng, qua cửa số, thả ra bên ngoài tường thành, và tôi đã thoát khỏi tay ông ấy.

                """]
            ]),
        Chapter(12, passages: [
            ["Khải Tượng Thiên Thượng và Mặc Khải của Chúa cho Phao-lô": """
                1 Nếu phải tự hào, dù biết rằng chẳng có lợi ích gì, thì tôi sẽ đề cập đến những khải tượng và những mặc khải Chúa ban.  2 Tôi biết một người trong Ðấng Christ, mười bốn năm trước đã được cất lên tầng trời thứ ba, hoặc trong thân thể người ấy hoặc ngoài thân thể người ấy, tôi không biết, có Ðức Chúa Trời biết.  3 Tôi biết người ấy, hoặc trong thân thể người ấy hoặc ngoài thân thể người ấy, tôi không biết, có Ðức Chúa Trời biết, 4 đã được đưa vào nơi phước hạnh, và được nghe những lời không thể diễn tả, là những điều phàm nhân không được phép kể lại.
                5 Về người ấy, tôi sẽ tự hào, nhưng về chính tôi, tôi sẽ không tự hào, ngoại trừ tự hào về những yếu đuối của tôi.  6 Vì nếu tôi muốn tự hào, tôi sẽ không dại đâu, bởi tôi sẽ nói sự thật.  Tuy nhiên tôi phải tự kiềm chế, để không ai nghĩ rằng tôi làm cho mình có giá hơn những gì họ đã thấy nơi tôi hoặc đã nghe nơi tôi.
                7 Vậy để giữ tôi khỏi lên mình kiêu ngạo, đặc biệt về những mặc khải siêu phàm, một cái dằm đã được cho đâm vào thân xác tôi, một sứ giả của Sa-tan đã đánh tôi, để giữ tôi khỏi lên mình kiêu ngạo.  8 Ðã ba lần tôi cầu xin Chúa cất nó khỏi tôi, 9 nhưng Ngài đã phán với tôi, “Ân sủng Ta đã đủ cho ngươi rồi, vì quyền năng Ta được thể hiện trọn vẹn trong sự yếu đuối.”  Vậy tôi rất vui mừng tự hào về những yếu đuối của tôi, để quyền năng của Ðấng Christ có thể ngự trên tôi.  10 Cho nên vì cớ Ðấng Christ tôi vui chịu yếu đuối, sỉ nhục, gian khổ, bắt bớ, và hoạn nạn; vì khi tôi yếu đuối chính là lúc tôi mạnh mẽ.

                """],
            ["Mối Quan Tâm của Phao-lô về Hội Thánh Cô-rinh-tô": """
                11 Tôi đã thành một kẻ điên khùng, vì anh chị em đã buộc tôi trở nên như thế.  Ðúng ra anh chị em phải khen tôi mới phải, vì tuy tôi không ra gì, nhưng tôi không thua kém các sứ đồ siêu đẳng kia đâu.  12 Những dấu hiệu của một sứ đồ thật đã được thể hiện giữa anh chị em bằng tất cả sự kiên trì, bằng những dấu kỳ, những phép lạ, và những việc quyền năng.  13 Anh chị em có thua kém các hội thánh khác điều gì chăng?  Có chăng là tôi không là gánh nặng cho anh chị em mà thôi.  Hãy tha thứ cho tôi về sự bất công ấy!
                14 Xin anh chị em hãy xem, đây là lần thứ ba tôi sẵn sàng đến thăm anh chị em.  Tôi sẽ không là gánh nặng cho anh chị em đâu, bởi vì tôi không muốn tìm kiếm vật gì của anh chị em, mà chỉ muốn chính anh chị em; vì không phải con cái để dành của cải cho cha mẹ, nhưng cha mẹ để dành của cải cho con cái.
                15 Tôi rất vui sẽ chi tiêu, dù phải chi tiêu cả cuộc đời tôi vì linh hồn anh chị em.  Nếu tôi yêu thương anh chị em nhiều hơn, lẽ nào tôi sẽ được thương yêu ít lại sao?  16 Nhưng giả dụ như tôi không là gánh nặng cho anh chị em, nhưng tôi là kẻ xảo quyệt, đã dùng sự lừa dối gạt được anh chị em.  17 Vậy thử hỏi có ai trong số những người tôi đã phái đến với anh chị em, mà qua người đó tôi đã khai thác tư lợi gì của anh chị em chăng?  18 Lần trước tôi bảo Tít đi và đã phái một anh em cùng đi với anh ấy, Tít có khai thác tư lợi gì của anh chị em chăng?  Chẳng phải chúng tôi đã bước đi trong cùng một tinh thần sao?  Chẳng phải chúng tôi cùng đi theo những dấu chân đó sao?
                19 Lâu nay có lẽ anh chị em nghĩ rằng chúng tôi muốn bào chữa mình với anh chị em.  Nhưng thưa anh chị em yêu dấu, chúng tôi nói tất cả những điều nầy trước mặt Ðức Chúa Trời trong Ðấng Christ cốt để xây dựng anh chị em.  20 Vì tôi lo ngại rằng khi tôi đến, tôi sẽ thấy anh chị em không được như tôi mong ước, và anh chị em cũng sẽ thấy tôi không được như anh chị em mong ước.  Tôi cũng lo ngại rằng giữa anh chị em sẽ có cãi vã, ganh tị, giận dữ, ích kỷ, vu khống, nói hành, tự kiêu, và hỗn loạn.  21 Tôi cũng lo ngại rằng khi đến thăm anh chị em, Ðức Chúa Trời của tôi sẽ để tôi bị mất thể diện trước mặt anh chị em, và tôi phải than khóc vì những người đã phạm tội trước đây nhưng đến nay vẫn chưa chịu ăn năn về những việc ô uế, gian dâm, và trụy lạc họ đã phạm.

                """]
            ]),
        Chapter(13, passages: [
            ["Lời Cảnh Cáo Sau Cùng": """
                1 Ðây là lần thứ ba tôi đến thăm anh chị em.  Mọi lời buộc tội sẽ dựa vào lời chứng của hai hoặc ba người mà thiết lập.  2 Tôi muốn nói trước với những kẻ đã phạm tội trước đây và với mọi người, như tôi đã nói trong kỳ đến thăm lần thứ hai, và nay tôi lại nói trong lúc vắng mặt rằng: nếu tôi trở lại lần nữa, tôi sẽ không dung thứ đâu, 3 bởi vì anh chị em nhất định đòi cho được bằng chứng rằng Ðấng Christ đã phán qua tôi.  Ngài không phải là Ðấng nhu nhược khi đối xử với anh chị em, nhưng là Ðấng đầy quyền uy giữa anh chị em.  4 Thật vậy, dù Ngài đã chịu đóng đinh trong tình trạng yếu đuối, nhưng hiện nay Ngài đang sống bằng quyền năng Ðức Chúa Trời.  Cũng vậy, ở trong Ngài chúng tôi tuy yếu đuối, nhưng khi xử sự với anh chị em chúng tôi sẽ sống với Ngài bằng quyền năng Ðức Chúa Trời.
                5 Hãy tự xét nghiệm xem anh chị em có sống trong đức tin chăng.  Hãy tự kiểm tra mình đi.  Anh chị em không biết rằng Ðức Chúa Jesus Christ đang ở trong anh chị em sao?  Trừ phi anh chị em không qua nổi cuộc kiểm tra ấy.  6 Tôi hy vọng rằng anh chị em biết chúng tôi đã qua được cuộc kiểm điểm ấy rồi.
                7 Bây giờ chúng tôi cầu xin Ðức Chúa Trời cho anh chị em không làm điều gì sai, không phải để chứng tỏ rằng chúng tôi đã qua được cuộc kiểm tra, nhưng để anh chị em có thể làm điều đúng, cho dù chúng tôi có thể bị xem như không qua được cuộc kiểm tra thì cũng chẳng sao.  8 Vì chúng ta không thể làm những gì nghịch với sự thật, nhưng phải làm những gì hợp với sự thật.  9 Chúng tôi vui mừng khi thấy mình yếu đuối nhưng anh chị em mạnh mẽ.  Đây cũng là điều chúng tôi hằng cầu nguyện: anh chị em được trở nên trọn vẹn.
                10 Vì lý do đó tôi viết những điều nầy trong khi vắng mặt, để khi có mặt tôi không phải sử dụng uy quyền Chúa ban cho tôi một cách nghiêm khắc đối với anh chị em, dù đó là uy quyền để xây dựng chứ không phải để phá hủy.

                """],
            ["Lời Chào Cuối Thư và Chúc Phước": """
                11 Cuối cùng, thưa anh chị em, hãy vui lên, hãy cố gắng để trở nên trọn vẹn, hãy khích lệ lẫn nhau, hãy đồng tâm nhất trí với nhau, và hãy sống hòa bình với nhau.
                Nguyện xin Ðức Chúa Trời yêu thương và bình an ở với anh chị em.
                12 Hãy chào nhau bằng nụ hôn thánh.  
                13 Tất cả các thánh đồ ở đây gởi lời chào thăm anh chị em.
                14 Nguyện xin ân sủng của Ðức Chúa Jesus Christ, tình yêu của Ðức Chúa Trời, và sự hiệp thông của Ðức Thánh Linh ở với tất cả anh chị em.  A-men.

                """]
            ])
    ]
    
}




