
class Nehemi: Book {
    
    override init() {
        super.init()
        title = "NÊ-HÊ-MI"
        chapters = allChapters
        allChapters.forEach{ $0.book = self }
    }
    
    var allChapters: [Chapter] = [
        Chapter(1, passages: [
            ["Nê-hê-mi Cầu Nguyện cho Dân Tộc Ông": """
                1 Ðây là những lời của Nê-hê-mi con của Ha-ca-li-a:
                Vào tháng Kích-lê của năm thứ hai mươi, khi tôi đang ở trong cung điện của vua tại Su-sa, 2 một người trong số các anh em của tôi tên là Ha-na-ni và một vài người từ Giu-đa đến thăm tôi.  Tôi hỏi họ về tình hình của những người Do-thái còn sót lại, tức những người không bị bắt đem đi lưu đày, và tôi cũng hỏi thăm họ về Giê-ru-sa-lem.
                3 Họ đáp, “Những người Do-thái còn sót lại trong tỉnh, tức những người không bị bắt đem đi lưu đày, đang ở trong tình cảnh rất khốn khó và nhục nhã. Bức tường bao quanh Thành Giê-ru-sa-lem đã bị sụp đổ, còn các cổng thành đều đã bị lửa thiêu rụi.”
                4 Khi nghe những lời ấy xong, tôi ngồi và khóc.  Tôi rầu rĩ như người thọ tang suốt mấy ngày.  Tôi kiêng ăn và dâng lời cầu nguyện lên Ðức Chúa Trời trên trời.
                5 Tôi nói, “Lạy CHÚA, Ðức Chúa Trời trên trời, Ðức Chúa Trời vĩ đại và đáng sợ, Ðấng giữ giao ước và bày tỏ tình thương đối với ai yêu kính Ngài và vâng giữ các điều răn Ngài, 6 cầu xin Ngài lắng tai nghe và mở mắt nhìn, để nhậm lời cầu nguyện của con, tôi tớ Ngài, đang ngày đêm dâng lên vì các tôi tớ Ngài là dân I-sơ-ra-ên.  Con xưng nhận các tội lỗi của dân I-sơ-ra-ên mà chúng con đã phạm đối với Ngài, kể cả nhà của tổ tiên con và chính con đã phạm.  7 Chúng con đã làm đau lòng Ngài rất nhiều; chúng con đã không vâng giữ các điều răn, mạng lịnh, và luật lệ mà Ngài đã truyền cho Môi-se tôi tớ Ngài.  8 Cầu xin Ngài nhớ lại lời Ngài đã truyền cho Môi-se tôi tớ Ngài rằng, ‘Nếu các ngươi bất trung, Ta sẽ tung rải các ngươi ra giữa các dân; 9 nhưng nếu các ngươi trở về với Ta, gìn giữ, và vâng theo các điều răn của Ta, thì dù những kẻ bị lưu đày của các ngươi ở xa xăm bất cứ nơi nào, Ta cũng sẽ tập họp chúng lại ở đó mà đem chúng về nơi Ta đã chọn để đặt danh Ta.’  10 Họ là các tôi tớ Ngài và dân Ngài; họ là những người Ngài đã chuộc bằng quyền năng lớn lao và bằng cánh tay mạnh mẽ của Ngài.  11 Lạy Chúa, xin lắng nghe lời cầu nguyện của tôi tớ Ngài và lời cầu nguyện của các con cái Ngài, những người lấy làm vui mà kính sợ danh Ngài.  Cầu xin Ngài cho con được thành công hôm nay và cho con được ơn trước mặt người này.”
                Bấy giờ, tôi đang làm quan dâng rượu cho vua.

                """]
            ]),
        Chapter(2, passages: [
            ["Nê-hê-mi Ðược Sai Về Giu-đa": """
                1 Sau đó vào tháng Ni-san, năm thứ hai mươi của triều đại Vua Ạc-ta-xẹc-xe, khi rượu được mang đến cho vua, tôi lấy rượu và dâng cho vua.  Từ trước đến giờ tôi chưa bao giờ lộ vẻ buồn bã trước mặt vua.  2 Vì thế vua hỏi tôi, “Tại sao nét mặt ngươi trông buồn bã mặc dù ngươi chẳng đau yếu gì?  Ngươi chắc có tâm sự buồn phải không?”
                Bấy giờ tôi hết sức lo sợ, 3 tôi tâu với vua, “Hoàng thượng vạn tuế!  Làm sao nét mặt của hạ thần không buồn được khi thành, nơi mồ mả của tổ tiên hạ thần, đang bị điêu tàn, các cổng thành đã bị lửa thiêu rụi?”
                4 Vua hỏi tôi, “Ngươi muốn xin điều gì?”
                Tôi thầm nguyện với Ðức Chúa Trời ở trên trời, 5 rồi tâu với vua, “Nếu hoàng thượng bằng lòng, và nếu tôi tớ của hoàng thượng được đẹp lòng hoàng thượng, xin hoàng thượng sai hạ thần trở về Giu-đa, về nơi thành có mồ mả của tổ tiên hạ thần, để xây dựng nó lại.”
                6 Vua hỏi tôi, lúc đó có hoàng hậu ngồi bên cạnh, “Ngươi sẽ đi bao lâu?  Khi nào ngươi sẽ trở lại?”  Thấy vua vui lòng muốn cho tôi đi, tôi đã tâu với vua ngày tôi hẹn sẽ trở lại.  7 Ngoài ra tôi đã xin với vua, “Nếu đẹp lòng hoàng thượng, kính xin hoàng thượng gởi các chiếu chỉ cho các quan tổng trấn ở Bên Kia Sông, và trao cho hạ thần mang đi, để họ cho phép hạ thần được đi qua lãnh thổ của họ mà về đến Giu-đa.  8 Kính xin hoàng thượng cũng ban chiếu chỉ cho A-sáp, quan phụ trách lâm sản của triều đình, để ông ấy cung cấp gỗ cho hạ thần, hầu hạ thần có thể dựng lại các cổng thành, xây lại Ðền Thờ, tường thành, và nhà cho hạ thần ở.”  Vua chuẩn ban cho tôi mọi điều tôi xin, nhờ cánh tay nhân lành của Ðức Chúa Trời của tôi phù hộ tôi.
                9 Sau đó tôi đến gặp các quan tổng trấn ở Bên Kia Sông và trao cho họ các chiếu chỉ của vua.  Số là vua đã sai các sĩ quan chỉ huy quân đội và một đoàn kỵ binh cùng đi với tôi.  10 Tuy nhiên khi San-ba-lát lãnh tụ của dân Hô-rô-ni và Tô-bi-a tôi tớ của vua đang cai trị dân Am-môn nghe rằng có người được phép trở về để lo cho dân I-sơ-ra-ên, họ rất bực bội.

                """],
            ["Nê-hê-mi Quan Sát Tường Thành Giê-ru-sa-lem": """
                11 Sau khi đã về đến Giê-ru-sa-lem và ở đó được ba ngày, 12 tôi và một vài người cùng đi với tôi thức dậy trong ban đêm.  Số là tôi không thố lộ cho người nào biết những gì Ðức Chúa Trời đã đặt trong lòng tôi sẽ làm tại Giê-ru-sa-lem, và cũng không có con vật nào đi với tôi ngoại trừ con vật tôi cỡi.  13 Ðang đêm tôi theo Cổng Thung Lũng đi ra ngoài thành, đến Giếng Mãng Xà, rồi đến Cổng Phân.  Tôi đã thấy tận mắt bức tường bao quanh Giê-ru-sa-lem bị đổ nát như thế nào và các cổng thành đã bị lửa thiêu rụi ra sao.  14 Sau đó tôi tiến đến Cổng Suối Nước, rồi đến Hồ Hoàng Gia, nhưng không có chỗ nào cho con vật tôi cỡi có thể đi qua được.  15 Vì thế tôi đi vòng xuống thung lũng, và cứ đi trong đêm mà quan sát những phần còn lại của tường thành.  Sau đó tôi đi ngược trở lại để vào thành qua Cổng Thung Lũng và trở về chỗ ở.  16 Các quan chức ở với tôi không biết tôi đã đi đâu và cũng không biết tôi đã làm gì.  Lúc ấy tôi chưa nói cho người Do-thái, các tư tế, các nhà quý tộc, các quan chức, hay những người sẽ làm công việc xây dựng biết gì cả.  17 Sau đó tôi nói với họ, “Quý vị chắc đã thấy rõ tình cảnh bi đát của chúng ta, thể nào Giê-ru-sa-lem đang bị hoang phế, và các cổng thành đã bị lửa thiêu rụi.  Hãy đến chúng ta hãy cùng nhau xây dựng lại bức tường bao quanh Giê-ru-sa-lem để chúng ta không còn làm cớ cho người ta sỉ nhục nữa.”
                18 Tôi đã trình bày cho họ biết thể nào tay của Ðức Chúa Trời đã tốt đối với tôi, và tôi cũng đã nói cho họ biết những lời vua đã nói với tôi.  Vì thế họ nói, “Chúng ta hãy đứng lên và xây dựng.”  Sau đó họ bắt tay thực hiện công việc tốt đẹp đó.
                19 Tuy nhiên khi San-ba-lát lãnh tụ của dân Hô-rô-ni, Tô-bi-a tôi tớ của vua đang cai trị dân Am-môn, và Ghê-sem lãnh tụ của người Ả-rập nghe điều đó, họ cười nhạo chúng tôi.  Họ mỉa mai và khinh dể chúng tôi rằng, “Các người tính làm gì đó?  Các người tính làm loạn chống lại nhà vua phải không?”
                20 Nhưng tôi đáp với họ và bảo họ rằng, “Chính Ðức Chúa Trời ở trên trời sẽ phù hộ chúng tôi; cho nên chúng tôi, các tôi tớ của Ngài, sẽ đứng dậy và xây dựng, nhưng quý vị không có phần gì, không có quyền gì, và cũng không có kỷ niệm gì ở Giê-ru-sa-lem cả.”

                """]
            ]),
        Chapter(3, passages: [
            ["Xây Dựng Lại Tường Thành Giê-ru-sa-lem": """
                1 Bấy giờ Thượng Tế Ê-li-a-síp cùng các anh em của ông, tức các tư tế, đứng dậy khởi công xây lại Cổng Chiên.  Họ biệt riêng nó ra thánh và gắn các cánh cửa của nó vào.  Sau đó họ xây lại tường thành từ cổng đó cho đến Tháp Mê-a, rồi biệt riêng nó ra thánh; xong rồi họ tiếp tục xây lại tường thành cho đến Tháp Ha-na-nên.
                2 Tiếp theo ông, dân ở Giê-ri-cô xây dựng khúc tường thành kế tiếp.
                Tiếp theo họ, Xác-cua con của Im-ri xây lại khúc kế tiếp.
                3 Các con của Hạc-sê-na-a xây lại Cổng Cá.  Họ đặt các cây đà vào vị trí của chúng; họ gắn các cánh cửa vào, tra các chốt cửa vào, và xỏ các then cài vào chỗ của chúng.
                4 Tiếp theo họ, Mê-rê-mốt con của U-ri-a, con của Hắc-cô, xây lại.
                Tiếp theo họ, Mê-su-lam con của Bê-rê-khi-a, con của Mê-sê-xa-bên, xây lại.
                Tiếp theo họ, Xa-đốc con của Ba-a-na, xây lại.
                5 Tiếp theo họ, dân ở Tê-cô-a xây lại; tuy nhiên những người quý tộc của họ không ghé vai vào công việc của Chúa họ.
                6 Giô-i-a-đa con của Pa-sê-a và Mê-su-lam con của Bê-sô-đê-a xây lại Cổng Cũ.  Họ đặt các cây đà vào vị trí của chúng; họ gắn các cánh cửa vào, tra các chốt cửa vào, và xỏ các then cài vào chỗ của chúng.
                7 Tiếp theo họ, Mê-la-ti-a người Ghi-bê-ôn và Gia-đôn người Mê-rô-nô-thi, những người ở Ghi-bê-ôn và Mích-pa, các địa hạt thuộc quyền quản trị của vị tổng trấn miền tây Sông Ơ-phơ-rát, xây lại.
                8 Kế ông ấy, U-xi-ên con của Hạc-hai-a, một trong những người thợ bạc, xây lại.
                Kế ông ấy, Ha-na-ni-a, một trong những người bào chế nước hoa, xây lại.  Họ đã làm cho tường thành Giê-ru-sa-lem trở nên kiên cố đến tận chỗ Tường Rộng.
                9 Tiếp theo họ, Rê-phai-a con của Hu-rơ, người cai trị phân nửa Quận Giê-ru-sa-lem, xây lại.
                10 Khúc tường thành kế tiếp nằm ngay trước nhà của Giê-đa-gia con của Ha-ru-máp, nên ông ấy lãnh trách nhiệm xây lại.
                Kế ông ấy, Hát-túc con của Ha-sáp-nê-gia xây lại.
                11 Manh-ki-gia con của Ha-rim và Hạc-súp con của Pa-hát Mô-áp xây lại khúc tường thành kế tiếp.  Họ cũng xây dựng lại Tháp Các Lò.
                12 Kế theo ông, Sanh-lum, người cai trị phân nửa Quận Giê-ru-sa-lem, và các con gái của ông xây lại.
                13 Ha-nun và dân Xa-nô-a xây lại Cổng Thung Lũng.  Họ xây cổng ấy lại, gắn các cánh cửa vào, tra các chốt cửa vào, và xỏ các then cài vào chỗ của chúng.  Họ cũng xây lại một khúc tường thành dài năm trăm mét cho đến Cổng Phân.
                14 Manh-ki-gia con của Rê-cáp, người cai trị Quận Bết Hạc-kê-rem, xây lại Cổng Phân.  Ông xây cổng ấy lại, gắn các cánh cửa vào, tra các chốt cửa vào, và xỏ các then cài vào chỗ của chúng.
                15 Sanh-lun con của Côn Hô-xết, người cai trị Quận Mích-pa, xây lại Cổng Suối Nước.  Ông xây cổng ấy lại, lợp mái cho cổng, gắn các cánh cửa vào, tra các chốt cửa vào, và xỏ các then cài vào.  Ông xây lại tường thành ở khúc ấy cho đến Ao Sê-la kế bên Vườn Ngự Uyển.  Sau đó ông xây lại tiếp một khúc tường thành nữa cho đến chỗ các bậc cấp dẫn từ Thành Ða-vít đi xuống.
                16 Kế theo ông, Nê-hê-mi-a con của A-xơ-búc, người cai trị Quận Bết Xua, xây lại.  Ông xây lại cho đến chỗ đối ngang Lăng Ða-vít, đến Hồ Nhân Tạo, và đến Ðền Tưởng Niệm Chiến Sĩ.
                17 Kế ông ấy, những người Lê-vi, dưới sự lãnh đạo của Rê-hum con của Ba-ni, xây lại.
                Kế theo ông, Ha-sa-bi-a, người cai trị phân nửa Quận Kê-la, xây lại phần tường thành nơi quận của ông.
                18 Kế theo ông, các anh em trong dòng họ của ông do Ba-vai con của Hê-na-đát, người cai trị phân nửa kia của Quận Kê-la, chỉ huy cuộc tu bổ.
                19 Tiếp theo ông, Ê-xe con của Giê-sua, người cai trị ở Mích-pa, xây lại khúc tường thành đối ngang với dốc đi lên Kho Binh Khí, nằm ở góc thành.
                20 Kế ông ấy, Ba-rúc con của Xáp-bai nhiệt tình xây lại khúc tường thành từ góc thành đến cổng của tư thất Thượng Tế Ê-li-a-síp.
                21 Kế theo ông, Mê-rê-mốt con của U-ri-gia, con của Cô-xơ, xây lại khúc tường thành từ cổng của tư thất Ê-li-a-síp cho đến cuối tư thất của Ê-li-a-síp.
                22 Kế tiếp ông, các tư tế sống ở đồng bằng xây lại.
                23 Tiếp theo họ, Bên-gia-min và Hạc-súp xây lại phần tường thành đối ngang nhà của họ.
                Tiếp theo họ, A-xa-ri-a con của Ma-a-sê-gia, con của A-na-ni-a, xây lại khúc tường thành kế bên nhà ông ấy.
                24 Kế ông, Bin-nui con của Hê-na-đát xây lại một phần khác, từ nhà của A-xa-ri-a cho đến chỗ có trụ tường và cả góc tường thành.
                25 Pa-lanh con của U-xai xây lại phần phía trước góc tường thành và cái tháp nhô ra từ thượng cung của đền vua, gần sân của các vệ binh và nhà tù.
                Kế ông ấy, Pê-đa-gia con của Pa-rốt xây lại.
                26 Những người phục vụ Ðền Thờ sống ở Ðồi Ô-phên xây lại khúc tường thành kế tiếp cho đến chỗ đối ngang Cổng Nước ở phía đông, nơi có tháp nhô ra.
                27 Tiếp theo họ, dân ở Tê-cô-a xây lại một khúc tường thành khác, từ chỗ tháp lớn nhô ra cho đến khúc tường tại Ô-phên.
                28 Từ Cổng Ngựa trở đi, các tư tế chịu trách nhiệm tu bổ; người nào xây lại khúc tường trước nhà người nấy.
                29 Tiếp theo họ, Xa-đốc con của Im-me xây lại khúc tường trước mặt nhà ông.
                Tiếp theo ông, Sê-ma-gia con của Sê-ca-ni-a, người giữ Cổng Ðông, xây lại khúc kế tiếp.
                30 Kế ông, Ha-na-ni-a con của Sê-la-mi-a và Ha-nun con thứ sáu của Xa-láp xây lại khúc tường thành kế tiếp.
                Tiếp theo họ, Mê-su-lam con của Bê-rê-ki-a xây lại phần tường thành đối ngang nơi ông ở.
                31 Kế ông, Manh-ki-gia, một trong các thợ kim hoàn, xây lại khúc tường thành cho đến tòa nhà dành cho những người phục vụ Ðền Thờ và những người mua đồ cung cấp cho Ðền Thờ.  Ðó là nơi đối ngang Cổng Khám Xét.  Ông tiếp tục xây lại cho đến phòng cao ở góc thành.
                32 Khúc tường thành ở giữa phòng cao của góc thành và Cổng Chiên do các thợ kim hoàn và các thương gia xây lại.

                """]
            ]),
        Chapter(4, passages: [
            ["Quân Thù Ðe Dọa và Cách Ðối Phó với Quân Thù": """
                1 Khi San-ba-lát nghe rằng chúng tôi đang xây lại tường thành, ông nổi giận và cực kỳ tức tối.  Ông chế nhạo người Do-thái.  2 Ông nói trước mặt anh em của ông và đạo quân Sa-ma-ri, “Bọn Do-thái nhu nhược đó đang làm gì thế? Chúng tưởng chúng có thể xây lại được tường thành ấy sao?  Bọn chúng tính sẽ dâng của tế lễ sao?  Chúng há có thể hoàn tất công việc ấy trong một ngày sao?  Chúng há có thể làm cho đống đá đổ nát đã bị cháy ấy được xây dựng lại sao?”
                3 Lúc ấy Tô-bi-a người Am-môn đang đứng bên cạnh ông cũng nói, “Những gì bọn đó xây dựng, nếu có một con chồn leo lên, bức tường đá ấy ắt sẽ đổ xuống ngay!”
                4 “Ðức Chúa Trời của chúng con ôi, xin đoái nghe, vì chúng con bị khinh khi quá đỗi.  Xin Ngài đổ nỗi sỉ nhục do chúng gây ra trở lại trên đầu chúng.  Xin ban chúng làm chiến lợi phẩm cho quân thù của chúng, để chúng phải vào trong xứ chúng sẽ bị lưu đày.  5 Xin Ngài đừng che đậy tội lỗi của chúng.  Xin đừng xóa bỏ tội của chúng khỏi thánh nhan Ngài, vì chúng đã thốt ra những lời sỉ nhục trước mặt những người đang nỗ lực xây dựng.”
                6 Dù chúng nói vậy, chúng tôi vẫn tiếp tục xây lại tường thành cho đến khi bức tường xây lên được một nửa, vì dân chúng đã chuyên tâm làm việc.
                7 Tuy nhiên khi San-ba-lát, Tô-bi-a, những người Ả-rập, những người Am-môn, và những người Ách-đốt nghe rằng việc xây lại tường thành Giê-ru-sa-lem đã tiến triển tốt đẹp, những chỗ đổ vỡ của tường thành đã được xây sửa lại, họ rất tức giận.  8 Tất cả những người ấy lập mưu với nhau để tiến đánh Giê-ru-sa-lem hầu gây trở ngại cho công cuộc tái thiết.  9 Nhưng chúng tôi cầu nguyện với Ðức Chúa Trời của chúng tôi và đặt người canh gác để đề phòng chúng cả ngày lẫn đêm.  10 Bấy giờ người Giu-đa nói, “Sức lực của các nhân công đã kiệt quệ, còn các đống đổ nát lại quá lớn.  Chúng ta sẽ không thể nào xây lại tường thành này được đâu.”  11 Trong khi ấy những kẻ thù của chúng tôi bảo, “Bọn chúng sẽ không biết và không thấy gì cho đến khi chúng ta ập vào giữa chúng, giết chúng, và làm ngưng công cuộc tái thiết ấy.”  12 Tuy nhiên những người Do-thái sống bên cạnh chúng đã đến báo cho chúng tôi hay đến mười lần rằng quân thù khắp nơi sẽ kéo đến tấn công chúng tôi.  13 Vì thế tôi đặt những người được vũ trang phía sau những chỗ thấp và trống trải của tường thành.  Tôi bố trí họ theo từng dòng họ và trang bị họ với gươm, giáo, và cung tên.  14 Sau khi đã thị sát, tôi đứng dậy và nói với các nhà quý tộc, các quan chức, và những người dân còn lại rằng, “Xin anh chị em chớ sợ chúng.  Hãy nhớ rằng Chúa là Ðấng vĩ đại và đáng kinh hãi.  Hãy chiến đấu cho anh chị em mình, cho con trai, con gái, vợ, và nhà mình.”
                15 Khi quân thù của chúng tôi nghe báo cáo rằng chúng tôi đã biết rõ âm mưu của chúng, và Ðức Chúa Trời đã làm bại mưu của chúng, bấy giờ tất cả chúng tôi trở lại chỗ làm của mình nơi tường thành, và tiếp tục việc ai nấy làm.
                16 Kể từ đó trở đi, phân nửa nhân lực của tôi làm công việc xây cất, còn phân nửa kia mặc áo giáp đứng canh gác với giáo mác, thuẫn khiên, và cung nỏ bên mình.  Những người chỉ huy của họ đứng phía sau điều động toàn thể nhà Giu-đa.  17 Những người xây thành và những người khuân vác đều chia sẻ trách nhiệm: một tay làm việc, một tay cầm binh khí.  18 Mỗi người xây dựng đều mang một thanh gươm bên mình trong khi làm việc, còn người thổi kèn hiệu lịnh luôn ở bên cạnh tôi.  19 Tôi nói với các nhà quý tộc, các quan chức, và những người dân còn lại rằng, “Công việc quá lớn lao và trải rộng, trong khi chúng ta làm việc cách khoảng với nhau trên tường thành, nhóm này cách xa nhóm nọ.  20 Vì thế mỗi khi anh em nghe tiếng kèn trỗi lên ở nơi nào, anh em hãy tập trung về nơi đó với chúng tôi.  Ðức Chúa Trời chúng ta sẽ chiến đấu cho chúng ta!”
                21 Cứ như thế chúng tôi nỗ lực làm việc, ngày nào cũng từ sáng sớm đến chiều tối.  Một nửa nhân lực luôn cầm giáo đứng canh chừng quân thù đến tấn công.
                22 Lúc đó tôi cũng nói với những người sống ở xa về giúp, “Mọi người, kể cả các tôi tớ của họ, hãy vào trong Thành Giê-ru-sa-lem mà qua đêm, để họ có thể chia sẻ việc canh gác ban đêm, rồi cùng nhau làm việc ban ngày.”
                23 Cứ như thế, chính mình tôi, các anh em của tôi, các tôi tớ của tôi, và các vệ sĩ đi theo tôi, không ai cởi bỏ chiến y của mình ra, nhưng ai nấy lúc nào cũng mang vũ khí bên mình, ngay cả khi tắm rửa cũng để vũ khí cận kề.

                """]
            ]),
        Chapter(5, passages: [
            ["Giải Quyết Tệ Nạn Xã Hội": """
                1 Lúc ấy dân và vợ của họ lớn tiếng kêu la phản đối những người Do-thái anh chị em của họ.  2 Có người đã nói, “Gia đình chúng tôi đông miệng ăn, gồm chúng tôi, các con trai chúng tôi, và các con gái chúng tôi.  Chúng tôi cần có lúa để ăn và sống.”  3 Một số người khác nói, “Chúng tôi phải cầm cố ruộng đất, vườn nho, và nhà cửa mới có lúa ăn trong thời đói kém.”  4 Một số khác lại nói, “Chúng tôi phải thế chấp ruộng đất và vườn nho của mình mới vay được tiền đóng thuế cho vua, 5 trong khi đó chúng tôi đều là người cùng máu mủ ruột thịt như anh chị em mình, con cái chúng tôi cũng như con cái họ, thế mà chúng tôi bị buộc phải bắt con trai và con gái chúng tôi làm tôi đòi cho họ.  Thật vậy một số con gái chúng tôi đã phải làm nô tỳ.  Chúng tôi không có quyền gì cả, vì ruộng đất và vườn nho của chúng tôi đều đã thuộc quyền của người khác rồi.”
                6 Khi tôi nghe những lời kêu ca và phản đối ấy, tôi nổi giận.  7 Sau khi suy nghĩ kỹ, tôi trách những nhà quý tộc và những người cầm quyền trong dân.  Tôi nói với họ, “Ai nấy trong quý vị đều cho anh chị em mình vay và lấy lãi quá cao.”  Sau đó tôi triệu tập một cuộc họp trọng thể để giải quyết việc ấy với họ.  8 Tôi nói với họ, “Chúng tôi đã chuộc lại anh chị em người Do-thái chúng ta vốn bị bán làm nô lệ cho các dân ngoại, nhưng bây giờ quý vị lại bán anh chị em mình, khiến họ phải làm nô lệ cho người khác, để rồi chúng tôi lại phải chuộc họ thêm lần nữa sao?”  Họ đều làm thinh và không thể đáp lại được lời nào.  9 Tôi nói tiếp, “Những gì quý vị làm là không tốt.  Há chẳng phải tất cả chúng ta phải sống với nhau trong sự kính sợ Ðức Chúa Trời để các dân ngoại, những kẻ thù của chúng ta, không khinh bỉ chúng ta sao?  10 Chính tôi, các anh em tôi, và các tôi tớ của tôi cũng cho vay tiền và lúa gạo vậy.  Tôi xin quý vị hãy xóa bỏ việc cho vay nặng lãi ấy đi.  11 Ngay hôm nay tôi xin quý vị hãy trả lại cho anh chị em mình ruộng đất của họ, các vườn nho của họ, các rẫy ô-liu của họ, và nhà cửa của họ; xin hãy xóa bỏ luôn các lãi suất quá cao về tiền bạc, lúa gạo, rượu mới, và dầu ô-liu mà họ đã vay của quý vị.”
                12 Họ trả lời, “Chúng tôi sẽ trả lại cho họ.  Chúng tôi sẽ không đòi họ phải trả gì nữa.  Chúng tôi sẽ làm những gì ông nói.”  
                Bấy giờ tôi mời các vị tư tế đến để lập một lễ tuyên thệ hầu họ có thể thề sẽ làm những gì họ đã hứa.  
                13 Tôi cũng giũ vạt áo của tôi và nói, “Nguyện Ðức Chúa Trời sẽ giũ sạch nhà cửa và tài sản của người nào không giữ lời hứa của mình.  Nguyện Ngài sẽ giũ nó như thế này, để nó sẽ trở nên trắng tay.”  
                Bấy giờ toàn thể hội chúng nói “A-men!” và cất tiếng ca ngợi CHÚA.  Sau đó những người ấy thực hiện những gì họ đã hứa.

                """],
            ["Lòng Hào Sảng của Nê-hê-mi": """
                14 Ngoài ra kể từ khi tôi được bổ nhiệm làm tổng trấn của họ trong xứ Giu-đa, tức từ năm thứ hai mươi cho đến năm thứ ba mươi hai của triều đại Vua Ạc-ta-xẹc-xe –mười hai năm– tôi và những người phụ tá của tôi không nhận lương bổng mà chúng tôi được quyền hưởng.  15 Nhưng các tổng trấn trước tôi đã làm gánh nặng cho dân.  Ngoài việc họ được cung cấp thực phẩm và rượu mỗi ngày, họ còn đòi dân phải chu cấp cho họ nửa ký bạc.  Ngay cả những người phụ tá của họ cũng bắt nạt dân.  Nhưng tôi không làm thế, vì tôi kính sợ Ðức Chúa Trời.  16 Thật vậy tôi đã đổ tâm huyết vào việc xây dựng lại tường thành và không màng gì đến việc mua ruộng đất cho mình.  Tất cả các tôi tớ của tôi đều tập trung tại đó để làm việc.  17 Ngoài ra có chừng một trăm năm mươi quan chức người Do-thái thường ăn uống tại bàn tôi, không kể những quan khách ngoại quốc từ các nước đến.  18 Mỗi ngày người ta làm thịt một con bò, sáu con chiên mập, và rất nhiều gà vịt để thết đãi.  Cứ mỗi mười ngày, người ta lại chở đến một đợt gồm nhiều loại rượu.  Dù vậy tôi vẫn không đòi hỏi bổng lộc dành cho một tổng trấn, bởi vì công việc chung trong sự tái thiết tường thành đã đủ nặng nhọc cho dân này rồi.
                19 “Ðức Chúa Trời của con ôi, cầu xin Ngài nhớ đến con và ban phước cho con, vì tất cả những gì con đã làm cho dân này.”

                """]
            ]),
        Chapter(6, passages: [
            ["Ðối Phó với Thù Trong Giặc Ngoài": """
                1 Sau việc ấy khi San-ba-lát, Tô-bi-a, Ghê-sem người Ả-rập, và những kẻ thù còn lại của chúng tôi đã nghe báo cáo rằng tôi đã xây lại xong tường thành và không còn chỗ nào bị đổ vỡ nữa, dù lúc đó tôi chưa tra các cánh cửa ở các cổng thành vào.  2 San-ba-lát và Ghê-sem sai sứ giả đến gặp tôi và nói, “Hãy đến, chúng ta hãy gặp nhau tại một làng trong số các làng ở Ðồng Bằng Ô-nô.”  Số là họ đã lập mưu để hại tôi.  3 Vì thế tôi sai các sứ giả đến gặp họ và nói, “Tôi đang bận thực hiện công việc trọng đại nên không thể xuống gặp các ông được.  Làm sao tôi có thể ngưng lại và bỏ dở công việc để xuống gặp các ông chứ?”  4 Họ sai người đến nói với tôi bốn lần như thế, và mỗi lần tôi đều trả lời như nhau.  5 Lần thứ năm San-ba-lát sai sứ giả đến gặp tôi, trong tay mang một bức thư không niêm, 6 trong đó viết, “Theo như lời của Ghê-sem nói, người ta đã đồn trong các dân các nước rằng ông và người Do-thái đang mưu đồ phản loạn, vì lẽ đó nên ông đã cho xây lại tường thành, và cũng theo các tin đồn đó, ông tính sẽ làm vua của họ.  7 Hơn nữa ông đã lập các tiên tri để rao báo về ông ở Giê-ru-sa-lem rằng, ‘Có một vua ở Giu-đa.’  Tin tức này thế nào cũng sẽ được tâu trình về vua.  Vì thế mời ông đến để chúng ta bàn bạc với nhau.”
                8 Tôi bèn sai người đến nói với hắn, “Không hề có chuyện như lời ông nói.  Tất cả đều do ông tưởng tượng đặt điều.”  9 Quả vậy cả bọn họ đều muốn làm cho chúng tôi lo sợ; họ bảo nhau, “Phải làm cho tay chúng yếu đi mà buông xuôi, và công việc sẽ bị bỏ dở.”  Vì thế, “Ðức Chúa Trời ôi, xin Ngài làm cho tay con được mạnh mẽ.”
                10 Sau đó tôi đến nhà của Sê-ma-gia con của Ðê-la-gia, con của Mê-hê-ta-bên, một kẻ làm nội tuyến, vì hắn đã nói với tôi, “Chúng ta hãy đến gặp nhau trong Ðền Thờ của Ðức Chúa Trời.  Chúng ta sẽ vào bên trong và khóa cửa lại, vì họ sẽ đến để giết ông.  Thế nào đêm về họ cũng sẽ đến để ám sát ông.”
                11 Tôi nói với hắn, “Một người như tôi mà chạy trốn sao?  Một người như tôi mà phải chạy vào Ðền Thờ để giữ mạng sao?  Tôi sẽ không vào đâu.”  12 Vì tôi đã nhận biết rằng Ðức Chúa Trời không sai bảo hắn, nhưng vì Tô-bi-a và San-ba-lát đã thuê hắn để hắn nói tiên tri chống lại tôi.  13 Họ đã có chủ mưu khi mướn hắn.  Họ muốn làm cho tôi hoảng sợ mà làm theo đề nghị của hắn, hầu tôi sẽ mắc tội, và như thế họ sẽ có lý do để buộc tội tôi và làm mất uy tín tôi.
                14 “Ðức Chúa Trời của con ôi, xin Ngài nhớ đến Tô-bi-a và San-ba-lát về những việc ấy của chúng.  Xin Ngài cũng nhớ đến Nữ Tiên Tri Nô-a-đi-a và các tiên tri a dua theo bà ấy, những kẻ muốn làm cho con phải lo sợ.”
                15 Cuối cùng tường thành cũng đã được xây lại xong vào ngày hai mươi lăm tháng Ê-lun, trong vòng năm mươi hai ngày.  16 Khi toàn thể quân thù của chúng tôi nghe việc ấy, tất cả các nước chung quanh chúng tôi đều sợ hãi và mất tinh thần.  Họ đều nhận biết rằng nhờ Ðức Chúa Trời phù hộ nên công trình ấy mới được hoàn tất.
                17 Ngoài ra trong những ngày ấy các nhà quyền quý của Giu-đa đã gởi nhiều thư đến Tô-bi-a, và Tô-bi-a cũng đã gởi nhiều thư đến với họ.  18 Thật vậy có nhiều người ở Giu-đa đã lập lời thề với hắn, vì hắn là con rể của Sê-ca-ni-a con của A-ra; con trai hắn là Giê-hô-ha-nan đã cưới con gái của Mê-su-lam, con trai của Bê-rê-ki-a.  19 Hơn nữa những người ấy đã nói tốt về hắn trước mặt tôi và tâu lại với hắn những gì tôi đã nói.  Chính Tô-bi-a này là người đã gởi các thư đe dọa tôi.

                """]
            ]),
        Chapter(7, passages: [
            ["Tổ Chức Việc Lãnh Ðạo và Canh Gác Thành": """
                1 Sau khi tường thành đã được tái thiết, và tôi đã cho tra các cánh cửa ở các cổng thành vào, các đội ngũ canh gác, ca hát, và những người Lê-vi cũng đã được phân nhiệm, 2 tôi lập Ha-na-ni em tôi làm thị trưởng, và Ha-na-ni-a làm người chỉ huy các binh sĩ bảo vệ thành, vì ông ấy là một người trung thành và kính sợ Ðức Chúa Trời hơn nhiều người khác.  3 Tôi truyền cho họ, “Ðừng mở các cổng thành Giê-ru-sa-lem cho đến khi ánh nắng mặt trời lên.  Hễ những người canh gác ban đêm còn đứng canh, các cổng thành vẫn phải đóng và cài then.  Hãy cắt đặt dân cư Giê-ru-sa-lem thay phiên nhau canh gác.  Một số sẽ đứng gác ở các trạm canh, và một số khác sẽ đứng gác trước nhà mình.”
                """],
            ["Sổ Bộ Những Người Hồi Cư": """
                (Êxr 2:1-70)
                
                4 Khi ấy thành thì rộng và lớn, nhưng dân trong thành lại ít và nhà cửa chưa được xây dựng lại.  5 Ðức Chúa Trời của tôi giục lòng tôi để tôi mời các nhà quý tộc, các quan chức, và dân lại để họ ghi danh theo gia phả của họ.  Tôi đã tìm được một sổ danh bạ những người hồi hương đợt đầu, trong đó có ghi như sau:
                6 Ðây là những người ở các tỉnh từ chốn lưu đày trở về, những người trong số những người đã bị Nê-bu-cát-nê-xa vua Ba-by-lôn bắt đem đi lưu đày đã trở về Giê-ru-sa-lem và Giu-đa, ai về thành nấy.  7 Những người cùng trở về với Xê-ru-ba-bên gồm có: Giê-sua, Nê-hê-mi-a, A-xa-ri-a, Ra-a-mi-a, Na-ha-ma-ni, Mạc-đô-chê, Bin-san, Mít-pê-rết, Bích-vai, Nê-hum, và Ba-a-na.
                Ðây là con số những người I-sơ-ra-ên đã từ chốn lưu đày trở về:
                8 Con cháu của Pa-rốt, hai ngàn một trăm bảy mươi hai người.
                9 Con cháu của Sê-pha-ti-a, ba trăm bảy mươi hai người.
                10 Con cháu của A-ra, sáu trăm năm mươi hai người.
                11 Con cháu của Pa-hát Mô-áp, qua dòng dõi của Giê-sua và Giô-áp, hai ngàn tám trăm mười tám người.
                12 Con cháu của Ê-lam, một ngàn hai trăm năm mươi bốn người.
                13 Con cháu của Xát-tu, tám trăm bốn mươi lăm người.
                14 Con cháu của Xác-cai, bảy trăm sáu mươi người.
                15 Con cháu của Bin-nui, sáu trăm bốn mươi tám người.
                16 Con cháu của Bê-bai, sáu trăm hai mươi tám người.
                17 Con cháu của A-xơ-gát, hai ngàn ba trăm hai mươi hai người.
                18 Con cháu của A-đô-ni-cam, sáu trăm sáu mươi bảy người.
                19 Con cháu của Bích-vai, hai ngàn sáu mươi bảy người.
                20 Con cháu của A-đin, sáu trăm năm mươi lăm người.
                21 Con cháu của A-te, gia tộc của Hê-xê-ki-a, chín mươi tám người.
                22 Con cháu của Ha-sum, ba trăm hai mươi tám người.
                23 Con cháu của Bê-xai, ba trăm hai mươi bốn người.
                24 Con cháu của Ha-ríp, một trăm mười hai người.
                25 Con cháu của Ghi-bê-ôn, chín mươi lăm người.
                26 Dân Bết-lê-hem và Nê-tô-pha, một trăm tám mươi tám người.
                27 Dân A-na-thốt, một trăm hai mươi tám người.
                28 Dân Bết A-ma-vết, bốn mươi hai người.
                29 Dân Ki-ri-át Giê-a-rim, Kê-phi-ra, và Bê-e-rốt, bảy trăm bốn mươi ba người.
                30 Dân Ghê-ba và Ra-ma, sáu trăm hai mươi mốt người.
                31 Dân Mích-mác, một trăm hai mươi hai người.
                32 Dân Bê-tên và Ai, một trăm hai mươi ba người.
                33 Dân Nê-bô khác, năm mươi hai người.
                34 Con cháu của Ê-lam khác, một ngàn hai trăm năm mươi bốn người.
                35 Con cháu của Ha-rim, ba trăm hai mươi người.
                36 Con cháu của Giê-ri-cô, ba trăm bốn mươi lăm người.
                37 Con cháu của Lô, Ha-đi, và Ô-nô, bảy trăm hai mươi mốt người.
                38 Con cháu của Sê-nê-a, ba ngàn chín trăm ba mươi người.
                39 Các tư tế: Con cháu của Giê-đa-gia, gia tộc của Giê-sua, chín trăm bảy mươi ba người.
                40 Con cháu của Im-me, một ngàn năm mươi hai người.
                41 Con cháu của Pát-khua, một ngàn hai trăm bốn mươi bảy người.
                42 Con cháu của Ha-rim, một ngàn mười bảy người.
                43 Những người Lê-vi: con cháu của Giê-sua, gia tộc của Hô-đê-va, bảy mươi bốn người.
                44 Những người ca hát: con cháu của A-sáp, một trăm bốn mươi tám người.
                45 Những người canh cửa: con cháu của Sanh-lum, con cháu của A-te, con cháu của Tanh-môn, con cháu của Ạc-cúp, con cháu của Ha-ti-ta, con cháu của Sô-bai, một trăm ba mươi tám người.
                46 Những người phục vụ tại Ðền Thờ: con cháu của Xi-ha, con cháu của Ha-su-pha, con cháu của Ta-ba-ốt, 47 con cháu của Kê-rô, con cháu của Si-a, con cháu của Pa-đôn, 48 con cháu của Lê-ba-na. con cháu của Ha-ga-ba, con cháu của Sanh-mai, 49 con cháu của Ha-na, con cháu của Ghít-đên, con cháu của Ga-ha, 50 con cháu của Rê-a-gia, con cháu của Rê-xin, con cháu của Nê-cô-đa, 51 con cháu của Ga-xam, con cháu của U-xa, con cháu của Pa-sê-a, 52 con cháu của Bê-sai, con cháu của Mê-u-nim, con cháu của Nê-phu-sê-sim, 53 con cháu của Bác-búc, con cháu của Ha-cư-pha, con cháu của Hạc-hưa, 54 con cháu của Ba-xơ-lít, con cháu của Mê-hi-đa, con cháu của Hạc-sa, 55 con cháu của Ba-cốt, con cháu của Si-sê-ra, con cháu của Tê-ma, 56 con cháu của Nê-xi-a, con cháu của Ha-ti-pha.
                57 Con cháu của các tôi tớ Sa-lô-môn: con cháu của Sô-tai, con cháu của Sô-phê-rết, con cháu của Pê-ri-đa, 58 con cháu của Gia-a-la, con cháu của Ðạc-côn, con cháu của Ghít-đên, 59 con cháu của Sê-pha-ti-a, con cháu của Hát-tin, con cháu của Pô-kê-rết Ha-xê-ba-im, con cháu A-môn.
                60 Tất cả những người phục vụ ở Ðền Thờ và con cháu của các tôi tớ Sa-lô-môn là ba trăm chín mươi hai người.
                61 Có những người từ Tên Mê-la, Tên Hạc-sa, Kê-rúp, Át-đôn, và Im-me cùng đi lên, nhưng họ không thể chứng minh được tổ tiên của họ hay liên hệ huyết thống trong gia tộc của họ, nên không thể định rõ họ có phải là người I-sơ-ra-ên chính thống hay không.
                62 Con cháu của Ðê-la-gia, con cháu của Tô-bi-a, con cháu của Nê-cô-đa, sáu trăm bốn mươi hai người.
                63 Về các tư tế: con cháu của Hô-ba-gia, con cháu của Hắc-cô, con cháu của Ba-xi-lai –Ông ấy là người đã cưới một cô trong các con gái của Ba-xi-lai người Ghi-lê-át làm vợ và đã đổi họ để theo họ vợ– 64 Những người ấy đã truy lục gia phả của họ, nhưng họ không thể tìm thấy gia tộc của họ được liệt kê trong đó, nên họ đã bị loại ra khỏi hàng tư tế và bị xem là không tinh ròng để thi hành chức vụ thánh.  65 Do đó quan tổng trấn truyền cho họ không được ăn các món ăn cực thánh cho đến khi được một tư tế đứng ra dùng u-rim và thu-mim để xác quyết.
                66 Tổng cộng cả hội chúng được bốn mươi hai ngàn ba trăm sáu mươi người, 67 không kể bảy ngàn ba trăm ba mươi bảy người là các tôi trai và tớ gái; trong vòng họ cũng có hai trăm bốn mươi lăm người, cả nam lẫn nữ, là thành viên của ca đoàn thờ phượng.
                68 Toàn dân có được bảy trăm ba mươi sáu con ngựa, hai trăm bốn mươi lăm con la, 69 bốn trăm ba mươi lăm con lạc đà, và sáu ngàn bảy trăm hai mươi con lừa.
                70 Một số các trưởng tộc đã đóng góp vào quỹ tái thiết.  Tổng trấn đóng góp vào trong kho một ngàn miếng vàng, năm mươi tô vàng, và năm trăm ba mươi bộ lễ phục cho các tư tế.  71 Các vị trưởng tộc đã đóng góp vào trong kho hai mươi ngàn miếng vàng và hai ngàn hai trăm thỏi bạc.  72 Dân chúng còn lại đã đóng góp hai mươi ngàn miếng vàng, hai ngàn thỏi bạc, và sáu mươi bảy bộ lễ phục cho các tư tế.
                73 Như vậy các tư tế, những người Lê-vi, những người canh cửa, những người ca hát, những người phục vụ nơi Ðền Thờ, và một số người nữa, nói chung mọi người I-sơ-ra-ên đều được định cư trong các thành của họ.  Ðến tháng thứ bảy dân I-sơ-ra-ên đã ổn định chỗ ở trong các thành của họ.

                """]
            ]),
        Chapter(8, passages: [
            ["Ê-xơ-ra Tuyên Ðọc Luật Pháp và Cử Hành Lễ Lều Tạm": """
                1 Khi ấy mọi người đều nhóm lại với nhau như một người tại quảng trường ở Cổng Nước.  Họ nói với Ê-xơ-ra giáo sư kinh luật, xin ông đem bộ Sách Luật Pháp của Môi-se mà CHÚA đã truyền cho dân I-sơ-ra-ên đến.  2 Vì thế ngày mồng một tháng bảy, Tư Tế Ê-xơ-ra đem bộ sách đến trước hội chúng, gồm những người lớn nam và nữ và những thiếu niên có thể nghe và hiểu được, để đọc cho họ nghe từ sáng sớm cho đến giữa trưa.  3 Ông đứng ở quảng trường đối diện với Cổng Nước và đọc lớn tiếng những lời đã chép trong đó trước mặt những người lớn nam và nữ, cùng những thiếu niên có thể hiểu được.  Mọi người đều chăm chú lắng nghe Luật Pháp.  4 Ê-xơ-ra giáo sư kinh luật đứng trên một bục gỗ được đóng sẵn cho dịp này.  Ðứng bên cạnh ông, bên phải có Mát-ti-thi-a, Sê-ma, A-na-gia, U-ri-gia, Hinh-ki-a, và Ma-a-sê-gia; và bên trái có Pê-đa-gia, Mi-sa-ên, Manh-ki-gia, Ha-sum, Hách-ba-đa-na, Xa-cha-ri-a, và Mê-su-lam.  5 Ê-xơ-ra mở sách ra trước mặt mọi người; vì ông đứng cao hơn mọi người, nên ai nấy đều nhìn thấy ông.  Khi ông mở sách ra, mọi người đều đứng dậy.  6 Ê-xơ-ra ca ngợi CHÚA, Ðức Chúa Trời cao cả.  Bấy giờ mọi người đều đưa hai tay lên trời và đáp lại, “A-men! A-men!”  Kế đó họ cúi đầu và sấp mặt xuống đất mà thờ lạy CHÚA.
                7 Lúc ấy Giê-sua, Ba-ni, Sê-rê-bi-a, Gia-min, Ạc-cúp, Sa-bê-thai, Hô-đi-a, Ma-a-sê-gia, Kê-li-ta, A-xa-ri-a, Giô-xa-bát, Ha-nan, Pê-la-gia, những người Lê-vi, đã giúp cho dân hiểu được luật pháp, trong khi dân vẫn cứ đứng yên tại chỗ.  8 Họ đọc trong Sách Luật Pháp của Ðức Chúa Trời một cách rõ ràng và giải thích ý nghĩa những lời ấy, khiến ai nấy đều hiểu rõ những gì họ đọc.
                9 Bấy giờ Nê-hê-mi tổng trấn, Ê-xơ-ra giáo sư kinh luật kiêm tư tế, và những người Lê-vi giảng dạy cho dân.  Họ nói với toàn dân, “Hôm nay là ngày thánh dành cho CHÚA, Ðức Chúa Trời của anh chị em.  Ðừng than thở và khóc lóc.”  Vì toàn dân đã bật khóc khi nghe những lời của Luật Pháp.  10 Sau đó Nê-hê-mi nói với họ, “Ai nấy hãy đi về, hãy ăn những món béo bổ, hãy uống những thức ngọt ngon, và hãy gởi phần cho những người không có gì để ăn uống, vì hôm nay là ngày thánh dành cho CHÚA chúng ta.  Ðừng buồn, vì niềm vui của CHÚA là sức mạnh của anh chị em.”
                11 Những người Lê-vi cũng trấn an mọi người, bảo rằng, “Xin anh chị em hãy bình tĩnh, vì hôm nay là ngày thánh; đừng buồn.”  12 Thế là mọi người ra về, ăn, uống, và gởi phần ẩm thực.  Họ rất đỗi mừng, vì hiểu được những lời đã công bố cho mình.
                13 Ngày thứ nhì tất cả các trưởng tộc trong dân, cùng với các tư tế, và những người Lê-vi đã họp lại với Ê-xơ-ra giáo sư kinh luật để học hỏi những lời của Luật Pháp tường tận hơn.  14 Họ tìm thấy trong Luật Pháp có ghi rằng CHÚA truyền cho Môi-se bảo dân I-sơ-ra-ên phải ở trong các lều trong kỳ dự lễ tháng bảy, 15 và họ phải công bố và loan truyền trong tất cả các thành và trong Giê-ru-sa-lem rằng, “Hãy lên núi, đem những nhánh ô-liu, những nhánh thông, những cành sim, những cành kè, những cành cây rậm lá về làm lều để ở, y như đã chép.”
                16 Thế là dân chúng đi ra, mang những nhánh cây ấy về, và làm lều để ở.  Họ làm các lều lá ấy trên các sân thượng, trước sân nhà của họ, trong sân của nhà Ðức Chúa Trời, trong quảng trường ở Cổng Nước, và trong quảng trường ở Cổng Ép-ra-im.  17 Vậy cả tập thể những người từ chốn lưu đày trở về đã làm những lều lá và tạm trú trong các lều ấy suốt kỳ lễ.  Số là từ ngày Giô-suê con của Nun cho đến ngày ấy, dân I-sơ-ra-ên chưa hề làm như thế bao giờ.  Do đó mọi người đều vui mừng khôn xiết.
                18 Ngày nào cũng vậy, từ ngày đầu cho đến ngày cuối của kỳ lễ, Ê-xơ-ra đọc trong Sách Luật Pháp của Ðức Chúa Trời.  Họ cử hành lễ suốt bảy ngày; đến ngày thứ tám, họ cử hành một lễ bế mạc rất trọng thể, y như đã quy định.

                """]
            ]),
        Chapter(9, passages: [
            ["Lễ Thờ Phượng Sám Hối": """
                1 Vào ngày hai mươi bốn tháng ấy, dân I-sơ-ra-ên họp lại với nhau để kiêng ăn, mặc vải thô, và rắc bụi đất trên đầu.  2 Dân I-sơ-ra-ên tự tách biệt họ ra khỏi mọi người thuộc các chủng tộc khác.  Họ đứng dậy xưng tội của họ và tội của tổ tiên họ.  3 Họ đứng tại chỗ của họ và đọc Luật Pháp của Ðức Chúa Trời của họ trong nửa buổi, còn nửa buổi kia họ xưng tội và thờ phượng CHÚA, Ðức Chúa Trời của họ.
                4 Bấy giờ Ba-ni, Giê-sua, Cát-mi-ên, Sê-ba-ni-a, Bun-ni, Sê-rê-bi-a, Ba-ni, và Kê-na-ni đứng trên các bục dành cho người Lê-vi và lớn tiếng kêu cầu với CHÚA, Ðức Chúa Trời của họ.  5 Kế đó những người Lê-vi là Giê-sua, Cát-mi-ên, Ba-ni, Ha-sáp-nê-gia, Sê-rê-bi-a, và Pê-tha-hi-a nói, “Hãy đứng dậy và ca ngợi CHÚA, Ðức Chúa Trời của anh chị em, Ðấng hiện hữu từ vô cùng trong quá khứ cho đến vô cùng trong tương lai.” Họ nói tiếp, “Chúc tụng danh vinh hiển của Ngài.  Nguyện danh Ngài trỗi cao trên mọi lời chúc tụng và tôn vinh.”
                6 Bấy giờ Ê-xơ-ra nói, “Ôi, chỉ một mình Ngài là CHÚA, Ðấng có một không hai.  Chính Ngài đã dựng nên các từng trời và trời của các từng trời, cùng toàn thể thiên binh; Ngài đã dựng nên trái đất và mọi vật trên đất, biển và mọi vật trong biển.  Chính Ngài ban sự sống cho muôn loài vạn vật.  Toàn thể thiên binh thiên sứ đều sấp mình xuống thờ phượng Ngài.  
                7 Ngài là CHÚA, Ðức Chúa Trời, Ðấng đã chọn Áp-ram và đem ông ra khỏi U-rơ của người Canh-đê, và ban cho ông tên Áp-ra-ham.  8 Ngài đã thấy lòng ông trung thành với Ngài, nên đã lập với ông một giao ước, ban cho dòng dõi ông đất của dân Ca-na-an, dân Hi-ti, dân A-mô-ri, dân Pê-ri-xi, dân Giê-bu-si, và dân Ghi-ga-si.  Ngài đã giữ những lời hứa của Ngài, vì Ngài là Ðấng công chính.  
                9 Ngài đã nhìn thấy cảnh khốn cùng của tổ tiên chúng con ở Ai-cập; Ngài đã nghe tiếng khóc than của họ bên bờ Hồng Hải.  10 Ngài đã sai các phép lạ và các dấu kỳ của Ngài đến đối phó với Pha-ra-ôn, với bầy tôi của vua ấy, và với toàn dân trong xứ đó, vì Ngài biết rõ dân Ai-cập đã đối xử với họ cách hống hách như thế nào.  Ngài đã làm cho danh Ngài được lừng lẫy cho đến ngày nay.  11 Ngài đã rẽ biển ra trước mặt họ, để họ có thể đi qua giữa lòng biển trên đất khô; còn những kẻ đuổi theo họ, Ngài quăng chúng vào vực thẳm như một cục đá bị ném vào dòng nước mạnh.  12 Ngoài ra Ngài đã dẫn đưa họ ban ngày bằng một trụ mây và ban đêm bằng một trụ lửa để soi sáng cho họ trên con đường họ phải đi qua.  
                13 Ngài cũng đã ngự xuống trên Núi Si-nai; từ trời Ngài đã phán dạy họ.  Ngài đã ban cho họ các mạng lịnh chính trực, các luật pháp chân chính, cùng các luật lệ và các điều răn toàn hảo.  14 Ngài đã tỏ cho họ biết ngày Sa-bát thánh của Ngài, và đã ban cho họ các điều răn, luật lệ, và luật pháp của Ngài qua Môi-se tôi tớ Ngài.  15 Ðể họ khỏi đói Ngài đã ban bánh từ trời xuống cho họ ăn; để họ khỏi khát Ngài đã khiến nước ngọt từ vầng đá tuôn ra cho họ uống.  Ngài đã bảo họ đi vào chiếm lấy xứ mà Ngài đã thề sẽ ban cho họ.  
                16 Nhưng họ, tổ tiên của chúng con, đã ngang ngược và cứng cổ; họ đã không vâng theo các điều răn của Ngài.  17 Họ đã không vâng lời và cũng không nhớ gì đến các phép lạ Ngài đã làm ở giữa họ, nhưng đã cứng cổ, và trong cơn phản loạn họ đã lập một kẻ lãnh đạo để dẫn họ trở về làm nô lệ.  Nhưng Ngài là Ðức Chúa Trời sẵn lòng tha thứ, khoan dung độ lượng, thương xót, chậm giận, và đầy dẫy tình thương.  Ngài đã không bỏ họ, 18 ngay cả khi họ đúc cho họ một pho tượng của một con bê và nói, ‘Ðây là thần của ngươi, đấng đã dẫn ngươi ra khỏi Ai-cập,’ và như thế họ đã xúc phạm đến Ngài thật nặng nề.  
                19 Dù vậy do lòng thương xót vô biên của Ngài, Ngài đã không bỏ họ bơ vơ trong đồng hoang.  Ban ngày trụ mây dẫn đường họ vẫn không lìa khỏi họ; ban đêm trụ lửa soi sáng họ trên hành trình họ phải đi qua vẫn không rời khỏi họ.  20 Ngài đã ban Thần Linh thiện hảo của Ngài để dạy dỗ họ.  Ngài đã không giữ bánh ma-na khỏi miệng họ; Ngài đã ban cho họ nước ngọt để họ không bị khát.  21 Thật vậy trong bốn mươi năm Ngài đã duy trì mạng sống họ trong đồng hoang.  Họ đã chẳng thiếu thốn gì.  Quần áo họ không mòn, đôi chân họ không phù.  
                22 Hơn thế nữa Ngài đã ban các vương quốc và các nước cho họ.  Họ đã chia các nước ấy cho nhau và không chừa lại một miền nào.  Họ đã chiếm lấy xứ sở của Si-hôn vua Hếch-bôn và xứ sở của Óc vua Ba-san.  23 Ngài đã làm cho dòng dõi họ đông như sao trên trời, và Ngài đã đem họ vào trong xứ mà Ngài đã bảo tổ tiên họ hãy vào và chiếm lấy.  24 Vậy con cháu họ đã vào và chiếm lấy xứ.  Ngài đã bắt các dân đang ở trong xứ phải khuất phục trước mặt họ, đó là các dân Ca-na-an.  Ngài đã trao vào tay họ các vua và các dân trong xứ, để họ muốn làm gì với chúng tùy ý họ.  25 Họ đã chiếm lấy những thành trì kiên cố và những vùng đất màu mỡ.  Họ đã chiếm lấy những ngôi nhà chứa đầy mọi thứ tốt đẹp, những giếng nước đã đào sẵn, những vườn nho, những rẫy ô-liu, và những cây ăn trái nhiều vô kể.  Vậy họ đã ăn, được no nê, và trở nên mập béo.  Họ đã khoan khoái hưởng thụ mọi phước hạnh lớn lao mà Ngài ban cho.  
                26 Nhưng họ đã không vâng lời và đã nổi loạn chống lại Ngài.  Họ đã vứt bỏ luật pháp Ngài ra sau lưng họ.  Họ đã giết các tiên tri Ngài, những người đã khuyên bảo họ hãy trở về với Ngài.  Họ đã xúc phạm đến Ngài thật nặng nề.  27 Vì thế Ngài đã phó họ vào tay quân thù của họ để chúng tha hồ áp bức họ.  Tuy nhiên giữa cảnh gian lao khốn khổ họ đã kêu cầu với Ngài.  Từ trời cao Ngài đã nghe tiếng van xin của họ.  Do lòng thương xót vô biên của Ngài, Ngài đã ban cho họ những nhà giải phóng, để giải thoát họ ra khỏi tay của quân thù.  
                28 Nhưng vừa khi họ được nghỉ ngơi, họ lại làm những việc ác nữa trước mặt Ngài.  Do đó Ngài đã phó họ vào tay quân thù của họ để chúng cai trị họ.  Bấy giờ họ mới chịu quay về và kêu cầu với Ngài nữa.  Từ trời Ngài đã nghe tiếng van xin của họ.  Ngài đã giải cứu họ nhiều lần vì lòng thương xót của Ngài.  
                29 Ngài đã cảnh cáo họ phải trở lại và vâng giữ luật pháp Ngài, nhưng họ đã quá kiêu căng tự phụ và không vâng theo các điều răn Ngài.  Họ cứ phạm tội và chống lại luật lệ Ngài, luật lệ mà ai vâng theo sẽ sống.  Họ đã đưa ra đôi vai ương ngạnh, làm cho cổ họ ra cứng, và không chịu nghe lời Ngài.  30 Dù vậy Ngài đã nhẫn nại cưu mang họ suốt bao nhiêu năm dài.  Bởi Ðức Thánh Linh Ngài, Ngài đã cảnh cáo họ về tội lỗi họ qua các vị tiên tri Ngài.  Thế nhưng, họ vẫn một mực không chịu vâng lời.  Do đó Ngài đã phó họ cho các dân ngoại vốn cư ngụ trong xứ.  31 Tuy nhiên do lòng thương xót vô biên của Ngài, Ngài đã không tuyệt diệt họ hay bỏ rơi họ, vì Ngài là Ðức Chúa Trời khoan dung độ lượng và giàu lòng thương xót.
                32 Vậy bây giờ, lạy Ðức Chúa Trời của chúng con, Ðức Chúa Trời vĩ đại, quyền năng, và đáng sợ, Ðấng luôn giữ giao ước yêu thương vô tận của Ngài, xin đừng xem tất cả những khó khăn chúng con đang gánh chịu như một việc nhỏ trước mặt Ngài.  Hoạn nạn lớn đã giáng trên chúng con, trên các vua, các quan, các tư tế, các tiên tri, các tổ tiên, và tất cả dân của chúng con từ ngày các vua A-sy-ri đánh bại chúng con đến ngày nay.  33 Ngài luôn luôn công chính mỗi khi chúng con bị đoán phạt, vì Ngài đã đối xử với chúng con cách thành tín, còn chúng con thì cứ hành động cách gian tà đối với Ngài.  34 Không có vua nào, quan nào, tư tế nào, hay tổ tiên nào của chúng con vâng giữ luật pháp Ngài hoặc làm theo các điều răn Ngài hoặc quan tâm đến những lời cảnh cáo của Ngài đối với họ.  35 Ngược lại khi còn nắm giữ quyền hành trong vương quốc của họ, họ đã không thờ phượng Ngài.  Họ đã hưởng biết bao phước hạnh lớn lao trong đất nước phì nhiêu và rộng lớn Ngài đã ban cho họ, nhưng họ không thờ phượng Ngài và cũng không lìa bỏ những việc làm xấu xa gian tà của họ.  
                36 Cho nên giờ đây chúng con phải trở thành những kẻ nô lệ; chúng con làm nô lệ ngay trên đất nước Ngài đã ban cho tổ tiên chúng con để họ và con cháu họ có thể hưởng những hoa quả dẫy đầy và của cải nhiều vô kể.  Xin Ngài xem, chúng con đang làm những kẻ nô lệ!  37 Vì cớ những tội lỗi của chúng con, các hoa lợi làm ra trên đất nước này đều phải đem nộp cho các vua ngoại bang mà Ngài đã lập lên cai trị chúng con.  Họ có quyền trên thân thể chúng con; còn súc vật của chúng con họ muốn lấy lúc nào thì lấy.  Chúng con thật đang ở giữa một cơn hoạn nạn lớn.”

                """],
            ["Danh Sách Những Người Ký Giao Ước": """
                38 Vì tất cả những lẽ đó, chúng tôi đồng lòng với nhau lập một giao ước nghiêm túc và ghi rõ xuống trên giấy trắng mực đen.  Trong văn kiện được đóng ấn ấy có tên những người lãnh đạo, những người Lê-vi, và các vị tư tế.
                """]
            ]),
        Chapter(10, passages: [
            ["": """
                1 Trên mặt văn kiện được đóng ấn ấy có tên của Tổng Trấn Nê-hê-mi con của Ha-ca-li-a, và Xê-đê-ki-a, 2 Sê-rai-a, A-xa-ri-a, Giê-rê-mi, 3 Pát-khua, A-ma-ri-a, Manh-ki-gia, 4 Hát-túc, Sê-ba-ni-a, Manh-lúc, 5 Ha-rim, Mê-rê-mốt, Ô-ba-đi-a, 6 Ða-ni-ên, Ghin-nê-thôn, Ba-rúc, 7 Mê-su-lam, A-bi-gia, Mi-gia-min, 8 Ma-a-xi-a, Bin-gai, Sê-ma-gia.  Ðây là các tư tế.
                9 Những người Lê-vi có Giê-sua con của A-xa-ni-a, Bin-nui một trong các con của Hê-na-đát, Cát-mi-ên, 10 và những người cộng sự của họ gồm: Sê-ba-ni-a, Hô-đi-a, Kê-li-ta, Pê-la-gia, Ha-nan, 11 Mi-ca, Rê-hốp, Ha-sa-bi-a, 12 Xác-cua, Sê-rê-bi-a, Sê-ba-ni-a, 13 Hô-đi-a, Ba-ni, và Bê-ni-nu.
                14 Các nhà lãnh đạo của dân có Pa-rốt, Pa-hát Mô-áp, Ê-lam, Xát-tu, Ba-ni, 15 Bun-ni, A-xơ-gát, Bê-bai, 16 A-đô-ni-gia, Bích-vai, A-đin, 17 A-te, Hê-xê-ki-a, A-xua, 18 Hô-đi-a, Ha-sum, Bê-xai, 19 Ha-ríp, A-na-thốt, Nê-bai, 20 Mặc-pi-ách, Mê-su-lam, Hê-xia, 21 Mê-sê-xa-bên, Xa-đốc, Gia-đua, 22 Pê-la-ti-a, Ha-nan, A-na-gia, 23 Hô-sê, Ha-na-ni-a, Hạc-súp, 24 Ha-lô-hết, Pin-ha, Sô-béc, 25 Rê-hum, Ha-sáp-na, Ma-a-sê-gia, 26 A-hi-a, Ha-nan, A-nan, 27 Manh-lúc, Ha-rim, và Ba-a-na.

                """],
            ["Tóm Lược Giao Ước": """
                28 Những người còn lại trong dân gồm các tư tế, những người Lê-vi, những người giữ cửa, những người ca hát, những người phục vụ trong Ðền Thờ, và tất cả những ai đã tự tách rời ra khỏi các dân khác chủng tộc trong xứ để hết lòng vâng giữ luật pháp của Ðức Chúa Trời đã cùng với vợ, các con trai, các con gái, và tất cả thiếu niên đủ hiểu biết 29 hiệp với những người thân của họ, tức những nhà quyền quý, để lập một lời nguyền rủa và một lời thệ nguyện, hầu bước đi trong luật pháp của Ðức Chúa Trời, là luật đã ban cho Môi-se tôi tớ của Ðức Chúa Trời, vâng giữ và thực thi mọi điều răn của CHÚA, Ðức Chúa Trời của chúng tôi, cùng các luật lệ và các mạng lịnh của Ngài.
                30 Chúng tôi sẽ không gả con gái chúng tôi cho dân trong xứ và cũng không cưới con gái của họ cho con trai chúng tôi.
                31 Nếu các dân khác chủng tộc trong xứ mang các hàng hóa hay lúa gạo đến bán trong ngày Sa-bát, chúng tôi sẽ không mua của họ bất cứ vật gì trong ngày Sa-bát hay trong ngày lễ thánh.
                Cứ mỗi năm thứ bảy chúng tôi sẽ nghỉ canh tác và sẽ xóa mọi món nợ của nhau.
                32 Chúng tôi tự buộc mình mỗi năm phải đóng góp một số tiền nhất định để trang trải các chi phí cho việc phục vụ nhà Ðức Chúa Trời của chúng tôi.  33 Ðó là các chi phí để làm bánh dâng trên bàn thờ hằng tuần, những của lễ chay định kỳ, những của lễ thiêu định kỳ, chi phí cho những ngày Sa-bát, những ngày lễ đầu tháng, những ngày đại lễ, mua sắm những vật thánh, chi phí cho những của lễ chuộc tội để chuộc tội cho dân I-sơ-ra-ên, và những chi phí khác cho mọi công việc của nhà Ðức Chúa Trời chúng tôi.
                34 Chúng tôi cũng bắt thăm giữa vòng các tư tế, những người Lê-vi, và dân chúng để dâng củi và mang củi đến nhà Ðức Chúa Trời chúng tôi, cứ theo từng chi tộc, vào những thời điểm nhất định, năm này qua năm khác, để đốt trên bàn thờ CHÚA, Ðức Chúa Trời của chúng tôi, y như đã ghi trong luật pháp.
                35 Chúng tôi cũng tự buộc mình hằng năm phải đem đến dâng trong nhà CHÚA những hoa quả đầu mùa của ruộng đất chúng tôi và những trái cây đầu mùa của mọi cây ra trái của chúng tôi.
                36 Chúng tôi sẽ đem đến nhà Ðức Chúa Trời của chúng tôi, tức đem đến cho các tư tế đang thi hành chức vụ trong nhà Ðức Chúa Trời của chúng tôi, con trai đầu lòng của chúng tôi và con vật đầu lòng của súc vật chúng tôi, y như đã ghi trong luật pháp, tức các con vật đầu lòng của đàn bò đàn lừa chúng tôi và của đàn chiên đàn dê chúng tôi.
                37 Ngoài ra chúng tôi sẽ đem phần bột thượng hạng, những của dâng, những trái cây của mỗi cây, rượu và dầu đến các tư tế, tức đem vào các kho của nhà Ðức Chúa Trời của chúng tôi, và đem đến những người Lê-vi một phần mười các sản vật của ruộng đất chúng tôi, vì những người Lê-vi được hưởng nhận các của dâng một phần mười trong các thành ở miền quê.  38 Một tư tế trong dòng dõi của A-rôn sẽ có mặt với những người Lê-vi khi những người Lê-vi tiếp nhận các của dâng một phần mười.  Những người Lê-vi sẽ lấy ra một phần mười từ các của dâng một phần mười để đem đến nhà Ðức Chúa Trời của chúng tôi, tức đem đến các phòng chứa của nhà kho.  39 Dân I-sơ-ra-ên và các con cháu Lê-vi sẽ đem các của dâng lấy ra từ gạo, rượu, và dầu mang đến các phòng chứa, nơi có các vật dụng của đền thánh, nơi các tư tế thi hành chức vụ, và nơi những người giữ cửa và những người ca hát phục vụ.  Chúng tôi sẽ không bỏ bê nhà Ðức Chúa Trời của chúng tôi.

                """]
            ]),
        Chapter(11, passages: [
            ["Dân Số trong Thành Giê-ru-sa-lem Gia Tăng": """
                1 Bấy giờ những người lãnh đạo của dân ở tại Giê-ru-sa-lem và dân còn lại đã bắt thăm với nhau, để cứ mười người thì một người sẽ sống tại thành thánh Giê-ru-sa-lem, còn chín người kia vẫn cứ sống trong các thành khác.  2 Dân chúc phước cho những người tình nguyện dọn đến sống ở Giê-ru-sa-lem.  3 Sau đây là danh sách các quan chức hàng tỉnh sống tại Giê-ru-sa-lem, nhưng dân I-sơ-ra-ên, các tư tế, những người Lê-vi, những người phục vụ Ðền Thờ, và dòng dõi của các tôi tớ Sa-lô-môn đều sống trong các thành của Giu-đa, ai nấy sống trong đất của mình và trong thành của mình.
                4 Tại Giê-ru-sa-lem có một số con cháu của Giu-đa và một số con cháu của Bên-gia-min đến định cư.
                Trong chi tộc Giu-đa có A-tha-gia con của U-xi-a, con của Xa-cha-ri-a, con của A-ma-ri-a, con của Sê-pha-ti-a, con của Ma-ha-la-lên, con cháu của Pê-rê, 5 và Ma-a-sê-gia con của Ba-rúc, con của Côn Hô-xê, con của Ha-xa-gia, con của A-đa-gia, con của Giô-gia-ríp, con của Xa-cha-ri-a, con cháu của Si-lô-ni.  6 Tổng số con cháu của Pê-rê sống tại Giê-ru-sa-lem được bốn trăm sáu mươi tám người dũng mãnh.
                7 Trong chi tộc Bên-gia-min có Sanh-lu con của Mê-su-lam, con của Giô-ết, con của Pê-đa-gia, con của Cô-la-gia, con của Ma-a-sê-gia, con của I-thi-ên, con của Giê-sa-gia.  8 Cùng đi theo ông có Ga-bai và Sanh-lai.  Tất cả gồm chín trăm hai mươi tám chiến sĩ.  9 Người chỉ huy đội quân này là Giô-ên con của Xích-ri; Giu-đa con của Ha-sê-nu-a làm phó thị trưởng.
                10 Trong vòng các tư tế có Giê-đa-gia con của Giô-gia-ríp, Gia-kin, 11 Sê-ra-gia con của Hinh-ki-a, con của Mê-su-lam, con của Xa-đốc, con của Mê-ra-giốt, con của A-hi-túp, người quản lý nhà Ðức Chúa Trời, 12 cùng với những người bà con dòng họ của họ làm việc trong Ðền Thờ, tổng cộng được tám trăm hai mươi hai người.  Ngoài ra có A-đa-gia con của Giê-rô-ham, con của Pê-la-li-a, con của Am-xi, con của Xa-cha-ri-a, con của Pát-khua, con của Manh-ki-gia, 13 cùng với những người bà con dòng họ của ông ấy, những tộc trưởng trong gia tộc của họ, tổng cộng được hai trăm bốn mươi hai người.  Cũng có A-ma-sai con của A-xa-rên, con của A-xai, con của Mê-sin-lê-mốt, con của Im-me, 14 cùng với những người bà con dòng họ của ông ấy, những chiến sĩ dũng mãnh, tổng cộng được một trăm hai mươi tám người.  Người lãnh đạo của họ là Xáp-đi-ên con của Ha-ghê-đô-lim.
                15 Trong vòng những người Lê-vi có Sê-ma-gia con của Hạc-súp, con của A-xơ-ri-cam, con của Ha-sa-bi-a, con của Bun-ni.  16 Sa-bê-thai và Giô-xa-bát là hai người lãnh đạo của người Lê-vi làm những việc bên ngoài nhà Ðức Chúa Trời.  17 Mát-ta-ni-a con của Mi-ca, con của Xáp-đi, con của A-sáp, là trưởng ban hướng dẫn hội chúng dâng lời cầu nguyện cảm tạ; Bạc-bu-ki-gia làm phó ban trong vòng những người bà con dòng họ của ông ấy.  Ngoài ra còn có Áp-đa con của Sam-mua, con của Ga-lanh, con của Giê-đu-thun.  18 Tổng số những người Lê-vi phục vụ trong thành thánh được hai trăm tám mươi bốn người.
                19 Trong vòng những người giữ cửa có Ạc-cúp, Tanh-môn, và những người bà con dòng họ của họ lo việc canh gác ở các cửa, tổng cộng được một trăm bảy mươi hai người.
                20 Những người còn lại của dân I-sơ-ra-ên, cùng với các tư tế và những người Lê-vi, tất cả đều sống trong các thành của Giu-đa, ai nấy đều sống trong sản nghiệp của mình.  21 Nhưng những người phục vụ Ðền Thờ đều sống ở Ô-phên.  Xi-ha và Ghích-pa là hai người chỉ huy của họ.
                22 Người lãnh đạo tất cả những người Lê-vi ở Giê-ru-sa-lem là U-xi con của Ba-ni, con của Ha-sa-bi-a, con của Mát-ta-ni-a, con của Mi-ca, tức con cháu của A-sáp, dòng dõi của những người phụ trách việc ca hát thờ phượng Ðức Chúa Trời tại Ðền Thờ.  23 Về những người ca hát thờ phượng, vua truyền lịnh phải cung cấp một phần cố định hằng ngày cho họ.
                24 Ngoài ra Pê-tha-hi-a con của Mê-sê-xa-bên, dòng dõi của Xê-ra, con cháu của Giu-đa, đã được vua lập làm người giải quyết mọi việc cho dân.

                """],
            ["Các Vùng Ðịnh Cư Bên Ngoài Giê-ru-sa-lem": """
                25 Về các làng mạc và các cánh đồng trực thuộc, một số con cháu của Giu-đa định cư tại Ki-ri-át Ạc-ba và các thị trấn trực thuộc, Ði-bôn và các thị trấn trực thuộc, Giê-cáp-xê-ên và các làng trực thuộc, 26 Giê-sua, Mô-la-đa, Bết Pê-lết, 27 Ha-xa Su-anh, Bê-e Sê-ba và các thị trấn trực thuộc, 28 Xích-lắc, Mê-cô-na và các thị trấn trực thuộc, 29 Ên Rim-môn, Xô-ra, Giạc-mút, 30 Xa-nô-a, A-đu-lam và các làng trực thuộc, La-kích và những cánh đồng trực thuộc, A-xê-ca và các làng trực thuộc.  Như vậy con cháu của Giu-đa định cư từ Bê-e Sê-ba cho đến Thung Lũng của Hin-nôm.
                31 Con cháu của Bên-gia-min định cư từ Ghê-ba trở đi, tại Mích-mát, Ai-gia, Bê-tên và các làng trực thuộc, 32 A-na-thốt, Nốp, A-na-ni-a, 33 Ha-xơ, Ra-ma, Ghi-ta-im, 34 Ha-đi, Xê-bô-im, Nê-ba-lát, 35 Lốt, Ô-nô, và Thung Lũng của Các Nghệ Nhân.
                36 Một số gia tộc người Lê-vi được cắt cử từ Giu-đa đến sống giữa người Bên-gia-min.
                """]
            ]),
        Chapter(12, passages: [
            ["Danh Sách Các Tư Tế và Những Người Lê-vi": """
                1 Sau đây là các tư tế và những người Lê-vi đã hồi hương với Xê-ru-ba-bên con của Sê-anh-ti-ên và với Giê-sua:
                Sê-ra-gia, Giê-rê-mi, Ê-xơ-ra, 2 A-ma-ri-a, Manh-lúc, Hát-túc, 3 Sê-ca-ni-a, Rê-hum, Mê-rê-mốt, 4 I-đô, Ghin-nê-thôi, A-bi-gia, 5 Mi-gia-min, Ma-a-đi-a, Bin-ga, 6 Sê-ma-gia, Giô-gia-ríp, Giê-đa-gia, 7 Sanh-lu, A-mốc, Hinh-ki-a, Giê-đa-gia.  Ðó là những người lãnh đạo các tư tế và những người cộng sự của họ trong thời của Giê-sua.
                8 Về những người Lê-vi có Giê-sua, Bin-nui, Cát-mi-ên, Sê-rê-bi-a, Giu-đa, và Mát-ta-ni-a.  Mát-ta-ni-a là người lãnh đạo những người cộng tác với ông trong việc ca ngợi thờ phượng.  9 Bác-bu-ki-a và Un-nô cùng những người bà con dòng họ của họ đứng đối diện nhau trong khi hành lễ.
                10 Giê-sua sinh Giô-gia-kim.  Giô-gia-kim sinh Ê-li-a-síp.  Ê-li-a-síp sinh Giô-gia-đa.  11 Giô-gia-đa sinh Giô-na-than.  Giô-na-than sinh Gia-đua.
                12 Trong thời của Giô-gia-kim, các tư tế sau đây là trưởng tộc trong gia tộc của họ: gia tộc Sê-ra-gia, Mê-ra-gia; gia tộc Giê-rê-ni-a, Ha-na-ni-a; 13 gia tộc Ê-xơ-ra, Mê-su-lam; gia tộc A-ma-ri-a, Giê-hô-ha-nan; 14 gia tộc Manh-lu-ki, Giô-na-than; gia tộc Sê-ba-ni-a, Giô-sép; 15 gia tộc Ha-rim, Át-na; gia tộc Mê-ra-giốt, Hên-cai; 16 gia tộc I-đô, Xa-cha-ri; gia tộc Ghin-nê-thôn, Mê-su-lam; 17 gia tộc A-bi-gia, Xích-ri; gia tộc Mi-ni-a-min và gia tộc Mô-a-đi-a, Pin-tai; 18 gia tộc Bin-ga, Sam-mua; gia tộc Sê-ma-gia, Giê-hô-na-than; 19 gia tộc Giô-gia-ríp, Mát-tê-nai; gia tộc Giê-đa-gia, U-xi; 20 gia tộc Sanh-lai, Canh-lai; gia tộc A-mốc, Ê-be; 21 gia tộc Hinh-ki-a, Ha-sa-bi-a; gia tộc Giê-đa-gia, Nê-tha-nên.
                22 Về những người Lê-vi, trong thời của Ê-li-a-síp, Giô-gia-đa, Giô-ha-nan, và Gia-đua, người ta ghi vào sổ bộ những người trưởng tộc của gia tộc họ.  Các tư tế cũng được ghi tên vào sổ bộ cho đến triều đại của Ða-ri-út người Ba-tư.
                23 Về con cháu của Lê-vi, các trưởng tộc của gia tộc của họ được ghi tên vào Sách Sử Ký cho đến thời của Giô-ha-nan con của Ê-li-a-síp.  24 Những người lãnh đạo của người Lê-vi gồm có: Ha-sa-bi-a, Sê-rê-bi-a, và Giê-sua con của Cát-mi-ên, cùng với những người bà con dòng họ của họ đứng đối diện với họ để ca ngợi và dâng lời tạ ơn theo như lịnh của Ða-vít, người của Ðức Chúa Trời.  Họ chia ra thành bè đứng ca hát đối đáp với nhau.
                25 Mát-ta-ni-a, Bạc-bu-ki-a, Ô-ba-đi-a, Mê-su-lam, Tanh-môn, và Ạc-cúp là những người giữ cửa; họ đứng gác ở các nhà kho gần các cổng. 26 Những người ấy phục vụ trong thời của Giô-gia-kim con của Giê-sua, con của Giô-xa-đác, và trong thời của Nê-hê-mi làm tổng trấn và Tư Tế Ê-xơ-ra làm giáo sư kinh luật.

                """],
            ["Lễ Khánh Thành Tường Thành Giê-ru-sa-lem": """
                27 Khi ấy có lễ khánh thành bức tường bao quanh Thành Giê-ru-sa-lem.  Người ta tìm những người Lê-vi khắp nơi họ ở, đưa họ về Giê-ru-sa-lem để tổ chức lễ khánh thành, hầu mừng tường thành đã được xây lại xong.  Người ta tổ chức những chương trình tạ ơn có ca hát, phối hợp với các khánh chiêng, các hạc cầm, và các đàn lia.  28 Con cháu của những người ca hát từ các miền phụ cận Giê-ru-sa-lem và từ các làng của người Nê-tô-pha tập họp về.  29 Họ cũng từ Bết Ghinh-ganh, từ những cánh đồng ở Ghê-ba và A-ma-vét kéo đến, vì những người ca hát đã thành lập các làng của họ quanh Giê-ru-sa-lem.  30 Khi ấy các tư tế và những người Lê-vi đã thanh tẩy chính họ, sau đó họ thanh tẩy dân chúng, các cổng thành, và tường thành.
                31 Tôi đưa những người lãnh đạo của Giu-đa lên tường thành và tổ chức hai đại ca đoàn để rước lễ tạ ơn.  Một đại ca đoàn đi trên tường thành tiến về hướng nam, tức về phía Cổng Phân.  32 Ði theo đại ca đoàn đó có Hô-sai-a và phân nửa những người lãnh đạo Giu-đa, 33 cùng với A-xa-ri-a, Ê-xơ-ra, Mê-su-lam, 34 Giu-đa, Bên-gia-min, Sê-ma-gia, và Giê-rê-mi.  35 Tháp tùng có ban kèn của các tư tế, cũng có Xa-cha-ri-a con của Giô-na-than, con của Sê-ma-gia, con của Mát-ta-ni-a, con của Mi-cai-a, con của Xác-cua, con của A-sáp, 36 cùng với những người bà con dòng họ của ông ấy là Sê-ma-gia, A-xa-rên, Mi-la-lai, Ghi-la-lai, Ma-ai, Nê-tha-nên, Giu-đa, và Ha-na-ni sử dụng các nhạc khí của Ða-vít, người của Ðức Chúa Trời.  Họ có Ê-xơ-ra giáo sư kinh luật dẫn đầu.  37 Khi đến Cổng Suối Nước, họ tiến thẳng về phía trước, đi lên các bậc thềm của Thành Ða-vít, và tiến lên đầu tường.  Họ tiếp tục đi trên tường thành phía sau cung Vua Ða-vít và tiến về Cổng Nước ở hướng đông.
                38 Còn đại ca đoàn kia thì đi ngược hướng với họ.  Tôi dẫn phân nửa những người còn lại đi theo sau họ trên tường thành, tiến qua Tháp Các Lò, đến chỗ Tường Rộng, 39 qua Cổng Ép-ra-im, qua Cổng Cũ, qua Cổng Cá, qua Tháp Ha-na-nên, qua Tháp Một Trăm, đến Cổng Chiên, và họ dừng lại ở Cổng Lính Canh.
                40 Kế đến hai đoàn trỗi tiếng cảm tạ và cùng tiến vào khu Ðền Thờ Ðức Chúa Trời.  Tôi và phân nửa những người lãnh đạo đi với tôi cũng làm như vậy; 41 chúng tôi đi với các vị tư tế: Ê-li-a-kim, Ma-a-sê-a, Mi-ni-a-min, Mi-cai-a, Ê-li-ô-ê-nai, Xa-cha-ri-a, và Ha-na-ni-a, những người sử dụng kèn, 42 và quý ông Ma-a-sê-gia, Sê-ma-gia, Ê-lê-a-xa, U-xi, Giê-hô-ha-nan, Manh-ki-gia, Ê-lam, và Ê-xe.  Trong khi đó Giê-ra-hi-a hướng dẫn ca đoàn lớn tiếng ca hát vang lừng.  43 Ngày hôm đó họ dâng nhiều của lễ và rất đỗi vui mừng vì Ðức Chúa Trời đã ban cho họ một niềm vui lớn.  Cả phụ nữ lẫn trẻ em đều cũng vui mừng hoan hỉ.  Niềm vui của Giê-ru-sa-lem đã vang rộng khắp nơi.

                """],
            ["Những Người Phục Vụ CHÚA Ðược Phụ Cấp": """
                44 Ngày hôm đó một số người được lập làm những người quản lý các phòng dùng làm nhà kho để chứa các của dâng, các hoa lợi đầu mùa, và các của dâng một phần mười.  Họ thâu nhận vào các phòng đó những phần được luật pháp quy định dành cho các tư tế và những người Lê-vi, tức những sản phẩm của các ruộng rẫy trực thuộc các thành, vì mọi người ở Giu-đa đều vui thỏa về sự phục vụ của các tư tế và những người Lê-vi.  45 Họ đã thi hành chức vụ Ðức Chúa Trời giao phó cho họ, và họ đã thi hành nghi thức thanh tẩy một cách tốt đẹp.  Những người ca hát và những người giữ cửa cũng thi hành chức vụ rất hoàn hảo theo như lịnh của Ða-vít và của Sa-lô-môn con vua ấy.  46 Số là trong thời của Ða-vít và A-sáp rất lâu về trước, có người đã được lập làm người chỉ huy những người ca hát, và có những bài thánh ca đã được dùng để ca ngợi và tạ ơn Ðức Chúa Trời.  47 Trong thời của Xê-ru-ba-bên và trong thời của Nê-hê-mi, toàn dân I-sơ-ra-ên đã dành riêng những phần phụ cấp để chu cấp hằng ngày cho những người ca hát và những người giữ cửa.  Họ biệt riêng phần của những người Lê-vi ra.  Những người Lê-vi lại trích ra từ phần của họ để chia sẻ cho các con cháu của A-rôn.
                """]
            ]),
        Chapter(13, passages: [
            ["Tách Rời Những Người Dị Chủng Không Thờ CHÚA": """
                1 Ngày hôm đó họ đọc trong sách của Môi-se cho dân nghe.  Họ khám phá trong sách đó viết rằng không một người Am-môn hay một người Mô-áp nào được vào hội của Ðức Chúa Trời, 2 vì chúng đã không dùng bánh và nước tiếp đãi dân I-sơ-ra-ên, ngược lại, chúng đã mướn Ba-la-am đến nguyền rủa họ.  Dầu vậy Ðức Chúa Trời của chúng tôi đã biến sự nguyền rủa đó ra một phước hạnh.  3 Khi dân I-sơ-ra-ên nghe luật pháp nói như thế, họ tự động tách rời khỏi mọi người ngoại quốc sống giữa họ.

                """],
            ["Cải Cách Khác của Nê-hê-mi": """
                4 Trước lúc đó Tư Tế Ê-li-a-síp, người được lập lên để coi sóc các phòng kho cho nhà Ðức Chúa Trời của chúng tôi, và ông lại là một đồng minh của Tô-bi-a.  5 Ông đã tự ý dành riêng cho Tô-bi-a một phòng lớn, đó là phòng trước kia được dùng để chứa các của lễ chay, nhũ hương, các vật dụng của Ðền Thờ, các của dâng một phần mười về lúa gạo, rượu, và dầu, mà theo điều răn thì phải dành cho những người Lê-vi, những người ca hát, và những người giữ cửa, và để chứa các lễ vật được chia cho các tư tế.  6 Việc ấy đã xảy ra khi tôi không có mặt tại Giê-ru-sa-lem, vì năm thứ ba mươi hai của Ạc-ta-xẹc-xe vua Ba-by-lôn tôi phải trở về chầu vua.  Sau một thời gian tôi xin phép vua được ra đi nữa.  7 Tôi về lại Giê-ru-sa-lem và biết được việc tồi tệ mà Ê-li-a-síp đã làm khi ưu đãi Tô-bi-a, tức dành riêng cho hắn một phòng trong sân của Ðền Thờ Ðức Chúa Trời.  8 Tôi rất giận về việc ấy, nên tôi quăng tất cả đồ đạc của Tô-bi-a ra khỏi phòng.  9 Kế đó tôi truyền lịnh thanh tẩy các phòng ấy và đem vào lại các phòng ấy những vật dụng của nhà Ðức Chúa Trời, cùng với các của lễ chay và nhũ hương.  10 Tôi cũng được biết những người Lê-vi đã không nhận được phần của dâng dành cho họ, nên tất cả người Lê-vi và những người ca hát đã trở về làm ruộng.  11 Vì thế tôi quở trách những người lãnh đạo của dân và hỏi họ, “Tại sao nhà Ðức Chúa Trời lại bị bỏ bê?”  Sau đó tôi mời những người Lê-vi và những người ca hát đến và tái lập họ vào chức vụ của họ khi trước.  12 Thấy vậy toàn dân Giu-đa đem một phần mười lúa gạo, rượu, và dầu đến dâng vào các kho của Ðền Thờ.  13 Tôi lập Tư Tế Sê-lê-mi-a, Giáo Sư Kinh Luật Xa-đốc, và một người Lê-vi tên Pê-đa-gia làm các thủ kho của các kho Ðền Thờ.  Ngoài ra có Ha-nan con của Xác-cua, con của Mát-ta-ni-a, làm phụ tá cho họ, vì những người ấy được xem là đáng tin cậy.  Nhiệm vụ của họ là phân chia các của dâng cho các anh em cùng phục vụ với họ.
                14 “Lạy Ðức Chúa Trời của con, xin nhớ đến con trong việc này, và xin đừng xóa bỏ những hành vi tốt đẹp này của con, mà con đã làm cho nhà Ðức Chúa Trời của con và cho sự phục vụ Ngài tại đó.”

                """],
            ["Áp Dụng Triệt Ðể Luật Ngày Sa-bát": """
                15 Trong những ngày ấy tôi thấy có mấy người Giu-đa đạp nho nơi bồn ép nho trong ngày Sa-bát; có người đã chất những bó lúa trên lưng lừa; có những người khác lại bắt lừa chở các vò rượu, các thùng nho, các thùng trái vả, và những bao sản phẩm nặng nề đem vào Giê-ru-sa-lem trong ngày Sa-bát.  Vì thế tôi cảnh cáo họ trong ngày họ đem lương thực đến bán.  16 Một số người quê ở Ty-rơ đang cư ngụ trong miền đó cũng đem cá và các thứ hàng hóa đến bán cho dân Giu-đa ở Giê-ru-sa-lem trong ngày Sa-bát.  17 Thấy vậy tôi quở trách các nhà quyền quý của Giu-đa và nói với họ, “Việc tồi tệ này mà các ông đã làm cho ngày Sa-bát phải ra phàm tục là gì vậy?  18 Há chẳng phải vì tổ tiên của các ông đã làm như thế mà Ðức Chúa Trời chúng ta đã đem tất cả các tai họa này giáng xuống trên chúng ta và trên thành này hay sao?  Ðã vậy bây giờ các ông còn muốn gia thêm cơn thịnh nộ cho dân I-sơ-ra-ên bằng cách làm cho ngày Sa-bát trở nên phàm tục hay sao?”
                19 Kể từ đó tại các cổng thành Giê-ru-sa-lem, mỗi khi trời bắt đầu tối trước ngày Sa-bát, tôi ra lịnh đóng tất cả các cổng thành lại và chỉ mở ra khi ngày Sa-bát đã qua rồi.  Tôi cũng đặt các tôi tớ của tôi ở các cổng thành, để không cho ai mang vật gì nặng vào thành trong ngày Sa-bát.  20 Vì thế các thương gia và những người bán đồ tạp hóa đã đôi phen phải qua đêm bên ngoài cổng thành.  21 Thấy vậy tôi cảnh cáo họ và nói, “Tại sao các người đã qua đêm ở bên ngoài cổng thành?  Nếu các người còn tiếp tục làm thế, tôi sẽ thẳng tay đấy.”  Từ đó trở đi họ không đến trong ngày Sa-bát nữa.  22 Sau đó tôi truyền cho những người Lê-vi hãy thanh tẩy chính họ, rồi đến canh gác ở các cổng thành, để giữ ngày Sa-bát ra thánh.
                “Lạy Ðức Chúa Trời của con, xin nhớ đến con trong việc này nữa, và xin ban phước cho con theo tình thương vô lượng của Ngài.”
                """],
            ["Phản Ðối Những Cuộc Hôn Nhân Dị Chủng và Dị Giáo": """
                23 Trong những ngày ấy tôi thấy các đàn ông Do-thái cưới các phụ nữ Ách-đốt, Am-môn, và Mô-áp làm vợ.  24 Phân nửa con cái của họ chỉ nói được tiếng Ách-đốt và không nói được tiếng Giu-đa.  Chúng chỉ nói được tiếng của mẹ chúng, những người thuộc các giống dân khác không tin thờ Chúa.  25 Vì thế tôi đã tranh luận với họ, nguyền rủa họ, đánh đập một vài người trong bọn họ, và bứt tóc họ.  Tôi bắt họ lấy danh Ðức Chúa Trời mà thề sẽ không làm như thế nữa.  Tôi nói với họ, “Các ông không được gả con gái của các ông cho con trai của chúng, hay cưới con gái của chúng cho con trai của các ông hoặc cho chính các ông.  26 Há chẳng phải Sa-lô-môn vua I-sơ-ra-ên đã phạm tội vì những phụ nữ như thế sao?  Giữa nhiều quốc gia, không một vua nào được như ông ấy.  Ông ấy đã được Ðức Chúa Trời của mình yêu thương, và Ðức Chúa Trời đã lập ông ấy làm vua trên cả I-sơ-ra-ên.  Nhưng các phụ nữ ngoại quốc không tin thờ Chúa đã làm cho ông ấy phạm tội.  27 Thế thì chúng ta há sẽ hành động bội nghịch chống lại Ðức Chúa Trời chúng ta, mà cưới những người phụ nữ ngoại quốc không tin thờ Ngài hay sao?”
                28 Một trong các con trai của Giê-hô-gia-đa, con của Thượng Tế Ê-li-a-síp, đã làm con rể của San-ba-lát người Hô-rô-ni.  Vì thế tôi đã đuổi hắn đi khỏi tôi.
                29 “Lạy Ðức Chúa Trời của con, xin nhớ đến họ, vì họ đã làm bất khiết chức vụ tư tế; họ đã vi phạm quy luật đặc biệt dành cho các tư tế và những người Lê-vi.”
                30 Như vậy tôi đã loại sạch tất cả những ai ngã theo ngoại giáo do mối liên hệ hôn nhân với các dân ngoại không tin thờ Chúa.  Tôi thiết lập rõ ràng nhiệm vụ của các tư tế và những người Lê-vi, đúng theo phần việc của mỗi người.  31 Tôi tổ chức việc cung cấp củi theo định kỳ cho việc dâng của lễ, và tái lập việc dâng hiến các trái cây đầu mùa.
                “Lạy Ðức Chúa Trời của con, xin nhớ đến con và ban phước cho con.”

                """]
            ])
    ]
    
}

